all-of-us/healthpro

templates/program/nph/order/sample-finalize.html.twig
web/assets/css/nph.css

| Jira Ticket(s)      | HPRO-1466

[HPRO-1466] Added back missing eraser.

---

templates/program/nph/index.html.twig

| Target Release?     | 3.6.0
| Jira Ticket(s)      | HPRO-1485

[HPRO-1485] Remove physical measurement text.

---

migrations/Version20230508162708.php
migrations/Version20230508174220.php
src/Entity/NphAliquot.php
src/Entity/NphOrder.php
src/Entity/NphSample.php
src/Service/Nph/NphOrderService.php

| Target Release?     | 3.6.0 
| Jira Ticket(s)      | HPRO-1480

[HPRO-1480] Save timezone info for nph orders

---

src/Controller/NphOrderLookupController.php

| Target Release?     | 3.6.0 
| Jira Ticket(s)      | HPRO-1432

[HPRO-1432] Fix order lookup redirect issue

---

src/Form/Nph/NphOrderType.php
templates/program/nph/order/generate-orders.html.twig
templates/program/nph/participant/index.html.twig
web/assets/css/nph.css
web/assets/js/views/NphOrderCreate.js

| Jira Ticket(s)      | HPRO-1455

[HPRO-1455] Added tooltip, code to color labels, banner alert.

---

templates/program/nph/order/sample-finalize.html.twig

| Jira Ticket(s)      | HPRO-1466

Actually disable eraser icon if sample is disabled.

---

src/Controller/NphOrderController.php
templates/program/nph/participant/index.html.twig
web/assets/css/app.css

| Jira Ticket(s)      | HPRO-1460

[HPRO-1460] Generate orders validate nph dob

---

config/packages/security.yaml
dev_config/config.yml.dist
src/Controller/NphBiobankController.php
src/Security/User.php
templates/base.html.twig
templates/program/nph/biobank/base.html.twig
templates/program/nph/biobank/index.html.twig
templates/program/nph/biobank/participants.html.twig
templates/program/nph/navbar.html.twig

| Jira Ticket(s)      | HPRO-1423

[HPRO-1423] Create NPH biobank participant lookup by biobank id

---

src/Controller/NphBiobankController.php
src/Form/Nph/NphSampleLookupType.php
templates/program/nph/biobank/index.html.twig

| Jira Ticket(s)      | HPRO-1418

[HPRO-1418] Create NPH biobank sample lookup

---

config/packages/security.yaml
src/Controller/DefaultController.php
src/Controller/NphBiobankController.php
src/Entity/NphOrder.php
src/Entity/NphSample.php
src/EventListener/RequestListener.php
src/Service/SiteService.php
templates/program/hpo/navbar.html.twig
templates/program/nph/biobank/index.html.twig
templates/program/nph/biobank/order-collect-details.html.twig
templates/program/nph/biobank/participant.html.twig
templates/program/nph/navbar.html.twig
templates/program/nph/order/macros/display-text.html.twig
templates/program/nph/participant/index.html.twig
tests/Entity/NphOrderTest.php
tests/Entity/NphSampleTest.php

| Jira Ticket(s)      | HPRO-1420

[HPRO-1420] Create NPH participant details and order collection details pages

---

src/Controller/NphBiobankController.php
src/Controller/NphOrderLookupController.php
templates/program/nph/biobank/index.html.twig
templates/program/nph/navbar.html.twig
templates/program/nph/order/orderlookup.html.twig

| Jira Ticket(s)      | HPRO-1417

[HPRO-1417] Added biobank order lookup route.

---

templates/program/nph/navbar.html.twig

| Jira Ticket(s)      | HPRO-1420

[HPRO-1420] Bold biobank navbar only when current nav is biobank

---

templates/program/nph/order/macros/display-text.html.twig

| Jira Ticket(s)      | HPRO-1419

[HPRO-1419] Fix for error causing aliquot's being unable to be finalized.

---

src/Controller/NphBiobankController.php
src/Controller/NphOrderController.php
src/EventListener/RequestListener.php
templates/program/nph/order/sample-aliquot-lookup.html.twig
templates/program/nph/order/sample-finalize.html.twig

| Jira Ticket(s)      | HPRO-1419

[HPRO-1419] Fix instruction pdf asking for site select, use biobank base.

---

src/Controller/NphBiobankController.php
templates/program/nph/order/sample-aliquot-lookup.html.twig
templates/program/nph/order/sample-finalize.html.twig

| Jira Ticket(s)      | HPRO-1418

[HPRO-1418] Fix sample not found error

---

templates/program/nph/biobank/order-collect-details.html.twig
templates/program/nph/order/macros/display-text.html.twig
templates/program/nph/order/partials/sample-finalize-participant-details-biobank.html.twig
templates/program/nph/order/partials/sample-finalize-participant-details.html.twig
templates/program/nph/order/sample-finalize.html.twig

| Jira Ticket(s)      | HPRO-1419

[HPRO-1419] Fixed feedback, display timezones, remove participant info from banner.

---

src/Controller/NphOrderLookupController.php

| Jira Ticket(s)      | HPRO-1417

[HPRO-1417] If a redirect response, redirect.

---

src/Controller/NphBiobankController.php
templates/program/nph/order/orderlookup.html.twig

| Jira Ticket(s)      | HPRO-1417

[HPRO-1417] Extend correct base.

---

templates/program/nph/biobank/order-collect-details.html.twig
templates/program/nph/order/collect.html.twig
templates/program/nph/order/macros/display-text.html.twig

| Target Release?     | 3.7.1 
| Jira Ticket(s)      | HPRO-1519

[HPRO-1519] Fix duplicate macros name

---

templates/program/nph/navbar.html.twig

| Target Release?     | 3.8.0 
| Jira Ticket(s)      | HPRO-1487

[HPRO-1487] Add aliquot samples link to NPH navbar

---

templates/program/nph/order/partials/sample-finalize-confirmation-modal.html.twig
templates/program/nph/order/sample-finalize.html.twig
web/assets/css/app.css
web/assets/js/views/NphSampleFinalize.js

| Target Release?     | 3.8.0
| Jira Ticket(s)      | HPRO-1491, HPRO-1524

[HPRO-1491] [HPRO-1524] Style finalize warning modal window and implement warn unsaved warning

---

templates/program/nph/participant/index.html.twig

| Target Release?     | 3.8.0
| Jira Ticket(s)      | HPRO-1521

[HPRO-1521] Update no DOB banner message

---

src/Helper/WorkQueue.php
src/Service/WorkQueueService.php
templates/participant/details.html.twig
templates/workqueue/index.html.twig
tests/Helper/WorkQueueTest.php
tests/Service/WorkQueueServiceTest.php

| Target Release?     | 3.8.0 
| Jira Ticket(s)      | HPRO-1137

[HPRO-1137] Health Data Stream Sharing.

---

src/Helper/WorkQueue.php
templates/participant/details.html.twig
tests/Helper/WorkQueueTest.php

| Target Release?     | 3.8.0 
| Jira Ticket(s)      | HPRO-1137

[HPRO-1137] Fix Health Data Sharing field status

---

src/Helper/WorkQueue.php

| Target Release?     | 3.8.0 
| Jira Ticket(s)      | HPRO-1137

[HPRO-1137] Fix sort column

---

src/Service/HelpService.php
templates/help/sop.html.twig

| Jira Ticket(s)      | HPRO-1497

[HPRO-1497] Added spanish titles for spanish SOPs

---

composer.json
composer.lock
config/bundles.php
src/Controller/NphPDFController.php
src/Service/PDFService.php
symfony.lock
templates/program/nph/pdf/biospecimen-label.html.twig

| Jira Ticket(s)      | HPRO-1425

[HPRO-1425] Added datamatrix to NPH Labels.

---

templates/review/today.html.twig
web/assets/js/views/review.js
web/assets/js/views/today.js

| Jira Ticket(s)      | HPRO-1005

[HPRO-1005] Add export to Todays Participant Review

---

templates/review/today.html.twig
web/assets/js/views/review.js

| Jira Ticket(s)      | HPRO-1005

[HPRO-1005] Enable export button if there are less than 5 participants

---

templates/program/nph/order/collect.html.twig
web/assets/css/app.css

| Jira Ticket(s)      | HPRO-1492

[HPRO-1492] Display stool reminder banner message

---

src/Helper/WorkQueue.php
templates/partials/workqueue-advance-filters.html.twig
templates/participant/details.html.twig
tests/Helper/WorkQueueTest.php

| Jira Ticket(s)      | HPRO-1452

[HPRO-1452] Fixed filter reset not working, removed withdrawn and deactivated filter

---

src/Helper/WorkQueue.php

| Composer updates?   |❌ 
| Jira Ticket(s)      | HPRO-1452

[HPRO-1452] Fix for sorting by ancillary study.

---

src/Helper/WorkQueue.php

| Jira Ticket(s)      | HPRO-1452

[HPRO-1452] Change Column Name.

---

src/Repository/MeasurementRepository.php

| Jira Ticket(s)      | HPRO-1486

[HPRO-1486] In person tab - sort PMs by desc order

---

templates/program/nph/order/sample-finalize.html.twig
web/assets/css/app.css

| Jira Ticket(s)      | HPRO-1493

[HPRO-1493] Aliquot collapse pdf instructions

---

templates/biobank/index.html.twig
templates/biobank/orders-quanum-today.html.twig
templates/biobank/orders-recent-modify.html.twig
templates/biobank/orders-today.html.twig
templates/biobank/orders-unfinalized.html.twig
templates/biobank/orders-unlocked.html.twig
templates/emails/deceased-pending.txt.twig
templates/program/hpo/index.html.twig
templates/program/hpo/navbar-bs5.html.twig
templates/program/hpo/navbar.html.twig
templates/program/nph/biobank/index.html.twig
templates/program/nph/biobank/partials/review-page-heading.html.twig
templates/program/nph/index.html.twig
templates/program/nph/navbar.html.twig
templates/program/nph/review/page_heading.html.twig
templates/program/nph/review/recently_modified.html.twig
templates/program/nph/review/today.html.twig
templates/program/nph/review/unfinalized.html.twig
templates/review/_page_heading.html.twig
templates/review/modified_measurements.html.twig
templates/review/modified_orders.html.twig
templates/review/today.html.twig
templates/review/unfinalized_measurements.html.twig
templates/review/unfinalized_orders.html.twig

| Jira Ticket(s)      | HPRO-1490

[HPRO-1490] Rename Participant Review to Daily Review

---

src/Controller/OnSiteDetailsReportingController.php
src/Repository/PatientStatusRepository.php
src/Service/OnSiteDetailsReportingService.php
templates/onsite/patient-status.html.twig
tests/Service/OnSiteDetailsReportingServiceTest.php
web/assets/js/views/OnSitePatientStatus.js

| Jira Ticket(s)      | HPRO-1148

[HPRO-1148] Added site filter to on site details report.

---

src/Helper/NphParticipant.php
src/Service/Nph/NphParticipantSummaryService.php
templates/program/nph/participant/index.html.twig
tests/Helper/NphParticipantTest.php

| Jira Ticket(s)      | HPRO-1382

[HPRO-1382] Determine module using RDR field

---

src/Service/ReviewService.php

| Target Release?     | 3.1.0.0 
| Jira Ticket(s)      | HPRO-1202

[HPRO-1202] Display incentive date of service in today's participant page

---

src/Controller/ReviewController.php
src/Service/ReviewService.php
templates/review/today.html.twig

| Jira Ticket(s)      | HPRO-1202

[HPRO-1202] Fix incentive DOS filter issue

---

templates/onsite/patient-status.html.twig

| Jira Ticket(s)      | HPRO-1148

[HPRO-1148] Removed extra elements, changed text.

---

src/Controller/OnSiteDetailsReportingController.php
src/Repository/PatientStatusRepository.php
tests/Repository/PatientStatusRepositoryTest.php
web/assets/js/views/OnSitePatientStatus.js

| Jira Ticket(s)      | HPRO-1148

[HPRO-1148] Run extra query to get possible sites.

---

web/assets/js/views/NphSampleFinalize.js

| Jira Ticket(s)      | HPRO-1471 
https://github.com/all-of-us/healthpro/assets/6041980/7deb8ee8-96e2-490f-b40f-ef7f6c1f2569

[HPRO-1471] Auto focus to volume tab when barcode is scanned

---

src/Repository/PatientStatusRepository.php

| Target Release?     | 3.10.1 
| Jira Ticket(s)      | HPRO-1561

[HPRO-1561] Added site filter to pagination count.

---

src/Controller/NphBiobankController.php
src/Controller/NphOrderController.php
src/Helper/NphParticipant.php
src/Nph/Order/Modules/Module1.php
src/Nph/Order/Modules/Module2.php
src/Nph/Order/Modules/Module3.php
src/Nph/Order/Visits/VisitDSMT.php
src/Service/Nph/NphOrderService.php
src/Service/Nph/NphParticipantSummaryService.php
src/Service/Nph/NphProgramSummaryService.php
templates/admin/debug/participant.html.twig
templates/program/nph/admin/debug/participant.html.twig
templates/program/nph/order/partials/sample-finalize-banner-message.html.twig
templates/program/nph/order/sample-finalize.html.twig
templates/program/nph/participant/index.html.twig
templates/program/nph/participant/partials/display-diet.html.twig
tests/Helper/NphParticipantTest.php
tests/Service/NphOrderServiceTest.php
tests/Service/data/order_module_2.json
web/assets/css/app.css
web/assets/js/views/NphOrderCreate.js

| Jira Ticket(s)      | HPRO-1545

[HPRO-1545] Block Collections for Non-Active Diets in M2 and M3

---

src/Helper/WorkQueue.php
web/assets/css/app.css

| Target Release?     | 3.11.0
| Jira Ticket(s)      | HPRO-1472

[HPRO-1472] Fixes for improper display and ordering.

---

src/Helper/WorkQueue.php

| Target Release?     | 3.11.0 
| Jira Ticket(s)      | HPRO-1472

[HPRO-1472] Removed extra quotation mark.

---

src/Helper/NphParticipant.php
templates/program/nph/order/partials/sample-finalize-banner-message.html.twig
templates/program/nph/participant/index.html.twig
templates/program/nph/participant/partials/display-diet.html.twig
tests/Helper/NphParticipantTest.php

| Jira Ticket(s)      | HPRO-1545

[HPRO-1545] Handle incomplete diet status

---

templates/program/nph/order/generate-orders.html.twig
templates/program/nph/participant/index.html.twig

| Jira Ticket(s)      | HPRO-1570

[HPRO-1570] Remove hair nail opt-in module1/2

---

src/Helper/NphParticipant.php
src/Service/Nph/NphParticipantSummaryService.php
templates/program/nph/participant/index.html.twig
tests/Service/NphParticipantReviewServiceTest.php

| Jira Ticket(s)      | HPRO-1578

[HPRO-1578] Auto select participant module, only display assigned modules.

---

src/Controller/DefaultController.php
templates/base.html.twig
templates/program/nph/navbar.html.twig

| Jira Ticket(s)      | HPRO-1510

[HPRO-1510] Fix page notices on home page

---

templates/program/nph/participant/index.html.twig

| Jira Ticket(s)      | HPRO-1579

[HPRO-1579] Expand only active diets in participant summary page

---

templates/partials/modals/site-select-bs5.html.twig
templates/partials/modals/site-select.html.twig

| Jira Ticket(s)      | HPRO-1583

[HPRO-1583] Fix select site modal switch button issue for NPH users

---

templates/program/nph/order/macros/display-text.html.twig

| Jira Ticket(s)      | HPRO-1568

[HPRO-1568] Fix status label colors

---

src/Entity/NphSample.php
src/Form/Nph/NphOrderType.php

| Jira Ticket(s)      | HPRO-1279

[HPRO-1279] Fix module 2 & 3 stool sample validation issue

---

templates/program/nph/order/sample-finalize.html.twig
web/assets/js/views/NphSampleFinalize.js

| Jira Ticket(s)      | HPRO-1592 
Readded the eraser icon to aliquot page.

[HPRO-1592] Readded eraser icon

---

src/Service/Nph/NphParticipantSummaryService.php

| Jira Ticket(s)      | HPRO-1279

[HPRO-1279] Remove nphBiospecimens field from NPH admin participant lookup tool

---

src/Service/Nph/NphParticipantSummaryService.php

| Jira Ticket(s)      | HPRO-1545

[HPRO-1545] Include module diet status fields in biobank id lookup

---

templates/deceasedreports/new.html.twig
templates/deceasedreports/review.html.twig

| Jira Ticket(s)      | HPRO-1546

[HPRO-1546] Disable enter and prevent resubmit in deceased reports forms

---

templates/program/nph/index.html.twig
templates/program/nph/navbar-bs5.html.twig
web/assets/css/nph.css

| Jira Ticket(s)      | HPRO-1537

[HPRO-1537] Added and converted NPH toolbar/index to bootstrap 5

---

templates/partials/participant-consent.html.twig

| Jira Ticket(s)      | HPRO-1555

[HPRO-1555] Removed DV EHR Consent Box

---

src/Service/JiraService.php

| Jira Ticket(s)      | HPRO-1139

[HPRO-1139] Changed release ticket creation to be release type ticket

---

templates/partials/modals/participant-barcode.html.twig
templates/participant/details.html.twig
templates/program/nph/order/dlw-collect.html.twig
templates/program/nph/participant/index.html.twig
web/assets/css/hpo.css
web/assets/css/nph.css
web/assets/js/views/NphParticipantSummary.js

| Jira Ticket(s)      | HPRO-1552

[HPRO-1552] [HPRO-1581] Added participant barcode modal.

---

src/Controller/CronController.php
src/Repository/OrderRepository.php
src/Service/BiobankNightlyReportService.php
src/Service/GcsBucketService.php
tests/Repository/OrderRepositoryTest.php
tests/Service/BiobankNightlyReportServiceTest.php

| Jira Ticket(s)      | HPRO-1522

[HPRO-1522] Generate biobank nightly report file and upload to GCS bucket

---

src/Controller/DefaultController.php

| Target Release?     | 3.12.1 
| Jira Ticket(s)      | HPRO-1600

[HPRO-1600] Fix biobank redirect issue

---

src/Entity/NphSample.php
templates/program/nph/order/collect.html.twig
templates/program/nph/order/macros/display-text.html.twig

| Jira Ticket(s)      | HPRO-1512

[HPRO-1512] NPH update unlock banner messages

---

config/packages/security.yaml
src/Controller/DefaultController.php

| Target Release?     | 3.12.2 
| Jira Ticket(s)      | HPRO-1603

[HPRO-1603] Fix biobank forbidden errors

---

src/Helper/WorkQueue.php

| Jira Ticket(s)      | HPRO-1575

[HPRO-1575] Disable sort for HealthDataSharingStatus field

---

src/Controller/NphOrderController.php
src/Form/DlwType.php
templates/program/nph/pdf/biospecimen-label.html.twig

| Jira Ticket(s)      | HPRO-1392

[HPRO-1392] Change scale of DLW weight, update route to attribute, add timezone.

---

config/packages/security.yaml

| Target Release?     | 3.12.2 
| Jira Ticket(s)      | HPRO-1603

[HPRO-1603] Fix nph permission issue

---

src/Nph/Order/Modules/Module3.php
src/Nph/Order/Visits/Visit3DSMT.php
src/Nph/Order/Visits/Visit3Diet.php
src/Nph/Order/Visits/Visit3LMT.php

| Jira Ticket(s)      | HPRO-1280

[HPRO-1280] Added module 3 specific visits, removed extra samples from diet

---

src/Nph/Order/Samples/Module3.json
src/Nph/Order/Visits/VisitDLW.php

[HPRO-1610] Updated timepoints, and collection identifiers.

---

src/Repository/SiteRepository.php
src/Service/EmailNotificationService.php
tests/Repository/SiteRepositoryTest.php

| Jira Ticket(s)      | HPRO-1484

[HPRO-1484] Withdrawal notification email issue

---

templates/participant/details.html.twig
templates/program/nph/participant/index.html.twig

| Jira Ticket(s)      | HPRO-1552

[HPRO-1552] Made barcode smaller, moved barcode to before module badge

---

templates/program/hpo/index.html.twig

| Jira Ticket(s)      | HPRO-1554

[HPRO-1554] Set default tab for on-site details reporting

---

templates/program/nph/participant/index.html.twig
web/assets/css/nph.css

| Jira Ticket(s)      | HPRO-1585

[HPRO-1585] Display right icon for open & closed state

---

config/packages/twig.php
src/Controller/DeceasedReportsController.php
src/Controller/MeasurementsController.php
src/Controller/OrderController.php
src/Controller/ParticipantDetailsController.php
src/Repository/SiteRepository.php
src/Service/MeasurementService.php
src/Service/OrderService.php
src/Service/SiteService.php
templates/base.html.twig
templates/macros/display-text.html.twig
templates/measurement/index.html.twig
templates/order/collect.html.twig
templates/order/finalize.html.twig
templates/order/header.html.twig
templates/order/process.html.twig
templates/partials/modals/site-select-bs5.html.twig
templates/partials/modals/site-select.html.twig
templates/partials/participant-id-verification.html.twig
templates/partials/participant-incentive.html.twig
templates/partials/participant-measurement-list-bs5.html.twig
templates/partials/participant-orders-list-bs5.html.twig
templates/partials/participant-patient-status.html.twig
templates/participant/details.html.twig
tests/Repository/SiteRepositoryTest.php
tests/Service/MeasurementServiceTest.php
tests/Service/OrderServiceTest.php
tests/Service/SiteServiceTest.php

| Jira Ticket(s)      | HPRO-1596

[HPRO-1596] Create read only view for Inactive sites

---

src/Form/Nph/NphOrderType.php
src/Helper/NphParticipant.php
src/Nph/Order/Modules/Module1.php
templates/program/nph/order/generate-orders.html.twig
templates/program/nph/participant/index.html.twig
templates/program/nph/participant/partials/hair-nail-optin-badge.html.twig

| Jira Ticket(s)      | HPRO-1629

[HPRO-1629] Hair and nail consents.

---

src/Service/Nph/NphOrderService.php

| Jira Ticket(s)      | HPRO-1631

[HPRO-1631] Change aliquot volume to include glycerolAdditiveVolume

---

src/Entity/NphSample.php
src/Service/Nph/NphOrderService.php

| Jira Ticket(s)      | HPRO-1631

[HPRO-1631] Don't change actual collection amount, just what's sent to RDR

---

src/Controller/DeceasedReportsController.php
src/Controller/ParticipantDetailsController.php
templates/partials/modals/site-select-bs5.html.twig
templates/partials/modals/site-select.html.twig
templates/partials/participant-id-verification.html.twig
templates/partials/participant-incentive.html.twig
templates/partials/participant-patient-status.html.twig
templates/participant/details.html.twig
templates/program/hpo/navbar-bs5.html.twig
templates/program/hpo/navbar.html.twig
templates/site-select.html.twig

| Jira Ticket(s)      | HPRO-1596

[HPRO-1596] Inactive sites on site details changes

---

templates/macros/display-text.html.twig
templates/partials/modals/site-select-bs5.html.twig
templates/partials/modals/site-select.html.twig
templates/partials/participant-id-verification.html.twig
templates/partials/participant-incentive.html.twig
templates/partials/participant-measurement-list-bs5.html.twig
templates/partials/participant-notice-bs5.html.twig
templates/partials/participant-orders-list-bs5.html.twig
templates/partials/participant-patient-status.html.twig
templates/participant/details.html.twig
templates/program/hpo/navbar-bs5.html.twig
templates/program/hpo/navbar.html.twig
templates/site-select.html.twig

| Jira Ticket(s)      | HPRO-1573

[HPRO-1573] Bootstrap5 changes and fixes

---

templates/participant/details.html.twig

| Jira Ticket(s)      | HPRO-1573

[HPRO-1573] Fix deceased reports button size

---

web/assets/js/views/NphOrderCreate.js

| Jira Ticket(s)      | HPRO-1629

[HPRO-1629] Fix check all issue when fields are disabled

---

migrations/Version20230906173509.php
src/Controller/NphOrderController.php
src/Entity/NphDlw.php
src/Service/Nph/NphOrderService.php
templates/program/nph/order/collect.html.twig
templates/program/nph/order/dlw-collect.html.twig
templates/program/nph/order/sample-finalize.html.twig
tests/Service/NphOrderServiceTest.php
tests/testSetup.php
web/assets/js/views/NphSampleFinalize.js

[HPRO-1610] Fix for checkboxes, save dlw finalization user.

---

src/Controller/NphOrderController.php

[HPRO-1610] Removed flash, fixed showing finalized by unknown.

---

templates/program/nph/order/sample-finalize.html.twig

[HPRO-1610] Remove second units for glyercol.

---

src/Entity/NphOrder.php
src/Form/DlwType.php
src/Nph/Order/Samples/Module3.json
templates/program/nph/order/dlw-collect.html.twig
templates/program/nph/order/sample-finalize.html.twig

[HPRO-1610] Color button, Form warning fix, Tube volumes.

---

templates/program/nph/order/dlw-collect.html.twig
templates/program/nph/order/sample-finalize.html.twig
web/assets/css/nph.css

[HPRO-1610] Fixed eraser alignment on sample finalize, added error class.

---

src/Helper/Participant.php

| Jira Ticket(s)      | HPRO-1604

[HPRO-1604] Set default pediatric indicator to false

---

src/Form/Nph/NphSampleFinalizeType.php
src/Nph/Order/Samples/Module3.json
templates/program/nph/order/sample-finalize.html.twig
web/assets/js/views/NphSampleFinalize.js

[HPRO-1652] Fix for missing eraser, constraint fixes, only check aliquots that are set.

---

web/assets/js/views/NphSampleFinalize.js

[HPRO-1652] Remove restore/remove checkboxes on add lines.

---

src/Form/Nph/NphSampleFinalizeType.php

[HPRO-1652] Error message change.

---

src/Service/Nph/NphOrderService.php

| Target Release?     |Next available 

[HPRO-1652] Fix for DLWInfo being null.

---

web/assets/js/views/NphSampleFinalize.js

[HPRO-1652] If salivaa2 aliquot clear previous row inputs.

---

src/Entity/NphSample.php

| Jira Ticket(s)      | HPRO-1674

[HPRO-1674] Handle single glycerol samples.

---

migrations/Version20230913201039.php
src/Controller/MeasurementsController.php
src/Entity/BloodPressureDiastolicHeightPercentile.php
src/Entity/BloodPressureSystolicHeightPercentile.php
src/Entity/HeartRateAge.php
src/Entity/Measurement.php
src/Helper/Participant.php
src/Model/Measurement/versions/0.3.3-peds-1.json
src/Model/Measurement/versions/0.3.3-peds-2.json
src/Model/Measurement/versions/0.3.3-peds-3.json
src/Model/Measurement/versions/0.3.3-peds-4.json
src/Repository/BloodPressureDiastolicHeightPercentileRepository.php
src/Repository/BloodPressureSystolicHeightPercentileRepository.php
src/Repository/HeartRateAgeRepository.php
templates/measurement/index.html.twig
templates/measurementform/0.3-peds.html.twig
web/assets/js/views/Measurements.js
web/assets/js/views/PhysicalEvaluation-0.3-peds.js

| Jira Ticket(s)      | HPRO-1650

[HPRO-1650] Implement Pediatrics Physical Measurements Warnings and Alerts

---

migrations/Version20231010192753.php
src/Controller/DebugToolsController.php
src/Controller/MeasurementsController.php
src/Entity/Measurement.php
src/Form/PediatricMeasurementType.php
src/Model/Measurement/Fhir.php
src/Model/Measurement/versions/0.3.3-peds-1.json
src/Model/Measurement/versions/0.3.3-peds-2.json
src/Model/Measurement/versions/0.3.3-peds-3.json
src/Service/MeasurementQueueService.php
src/Service/MeasurementService.php
templates/measurement/index.html.twig
tests/Entity/MeasurementTest.php

| Jira Ticket(s)      | HPRO-1634

[HPRO-1634] Save pediatrics PM form and send FHIR payloads to RDR

---

migrations/Version20231009143011.php
src/Entity/IdVerification.php
src/Form/IdVerificationType.php
src/Repository/IdVerificationRepository.php
src/Service/IdVerificationService.php
src/Service/OnSiteDetailsReportingService.php
templates/participant/details.html.twig
tests/Service/OnSiteDetailsReportingServiceTest.php
web/assets/js/views/IdVerification.js
web/assets/js/views/OnSiteIdVerification.js

| Jira Ticket(s)      | HPRO-1635

[HPRO-1635] Pediactric ID Verification

---

src/Entity/Measurement.php
src/Model/Measurement/Fhir.php
src/Model/Measurement/versions/0.3.3-peds-1.json
src/Model/Measurement/versions/0.3.3-peds-2.json
src/Model/Measurement/versions/0.3.3-peds-weight.json
templates/measurement/modify.html.twig
templates/measurementform/0.3-peds.html.twig
templates/partials/participant-dl-bs5.html.twig
templates/partials/participant-dl.html.twig
templates/partials/participant-measurement-summary.html.twig
web/assets/js/views/PhysicalEvaluation-0.3-peds.js

| Jira Ticket(s)      | HPRO-1651

[HPRO-1651] Pediatrics PM Hard stop Validations

---

src/Controller/OrderController.php
src/Entity/Order.php
templates/order/create.html.twig
templates/order/header.html.twig

| Jira Ticket(s)      | HPRO-1655

[HPRO-1655] Remove Process Tab.

---

src/Entity/Measurement.php
src/Helper/Participant.php
templates/partials/participant-measurement-list-bs5.html.twig
templates/partials/participant-measurement-list.html.twig

| Target Release?     | 4.0.0
| Jira Ticket(s)      | HPRO-1637

[HPRO-1637] Remove gRoR consent check for PM&B blocking logic and add pediatric indicator

---

src/Entity/Measurement.php
src/Model/Measurement/Fhir.php
templates/measurementform/0.3-peds.html.twig

[HPRO-1684] Pediatrics measurements bug fixes - 1

---

src/Entity/Order.php

| Jira Ticket(s)      | HPRO-1683

[HPRO-1683] Remove processing step for pediatric orders.

---

src/Model/Measurement/versions/0.3.3-peds-1.json
src/Model/Measurement/versions/0.3.3-peds-2.json
src/Model/Measurement/versions/0.3.3-peds-3.json
src/Model/Measurement/versions/0.3.3-peds-4.json
src/Model/Measurement/versions/0.3.3-peds-weight.json
templates/measurementform/0.3-peds.html.twig
web/assets/js/views/PhysicalEvaluation-0.3-peds.js

[HPRO-1684] Pediatrics measurements fix wheelchair and other modification issues

---

src/Entity/Order.php

| Jira Ticket(s)      | HPRO-1686

[HPRO-1686] Added 2ED04 sample identifier

---

src/Model/Measurement/versions/0.3.3-peds-2.json
src/Model/Measurement/versions/0.3.3-peds-3.json
src/Model/Measurement/versions/0.3.3-peds-4.json
templates/measurementform/0.3-peds.html.twig
templates/measurementform/metrics.html.twig
web/assets/js/views/PhysicalEvaluation-0.3-peds.js

This PR fixes 1-10 bugs listed in this ticket https://precisionmedicineinitiative.atlassian.net/browse/HPRO-1684

[HPRO-1684] Pediatrics measurements bug fixes 3

---

src/Model/Measurement/versions/0.3.3-peds-1.json
src/Model/Measurement/versions/0.3.3-peds-2.json
src/Model/Measurement/versions/0.3.3-peds-3.json
src/Model/Measurement/versions/0.3.3-peds-4.json
web/assets/js/views/PhysicalEvaluation-0.3-peds.js

[HPRO-1684] Pediatrics measurements bug fixes 4

---

src/Model/Measurement/Fhir.php
src/Model/Measurement/versions/0.3.3-peds-3.json
src/Model/Measurement/versions/0.3.3-peds-4.json
web/assets/js/views/PhysicalEvaluation-0.3-peds.js

[HPRO-1684] Pediatrics Measurements Bug Fixes - 5

---

src/Entity/Order.php
templates/order/finalize.html.twig
templates/order/pediatric/weight.html.twig
templates/order/samples.html.twig
templates/partials/participant-orders-list-bs5.html.twig

| Jira Ticket(s)      | HPRO-1683

[HPRO-1683] Fixes for Pediatric Bugs.

---

templates/review/modified_measurements.html.twig
templates/review/modified_orders.html.twig
templates/review/today.html.twig
templates/review/unfinalized_measurements.html.twig
templates/review/unfinalized_orders.html.twig

| Jira Ticket(s)      | HPRO-1608

[HPRO-1608] Add pediatric indicator in daily review pages

---

src/Helper/WorkQueue.php
tests/Service/WorkQueueServiceTest.php

| Jira Ticket(s)      | HPRO-1689

[HPRO-1689] Peds display new samples in WQ and Participant Summary details page

---

web/assets/js/views/NphOrderCreate.js

| Jira Ticket(s)      | HPRO-1633

[HPRO-1633] Order generation duplication fix.

---

src/Helper/Participant.php
templates/partials/participant-dl-bs5.html.twig

| Jira Ticket(s)      | HPRO-1586

[HPRO-1586] Pediatrics account linkage - Display guardian details

---

src/Model/Measurement/versions/0.3.3-peds-weight.json
templates/measurementform/0.3-peds-weight.html.twig
templates/partials/participant-overview.html.twig
web/assets/js/views/PhysicalEvaluation-0.3-peds.js

[HPRO-1684] Fix weight only form warnings and emergency alerts

---

migrations/Version20231024135150.php
src/Controller/ParticipantDetailsController.php
src/Entity/Incentive.php
src/Form/IncentiveType.php
src/Repository/IncentiveRepository.php
src/Service/IncentiveService.php
templates/partials/participant-incentive.html.twig
tests/Repository/IncentiveRepositoryTest.php
tests/Service/IncentiveServiceTest.php
web/assets/js/views/Incentive.js
web/assets/js/views/Participant.js

| Jira Ticket(s)      | HPRO-1636

[HPRO-1636] Added new item of appreciation incentive.

---

src/Helper/WorkQueue.php
tests/Service/WorkQueueServiceTest.php

| Jira Ticket(s)      | HPRO-1588

[HPRO-1588] Add environmental exposures field in WQ and participant details page

---

src/Controller/ReviewController.php
templates/review/modified_measurements.html.twig
templates/review/modified_orders.html.twig
templates/review/today.html.twig
templates/review/unfinalized_measurements.html.twig
templates/review/unfinalized_orders.html.twig
web/assets/js/views/review.js

| Jira Ticket(s)      | HPRO-1608

[HPRO-1608] Fix daily review pedaitric indicator

---

src/Controller/OrderController.php
src/Repository/MeasurementRepository.php
templates/order/check-pediatric.html.twig
templates/order/modify.html.twig
templates/order/pediatric/blood-draw-modal.html.twig
templates/partials/participant-orders-list-bs5.html.twig
web/assets/css/app.css
web/assets/css/nph.css

| Jira Ticket(s)      | HPRO-1683

Fixed null weight measurements, safety-check questions

---

src/Order/versions/3.1-ped-16.4.json
src/Order/versions/3.1-ped-2.5.json
src/Order/versions/3.1-ped-5.json
src/Order/versions/3.1-ped-9999.json
templates/order/check-pediatric.html.twig
templates/partials/participant-orders-list-bs5.html.twig
web/assets/css/hpo.css
web/assets/js/views/IdVerification.js

| Jira Ticket(s)      | HPRO-1696

[HPRO-1696] Order generation bugs, typo fixes, Readd second urine label, remove visit type option, Move pediatric indicator.

---

src/Model/Measurement/versions/0.3.3-peds-weight.json

[HPRO-1684] Fix weight only form protocol modification text

---

src/Model/Measurement/versions/0.3.3-peds-1.json
src/Model/Measurement/versions/0.3.3-peds-2.json
src/Model/Measurement/versions/0.3.3-peds-3.json
src/Model/Measurement/versions/0.3.3-peds-4.json

[HPRO-1684] Fix typo in HR method

---

templates/measurementform/0.3-peds.html.twig
web/assets/js/views/PhysicalEvaluation-0.3-peds.js

| Jira Ticket(s)      | HPRO-1700

[HPRO-1700] Peds PM bug fixes

---

src/Model/Measurement/versions/0.3.3-peds-1.json
src/Model/Measurement/versions/0.3.3-peds-2.json
src/Model/Measurement/versions/0.3.3-peds-3.json
src/Model/Measurement/versions/0.3.3-peds-4.json
web/assets/js/views/PhysicalEvaluation-0.3-peds.js

[HPRO-1701] Peds PM Bug Fixes

---

templates/program/nph/admin/sites/index.html.twig

| Jira Ticket(s)      | HPRO-1708

[HPRO-1708] Fix NPH site admin script load issue

---

templates/program/nph/pdf/biospecimen-label.html.twig

| Target Release?     | 4.1 
| Jira Ticket(s)      | HPRO-1652 
Swaps position of timepoint and visit type on DLW labels.

Fix label layout for dlw doses.

---

src/Entity/Measurement.php
src/Model/Measurement/versions/0.3.3-peds-3.json
web/assets/js/views/PhysicalEvaluation-0.3-peds.js

[HPRO-1701] Fix peds PM blocker bugs

---

src/Entity/Measurement.php
src/Model/Measurement/Fhir.php
src/Repository/BmiForAge5YearsAndUpRepository.php
src/Repository/HeadCircumferenceForAge0To36MonthsRepository.php
src/Repository/HeightForAge0To23MonthsRepository.php
src/Repository/HeightForAge24MonthsTo6YearsRepository.php
src/Repository/WeightForAge0To23MonthsRepository.php
src/Repository/WeightForAge24MonthsAndUpRepository.php
src/Repository/WeightForLength0To23MonthsRepository.php
src/Repository/WeightForLength23MonthsTo5YearsRepository.php
src/Service/MeasurementService.php
templates/measurement/index.html.twig
templates/measurementform/0.3-peds-weight.html.twig
templates/measurementform/0.3-peds.html.twig
templates/measurementform/macros/growth-percentile.html.twig
web/assets/css/app.css
web/assets/js/views/Measurements.js
web/assets/js/views/PhysicalEvaluation-0.3-peds.js

| Jira Ticket(s)      | HPRO-1680

[HPRO-1680] Peds PM add growth percentiles for both male and female if setAtBirth is not defined

---

src/Form/IncentiveType.php
src/Service/IncentiveService.php
templates/partials/participant-incentive.html.twig
web/assets/js/views/Incentive.js

| Jira Ticket(s)      | HPRO-1703

[HPRO-1703] Added other recipient, and specify other to incentives.

---

web/assets/js/views/PhysicalEvaluation-0.3-peds.js

[HPRO-1701] Fix percentile warnings

---

src/Model/Measurement/versions/0.3.3-peds-3.json
src/Model/Measurement/versions/0.3.3-peds-4.json
web/assets/js/views/PhysicalEvaluation-0.3-peds.js

[HPRO-1701] Fix peds pm urgent emergent warnings

---

src/Entity/Measurement.php

[HPRO-1701] Fix backend percentiles

---

web/assets/js/views/PhysicalEvaluation-0.3-peds.js

[HPRO-1701] Fix percentile/zscore warning conditions

---

src/Controller/ParticipantDetailsController.php
src/Form/IncentiveType.php

| Jira Ticket(s)      | HPRO-1703

[HPRO-1703] Incentive Fixes.

---

web/assets/js/views/Incentive.js

| Jira Ticket(s)      | HPRO-1703

[HPRO-1703] Number of items Item type required.

---

web/assets/js/views/PhysicalEvaluation-0.3-peds.js

| Jira Ticket(s)      | HPRO-1681

[HPRO-1681] Implement alerts/warnings when setAtBirth is not set

---

templates/measurementform/0.3-peds-weight.html.twig
templates/measurementform/0.3-peds.html.twig
web/assets/js/views/PhysicalEvaluation-0.3-peds.js

| Jira Ticket(s)      | HPRO-1695

[HPRO-1695] - Display out of range percentile warnings

---

composer.lock

| Jira Ticket(s)      | HPRO-1729

[HPRO-1729] Run composer update

---

web/assets/js/views/NphDlw.js

| Target Release?     | 4.1 
| Jira Ticket(s)      | HPRO-1694

[HPRO-1694] Change dosage to 1 decimal place.

---

src/Controller/NphOrderController.php
src/Repository/NphOrderRepository.php
src/Service/Nph/NphOrderService.php
templates/program/nph/order/generate-orders.html.twig
templates/program/nph/order/samples.html.twig
web/assets/js/views/NphOrderCreate.js

| Jira Ticket(s)      | HPRO-1685

[HPRO-1685] Bug fixes, show multiple downtime generated orders.

---

src/Controller/NphOrderController.php
src/Form/Nph/NphOrderType.php
src/Service/Nph/NphOrderService.php
templates/program/nph/order/collect.html.twig
templates/program/nph/order/generate-orders.html.twig
templates/program/nph/order/partials/order-collect-urine24.html.twig
templates/program/nph/order/sample-finalize.html.twig
templates/program/nph/order/samples.html.twig
web/assets/js/views/NphOrderCreate.js

| Target Release?     | 4.1.0
| Jira Ticket(s)      | HPRO-1654, HPRO-1733,HPRO-1685

[HPRO-1654][HPRO-1733][HPRO-1685] 24 hour urine fixes, 500 error fix, downtime generation future fix.

---

templates/program/nph/biobank/participant.html.twig

…mary.
| Target Release?     | 4.1.0
| Jira Ticket(s)      | HPRO-1709

[HPRO-1709] Use participant module to determine module display on participant summary page

---

templates/program/nph/pdf/biospecimen-label.html.twig

[HPRO-1652] Reverse Spacing on DLW.

---

src/Form/Nph/NphOrderCollect.php
src/Form/Nph/NphOrderForm.php
src/Form/Nph/NphSampleFinalizeType.php
templates/program/nph/order/partials/order-collect-urine24.html.twig
templates/program/nph/order/sample-finalize.html.twig
web/assets/css/nph.css
web/assets/js/views/NphOrder.js

| Jira Ticket(s)      | HPRO-1654

[HPRO-1654] Add missing warning and validation messages.

---

web/assets/js/views/NphOrder.js
web/assets/js/views/NphOrderCreate.js

| Target Release?     |Next available 
| Jira Ticket(s)      | HPRO-1654

[HPRO-1654] Datepicker don't allow future, inclusive error range.

---

src/Form/Nph/NphOrderType.php

| Jira Ticket(s)      | HPRO-1742

[HPRO-1742] Disable autocomplete for order generation time.

---

web/assets/js/views/NphOrderCreate.js

| Jira Ticket(s)      | HPRO-1742

[HPRO-1742] Make sure dateselector initializes with no value it had before.

---

src/Form/IdVerificationType.php

| Jira Ticket(s)      | HPRO-1678

[HPRO-1678] Add new visit type - ID Verification Only

---

src/Service/HelpService.php

| Jira Ticket(s)      | HPRO-1692

[HPRO-1692] Added pediatric SOPs

---

config/packages/twig.php
src/Controller/HelpController.php
src/Service/HelpService.php
templates/help/nph/faq.html.twig
templates/help/nph/footer.html.twig
templates/help/nph/helptext.html.twig
templates/help/nph/index.html.twig
templates/help/nph/sop-pdf.html.twig
templates/program/nph/navbar-bs5.html.twig
templates/program/nph/navbar.html.twig

| Jira Ticket(s)      | HPRO-1597

[HPRO-1597] NPH add help training resources

---

src/Service/HelpService.php

| Target Release?     |4.2.0 
| Jira Ticket(s)      | HPRO-1698

[HPRO-1698] Add Pediatric SOPs

---

src/Controller/NphOrderLookupController.php
src/Form/Nph/NphAliquotLookupType.php
templates/program/nph/index.html.twig
templates/program/nph/navbar-bs5.html.twig
templates/program/nph/navbar.html.twig
templates/program/nph/order/orderlookup.html.twig

| Target Release?     | 4.2.0
| Jira Ticket(s)      | HPRO-1527

[HPRO-1527] NPH Biospecimen Lookup

---

templates/macros/display-text.html.twig
templates/partials/participant-overview.html.twig

| Jira Ticket(s)      | HPRO-1704

[HPRO-1704] Readd checkmark for GROR Consent.

---

migrations/Version20231208200109.php
src/Controller/CronController.php
src/Entity/IdVerificationRdr.php
src/Repository/IdVerificationRdrRepository.php
src/Service/IdVerificationService.php

| Jira Ticket(s)      | HPRO-1237

[HPRO-1237] ID verification backfill from RDR data

---

src/Service/Nph/NphParticipantSummaryService.php
templates/program/nph/biobank/participant.html.twig

| Target Release?     | 4.20 
| Jira Ticket(s)      | HPRO-1749

[HPRO-1749] Use modulenumber, add enrollmentstatus to query.

---

templates/program/nph/navbar-bs5.html.twig
templates/program/nph/navbar.html.twig

| Target Release?     | 4.2.0
| Jira Ticket(s)      | HPRO-1597

[HPRO-1597] Change NPH feedback link in navbar

---

src/Service/ParticipantSummaryService.php

| Jira Ticket(s)      | HPRO-1751

[HPRO-1751] Fix participant id lookup errors if participant id is not found

---

src/Entity/Measurement.php
web/assets/js/views/PhysicalEvaluation-0.3-peds.js

| Jira Ticket(s)      | HPRO-1753

[HPRO-1753] FIX pediatric -ve 0.0 decimal height percentile issue

---

templates/program/nph/order/macros/display-text.html.twig
templates/program/nph/participant/index.html.twig
web/assets/css/nph.css
web/assets/js/views/NphSampleFinalize.js

| Jira Ticket(s)      | HPRO-1614, HPRO-1576

[HPRO-1614][HPRO-1576] Display bug fixes on participant summary page and aliquot page.

---

templates/program/nph/order/macros/display-text.html.twig
templates/program/nph/participant/index.html.twig

| Jira Ticket(s)      | HPRO-1576

[HPRO-1576] Updated colors and tooltip classes

---

templates/program/nph/participant/index.html.twig

| Jira Ticket(s)      | HPRO-1576

Fix access warning for bootstrap 5

---

templates/program/nph/participant/index.html.twig

| Jira Ticket(s)      | HPRO-1576

[HPRO-1576] Changed warning banner color

---

templates/program/nph/participant/index.html.twig

| Jira Ticket(s)      | HPRO-1576

[HPRO-1576] Add outline to cancel button.

---

web/assets/js/views/PhysicalEvaluation-0.3-peds.js

| Target Release?     | 4.2.0
| Jira Ticket(s)      | HPRO-1753

[HPRO-1753] Fix pediatrics percentile calculations

---

web/assets/js/views/PhysicalEvaluation-0.3-peds.js

| Target Release?     | 4.2.2 
| Jira Ticket(s)      | HPRO-1756

[HPRO-1756] Fix age transition Heart Rate percentile warnings

---

src/Entity/Measurement.php

| Target Release?     | 4.2.2 
| Jira Ticket(s)      | HPRO-1756

[HPRO-1756] Fix blood pressure protocol modifications error message

---

templates/participantlookup/participants.html.twig
templates/program/nph/participantlookup/participants.html.twig
web/assets/css/bs5.css
web/assets/js/views/ParticipantLookup.js

| Jira Ticket(s)      | HPRO-1621

[HPRO-1621] Update AOU/NPH participant lookup to bootstrap5

---

src/Controller/PatientStatusController.php

| Jira Ticket(s)      | HPRO-1481

[HPRO-1481] Handle patient status upload errors

---

src/Controller/WorkQueueController.php
src/Helper/WorkQueue.php
src/Service/WorkQueueService.php
templates/partials/workqueue-advance-filters.html.twig
tests/Helper/WorkQueueTest.php

| Jira Ticket(s)      | HPRO-1599

[HPRO-1599] AOU WQ add PM&B filters

---

templates/measurement/modify.html.twig
templates/partials/participant-dl-bs5.html.twig
templates/partials/participant-dl.html.twig

| Jira Ticket(s)      | HPRO-1734

[HPRO-1734] Display sex in participant details list

---

web/assets/js/views/NphSampleFinalize.js

| Jira Ticket(s)      | HPRO-1639

[HPRO-1639] Prevent auto populate time when aliquot id is disabled

---

templates/featurenotification/index.html.twig

| Jira Ticket(s)      | HPRO-1198

[HPRO-1198] Feature notification fix database date sort issues

---

src/Entity/NphOrder.php
src/Nph/Order/Samples/Module2.json

| Jira Ticket(s)      | HPRO-1683

[HPRO-1683] Fix urine sample display name

---

src/Helper/Participant.php

| Target Release?     | 3.4.0
| Jira Ticket(s)      | HPRO-1569

[HPRO-1569] Update Cohort 3 EHR consent banner display logic

---

src/Form/DlwType.php

| Jira Ticket(s)      | HPRO-1784

[HPRO-1784] Hotfix for DLW Batch ID Change range constraint to length constraint to handle leading 0

---

src/Form/DlwType.php

| Target Release?     | 4.3.1
| Jira Ticket(s)      | HPRO-1784

[HPRO-1784] Hotfix for DLW Dose Batch ID.

---

src/Controller/NphOrderController.php
src/Form/Nph/NphOrderForm.php
src/Form/Nph/NphSampleFinalizeType.php
templates/program/nph/order/sample-finalize.html.twig
web/assets/js/views/NphSampleFinalize.js

| Jira Ticket(s)      | HPRO-1494

[HPRO-1494] NPH - Implement real time validations in Sample Finalize (Aliquot) page

---

templates/partials/participant-overview.html.twig

| Jira Ticket(s)      | HPRO-1773

[HPRO-1773] Fix CABoR consent display issue

---

migrations/Version20240112183055.php
src/Entity/NphOrder.php

| Jira Ticket(s)      | HPRO-1781

[HPRO -1781] NPH diet period database updates

---

src/Form/Nph/NphOrderForm.php

| Target Release?     | 4.3.2 
| Jira Ticket(s)      | HPRO-1494

[HPRO-1494] Fix data comparison time zone issue

---

templates/program/nph/participant/index.html.twig
web/assets/css/bs5.css

| Target Release?     | 4.3.3 
| Jira Ticket(s)      | HPRO-1779

[HPRO-1779] Display diet color badge

---

src/Service/Nph/NphOrderService.php
templates/program/nph/participant/index.html.twig

| Target Release?     | 4.3.3 
| Jira Ticket(s)      | HPRO-1780

[HPRO-1780] NPH diet period display warning for orders created using visit type

---

templates/program/nph/participant/index.html.twig

| Target Release?     | 4.3.3 
| Jira Ticket(s)      | HPRO-1779

[HPRO-1779] Display diet color badge tooltip

---

src/Form/Nph/NphSampleFinalizeType.php

| Target Release?     | 4.3.3 
| Jira Ticket(s)      | HPRO-1795

[HPRO-1795] Fix total volume field disable issue for unlocked samples

---

src/Service/PDFService.php
templates/program/nph/pdf/biospecimen-label.html.twig

| Jira Ticket(s)      | HPRO-1778

[HPRO-1778] Updated labels to handle new visits

---

templates/program/nph/pdf/biospecimen-label.html.twig

| Jira Ticket(s)      | HPRO-1778

[HPRO-1778] Dlw Fix for labels.

---

templates/program/nph/biobank/partials/orders-review-table.html.twig

| Target Release?     | 4.3.3
| Jira Ticket(s)      | HPRO-1767

[HPRO-1767] Fix biobank daily review page visit

---

src/Form/Nph/NphSampleFinalizeType.php
templates/program/nph/order/sample-finalize.html.twig
web/assets/js/views/NphSampleFinalize.js

| Target Release?     | 4.3.4 
| Jira Ticket(s)      | HPRO-1648

[HPRO-1648 ] NPH disable aliquot fields for cancelled aliquots

---

src/Controller/DeceasedReportsController.php
src/Form/DeceasedReportType.php

| Target Release?     | 4.3.4 
| Jira Ticket(s)      | HPRO-1563

[HPRO-1563] Deceased reports validate dates

---

templates/program/nph/biobank/partials/orders-review-table.html.twig

| Target Release?     | 4.3.4
| Jira Ticket(s)      | HPRO-1812

[HPRO-1812] Fix NPH biobank daily review date columns sort

---

templates/accessmanagement/remove-member.html.twig

| Target Release?     | 4.3.4 
| Jira Ticket(s)      | HPRO-1716

[HPRO-1716] Update option notes in user management remove user form

---

src/Controller/MeasurementsController.php
templates/measurement/index.html.twig

| Target Release?     | 4.3.4
| Jira Ticket(s)      | HPRO-1632

[HPRO-1632] Disable PM form for cancelled measurements

---

src/Helper/Participant.php
templates/partials/participant-consent.html.twig

| Jira Ticket(s)      | HPRO-1723

[HPRO-1723] Display participant status on summary page, change field calculation

---

src/Helper/WorkQueue.php
tests/Service/WorkQueueServiceTest.php

| Target Release?     | 4.3.4 
| Jira Ticket(s)      | HPRO-1647

[HPRO-1647] Added PM&B Eligible date to export.

---

src/Form/DeceasedReportType.php
templates/program/nph/order/partials/sample-finalize-banner-message.html.twig

| Target Release?     | 4.3.4
| Jira Ticket(s)      | HPRO-1563

[HPRO-1563] Fix biobank view finalized date issue and add date format placeholder to DOD field

---

src/Helper/WorkQueue.php
tests/Helper/WorkQueueTest.php
tests/Service/WorkQueueServiceTest.php

| Jira Ticket(s)      | HPRO-1830

[HPRO-1830] Added missing field fixed selected fields export.

---

src/Controller/NphOrderController.php
src/Form/DlwType.php
src/Form/Nph/NphOrderType.php
templates/program/nph/order/samples.html.twig
web/assets/css/app.css
web/assets/js/views/NphOrder.js
web/assets/js/views/NphOrderCreate.js

| Target Release?     | 4.3.5 
| Jira Ticket(s)      | HPRO-1785

[HPRO-1785] NPH implement real time validations in order collect/generate pages

---

templates/program/nph/index.html.twig

| Jira Ticket(s)      | HPRO-1532

[HPRO-1532] Remove tile Link for workqueue.

---

src/Controller/NphOrderController.php
src/Entity/NphOrder.php
src/Form/Nph/NphSampleModifyBulkType.php
src/Repository/NphSampleRepository.php
src/Service/Nph/NphOrderService.php
templates/program/nph/order/sample-modify-bulk.html.twig
templates/program/nph/participant/index.html.twig

| Target Release?     | 4.3.5 
| Jira Ticket(s)      | HPRO-1717

[HPRO-1717] Created Bulk Cancelling of samples.

---

src/Controller/NphOrderController.php
templates/program/nph/order/sample-modify-bulk.html.twig
web/assets/css/nph.css

| Jira Ticket(s)      | HPRO-1717

[HPRO-1717] Added sample label display and table height

---

web/assets/js/views/NphOrder.js

| Target Release?     | 4.3.5 
| Jira Ticket(s)      | HPRO-1785

[HPRO-1785] Fix NPH collection page text message color

---

src/Controller/NphParticipantSummaryController.php
src/Service/Nph/NphOrderService.php
templates/program/nph/participant/index.html.twig
tests/Service/NphProgramSummaryServiceTest.php

| Jira Ticket(s)      | HPRO-1717

[HPRO-1717] Changed button style disable button if no active orders.

---

src/Helper/WorkQueue.php
src/Service/WorkQueueService.php
templates/workqueue/index.html.twig
tests/Helper/WorkQueueTest.php
tests/Service/WorkQueueServiceTest.php
web/assets/js/views/workqueue.js

| Jira Ticket(s)      | HPRO-1762

[HPRO-1762] Add pediatric status and related participant fields in WQ

---

src/Entity/Incentive.php
templates/partials/participant-incentive.html.twig
tests/Entity/IncentiveTest.php

| Target Release?     | 2.3.6 
| Jira Ticket(s)      | HPRO-1814

[HPRO-1814] Show incentive recipient in history

---

src/Service/ReviewService.php
templates/review/today.html.twig

| Target Release?     | 2.3.6
| Jira Ticket(s)      | HPRO-1173

[HPRO-1173] Fix date filter issue for edited orders in todays participants page

---

src/Form/DlwType.php

| Jira Ticket(s)      | HPRO-1852

Change type back to text type to handle leading zeroes

---

templates/order/check-pediatric.html.twig
web/assets/css/app.css
web/assets/js/views/PediatricOrderSafetyChecks.js

| Jira Ticket(s)      | HPRO-1845

[HPRO-1845] Allow to bypass Pediatric order checks for urine only orders

---

src/Controller/ParticipantDetailsController.php
src/Entity/IdVerification.php
src/Form/IdVerificationType.php
templates/partials/participant-id-verification.html.twig
web/assets/js/views/IdVerification.js

| Jira Ticket(s)      | HPRO-1846

[HPRO-1846] Enhance Pediatrics IDV with Guardian Verification

---

templates/measurementform/0.3-peds.html.twig
web/assets/js/views/PhysicalEvaluation-0.3-peds.js

| Target Release?     | 4.3.6 
| Jira Ticket(s)      | HPRO-1815

[HPRO-1815] Change modification when checkbox changes, added heartrate checkbox

---

src/Entity/Incentive.php
templates/partials/participant-incentive.html.twig
tests/Entity/IncentiveTest.php

| Target Release?     | 4.3.6 
| Jira Ticket(s)      | HPRO-1814

[HPRO-1814] Display other recipient info if exists

---

src/Helper/WorkQueue.php

| Target Release?     | 4.3.6 
| Jira Ticket(s)      | HPRO-1789

[HPRO-1789] Added Retention Eligible N/A pediatric display

---

src/Controller/NphBiobankController.php
src/Form/ReviewTodayFilterType.php
src/Repository/NphOrderRepository.php
templates/program/nph/biobank/orders-downtime.html.twig
templates/program/nph/biobank/partials/orders-review-table.html.twig
templates/program/nph/biobank/partials/review-page-heading.html.twig
tests/Repository/NphOrderRepositoryTest.php
web/assets/js/views/NphBiobankReview.js

| Jira Ticket(s)      | HPRO-1827

[HPRO-1827] NPH - Create downtime audit details page for biobank view

---

src/Controller/NphOrderController.php
web/assets/js/views/NphSampleFinalize.js

| Target Release?     | 4.3.7 
| Jira Ticket(s)      | HPRO-1584

[HPRO-1584] NPH aliquot field warning

---

src/Service/HelpService.php

| Target Release?     | 4.3.7 
| Jira Ticket(s)      | HPRO-1808

[HPRO-1808] Update release notes link

---

migrations/Version20240315182440.php
src/Controller/ParticipantDetailsController.php
src/Entity/Incentive.php
src/Form/IncentiveType.php
src/Repository/IncentiveRepository.php
src/Service/IncentiveService.php

| Target Release?     | 4.3.7 
| Jira Ticket(s)      | HPRO-1847

[HPRO-1847] Added linking of incentives given to pediatric guardians.

---

src/Model/Measurement/versions/0.3.3-peds-1.json
src/Model/Measurement/versions/0.3.3-peds-2.json
src/Model/Measurement/versions/0.3.3-peds-3.json
src/Model/Measurement/versions/0.3.3-peds-4.json
templates/measurementform/metrics.html.twig
web/assets/js/views/PhysicalEvaluation-0.3-blood-donor.js
web/assets/js/views/PhysicalEvaluation-0.3-ehr.js
web/assets/js/views/PhysicalEvaluation-0.3-peds.js
web/assets/js/views/PhysicalEvaluation-0.3.js

| Jira Ticket(s)      | HPRO-1630

[HPRO-1630] Fix for conversions not displaying when alternative isn't filled.

---

src/Controller/ParticipantDetailsController.php
src/Repository/IncentiveRepository.php
templates/partials/participant-incentive.html.twig

…creation
| Jira Ticket(s)      | HPRO-1847

[HPRO-1847] Display Guardian ID, Disable Edit/Delete on Related, Sort results by Creation

---

src/Controller/ParticipantDetailsController.php

| Jira Ticket(s)      | HPRO-1847

[HPRO-1847] Set incentive recipient to the related participant if guardian recipient

---

templates/partials/participant-incentive.html.twig

| Jira Ticket(s)      | HPRO-1847

[HPRO-1847] Remove string blank

---

src/Controller/ParticipantDetailsController.php
templates/workqueue/partials/consent-modal.html.twig

| Target Release?     | 4.3.7.1 
| Jira Ticket(s)      | HPRO-1884

[HPRO-1884] Fix typo in EHR reconsent field

---

templates/program/nph/order/partials/participant-details-bs5.html.twig
templates/program/nph/order/partials/participant-details.html.twig
templates/program/nph/participant/index.html.twig

| Jira Ticket(s)      | HPRO-1758

[HPRO-1758] Order Collection UI Fix

---

templates/program/nph/participant/index.html.twig

| Target Release?     |  4.3.8 
| Jira Ticket(s)      | HPRO-1821

[HPRO-1821] Hide diet color warning for module 1 samples

---

src/Order/versions/3.2.json

| Target Release?     | 4.3.8
| Jira Ticket(s)      | HPRO-1857

[HPRO-1857] Change question codes for new PST tubes

---

src/Helper/WorkQueue.php
tests/Helper/WorkQueueTest.php
tests/Service/WorkQueueServiceTest.php
web/assets/js/views/workqueue.js

Reverts all-of-us/healthpro#1770

Revert "[HPRO-1859] Add new PST samples to WQ and Participant Summary Pages"

---

src/Service/WorkQueueService.php
web/assets/js/views/workqueue.js

| Target Release?     | 4.3.8 
| Jira Ticket(s)      | HPRO-1813

[HPRO-1813] Fix program update filter in WQ

---

src/Controller/OrderController.php
src/Form/OrderType.php

[HPRO-1860] Only remove notes on tube select orders.

---

src/Service/OrderService.php
templates/order/modify.html.twig

| Target Release?     | 4.3.8
| Jira Ticket(s)      | HPRO-1857

[HPRO-1857] Display converted samples in order unlock/cancel pages

---

templates/program/nph/biobank/participant.html.twig
templates/program/nph/order/partials/participant-details-bs5.html.twig
templates/program/nph/participant/index.html.twig
web/assets/css/app.css

| Jira Ticket(s)      | HPRO-1719

[HPRO-1719] Fix biobankt view, merge conflict error, color text blue.

---

src/Model/Measurement/versions/0.3.3-blood-donor.json
web/assets/js/views/PhysicalEvaluation-0.3-blood-donor.js

| Target Release?     | 4.3.8
| Jira Ticket(s)      | HPRO-1849

[HPRO-1849] Fix blood donor PM form manual enter alt units field issues

---

src/Controller/OrderController.php

[HPRO-1860] Cast to float before comparison.

---

migrations/Version20240416023515.php
src/Entity/OrderHistory.php
src/Repository/OrderHistoryRepository.php
src/Service/OrderService.php
templates/order/collect.html.twig
templates/partials/participant-orders-list-bs5.html.twig
tests/Service/OrderServiceTest.php
web/assets/js/views/OrderCollect.js

[HPRO-1860] Added code to convert between order versions

---

web/assets/js/app-bs5.js
web/assets/js/bootstrap-session-timeout-bs5.js

| Target Release?     | 4.3.9 
| Jira Ticket(s)      | HPRO-1893

[HPRO-1893] Fix session timeout modal in bootstrap5 pages

---

src/Controller/OrderController.php
src/Form/OrderType.php
src/Service/OrderService.php
tests/Service/OrderServiceTest.php

[HPRO-1860] Set collect time when updating tubes, disable order version when appropriate.

---

src/Helper/WorkQueue.php
tests/Helper/WorkQueueTest.php
tests/Service/WorkQueueServiceTest.php

| Jira Ticket(s)      | HPRO-1856

[HPRO-1856] Add Pediatrics 2SAL0 sample to WQ and Participant Summary Page

---

src/Controller/OrderController.php

[HPRO-1860] Check that form has orderVersion before accessing it.

---

templates/partials/drc-support-text.html.twig

| Jira Ticket(s)      | HPRO-1858

[HPRO-1858] Updated support message

---

src/Helper/WorkQueue.php
src/Service/WorkQueueService.php
tests/Helper/WorkQueueTest.php

| Target Release?     | 4.3.10 
| Bug fix?            |/❌ 
| Jira Ticket(s)      | HPRO-1843

[HPRO-1843] Implement filtering for pediatric status field in WQ

---

src/Service/Nph/NphProgramSummaryService.php
templates/program/nph/participant/index.html.twig

| Jira Ticket(s)      | HPRO-1644

[HPRO-1644] Disable DLW button until DLW order generated.

---

templates/program/nph/participant/index.html.twig
web/assets/css/nph.css

| Target Release?     | 4.3.11 
| Jira Ticket(s)      | HPRO-1887

[HPRO-1887] NPH diet period UI changes

---

migrations/Version20240516141832.php
src/Controller/BiobankController.php
src/Controller/NphBiobankController.php
src/Controller/NphParticipantSummaryController.php
src/Entity/NphGenerateOrderWarningLog.php
src/Entity/NphSampleProcessingStatus.php
src/Repository/NphGenerateOrderWarningLogRepository.php
src/Repository/NphSampleProcessingStatusRepository.php
src/Service/Nph/NphOrderService.php
templates/program/nph/biobank/audit.html.twig
templates/program/nph/biobank/partials/review-page-heading.html.twig
templates/program/nph/participant/index.html.twig

| Jira Ticket(s)      | HPRO-1885

[HPRO-1885] Add biobank audit tab for Diet Period errors.

---

templates/program/nph/participant/index.html.twig
web/assets/css/nph.css

| Target Release?     | 4.3.11
| Jira Ticket(s)      | HPRO-1887

[HPRO-1887] Fix sample processing box width issue

---

src/Controller/NphParticipantSummaryController.php
src/Service/Nph/NphOrderService.php
templates/program/nph/participant/index.html.twig
tests/Service/NphOrderServiceTest.php
web/assets/css/app.css
web/assets/css/nph.css
web/assets/js/views/NphParticipantSummary.js

[HPRO-1911] NPH diet period fixes

---

templates/program/nph/biobank/audit.html.twig

[HPRO-1855] Text Fixes for audit tab.

---

src/Controller/CronController.php
src/Repository/IncentiveRepository.php
src/Repository/MeasurementRepository.php
src/Service/PediatricsReportService.php

| Target Release?     | 4.3.11 
| Jira Ticket(s)      | HPRO-1883,HPRO-1838,HPRO-1882,HPRO-1880

[HPRO-1883][HPRO-1838][HPRO-1882][HPRO-1880] Pediatric Quarterly Reports

---

src/Entity/NphSample.php
src/Form/Nph/NphOrderCollect.php
src/Form/Nph/NphOrderForm.php
src/Form/Nph/NphSampleFinalizeType.php
src/Service/Nph/NphOrderService.php
templates/program/nph/order/sample-finalize.html.twig
tests/Service/NphOrderServiceTest.php
web/assets/js/views/NphSampleFinalize.js

| Jira Ticket(s)      | HPRO-1915

[HPRO-1915] Add NPH freeze time for stool sample

---

config/packages/security.yaml
src/Controller/DefaultController.php
src/Service/SiteService.php
templates/base.html.twig
templates/program/hpo/navbar-bs5.html.twig
templates/program/hpo/navbar.html.twig
templates/program/nph/index.html.twig

| Jira Ticket(s)      | HPRO-1892

[HPRO-1892] Fix cross program roles site select

---

src/EventListener/ResponseSecurityHeadersTrait.php
src/Security/SalesforceAuthenticator.php
src/Service/SalesforceAuthService.php

| Jira Ticket(s)      | HPRO-1933

[HPRO-1933] Change SSO configuration to dev

---

src/Controller/NphOrderController.php
src/Entity/NphOrder.php
src/Form/Nph/NphOrderCollect.php
src/Form/Nph/NphOrderForm.php
src/Form/Nph/NphSampleFinalizeType.php
templates/program/nph/order/sample-finalize.html.twig

| Jira Ticket(s)      | HPRO-1916

[HPRO-1916] Disable freeze time field for old orders

---

src/Controller/NphParticipantSummaryController.php
src/Service/Nph/NphOrderService.php
templates/program/nph/participant/index.html.twig
tests/Service/NphOrderServiceTest.php
web/assets/js/views/NphParticipantSummary.js

[HPRO-1911] NPH diet period fixes 3

---

src/Service/PediatricsReportService.php

| Target Release?     | 4.3.11.2 
| Jira Ticket(s)      | HPRO-1942

[HPRO-1942] Added extra checks for array keys in pediatric reports.

---

src/Helper/NphDietPeriodStatus.php
src/Service/Nph/NphOrderService.php
templates/program/nph/participant/index.html.twig
web/assets/js/views/NphParticipantSummary.js

| Target Release?     | 4.3.12

[HPRO-1911] Fix NPH diet period issues 5

---

templates/program/nph/biobank/audit.html.twig

| Jira Ticket(s)      | HPRO-1885

[HPRO-1885] Audit tab Fixes according to feedback

---

src/Repository/NphSampleProcessingStatusRepository.php

| Target Release?     | 4.3.12 
| Bug fix?            | ✅  
| New feature?        |  ❌
| Jira Ticket(s)      | HPRO-1912

[HPRO-1911] Fix disable aliquot form issue

---

src/Form/Nph/NphOrderForm.php

| Target Release?     | 4.3.12

[HPRO-1911] Change freeze time required error message text

---

config/packages/security.yaml
src/Controller/AuthController.php
src/Controller/DefaultController.php
src/Controller/HpoPpscController.php
src/Helper/PpscParticipant.php
src/Security/SalesforceAuthenticator.php
src/Security/UserProvider.php
src/Service/Ppsc/PpscApiService.php
src/Service/SalesforceAuthService.php
templates/login.html.twig
templates/program/hpo/ppsc/base.html.twig
templates/program/hpo/ppsc/in-person-enrollment.html.twig
templates/program/hpo/ppsc/navbar.html.twig
templates/program/hpo/ppsc/partials/participant-measurement-list.html.twig
templates/program/hpo/ppsc/partials/participant-orders-list.html.twig
tests/Service/PpscApiServiceTest.php

| Jira Ticket(s)      | HPRO-.1912

[HPRO-1912] Integrate PPSC request api

---

templates/program/nph/biobank/audit.html.twig

| Jira Ticket(s)      | HPRO-1885

[HPRO-1885] Fix link for reset button

---

src/Form/Nph/NphOrderForm.php
src/Form/Nph/NphSampleFinalizeType.php

| Jira Ticket(s)      | HPRO-1917

[HPRO-1917] Remove 5 minute buffer for timestamps

---

templates/program/nph/biobank/audit.html.twig

| Jira Ticket(s)      | HPRO-1885

[HPRO-1885] Fix Typo and Sorting

---

src/Entity/NphOrder.php
web/assets/js/views/NphParticipantSummary.js

| Target Release?     | 4.3.12 
| Jira Ticket(s)      | HPRO-1915

[HPRO-1915] Fix NPH freeze time issue

---

src/Service/Nph/NphOrderService.php

| Target Release?     | 4.3.12 

[HPRO-1911] Check if participant module is greater than 1

---

src/Controller/NphBiobankController.php

| Target Release?     | 4.3.13
| Jira Ticket(s)      | HPRO-1958

[HPRO-1958] Pass missing fields to NPH sample finalize form in biobank view

---

src/Controller/OrderController.php
src/Form/OrderType.php
src/Service/OrderService.php

| Jira Ticket(s)      | HPRO-1932

[HPRO-1932] DV Site Config Option for enabling PST Tubes

---

web/assets/js/views/FinalizeOrder.js

| Jira Ticket(s)      | HPRO-1932

[HPRO-1932] Added javascript function to check checkAllBox

---

src/Controller/DefaultController.php
src/Controller/HpoPpscController.php
src/Controller/MeasurementsController.php
src/Controller/OrderController.php
src/Controller/ParticipantDetailsController.php
src/Drc/GoogleUser.php
src/Drc/SalesforceUser.php
src/Entity/Order.php
src/Helper/PpscParticipant.php
src/Service/OrderService.php
src/Service/SalesforceAuthService.php
src/Service/UserService.php
templates/measurement/index.html.twig
templates/measurement/modify.html.twig
templates/order/check-pediatric.html.twig
templates/order/check.html.twig
templates/order/collect.html.twig
templates/order/create.html.twig
templates/order/finalize.html.twig
templates/order/modify.html.twig
templates/order/print-labels.html.twig
templates/order/print-requisition.html.twig
templates/order/process.html.twig
templates/partials/participant-dl.html.twig
templates/partials/participant-measurement-list-bs5.html.twig
templates/partials/participant-measurement-list.html.twig
templates/program/hpo/ppsc/base.html.twig
templates/program/hpo/ppsc/navbar-bs5.html.twig
templates/program/hpo/ppsc/navbar.html.twig

| Jira Ticket(s)      | HPRO-1955

[HPRO-1955] Use PPSC participant API in the PM & Order forms

---

src/Helper/WorkQueue.php
src/Service/WorkQueueService.php
templates/workqueue/index.html.twig
tests/Helper/WorkQueueTest.php
tests/Service/WorkQueueServiceTest.php

| Jira Ticket(s)      | HPRO-1931

[HPRO-1931] Add hasCoreData to Workqueue

---

src/Helper/WorkQueue.php

| Jira Ticket(s)      | HPRO-1904

[HPRO-1904] Make pediatric status field sortable

---

src/Controller/DefaultController.php
src/Controller/ReviewController.php
src/Service/ReviewService.php
templates/review/modified_measurements.html.twig
templates/review/modified_orders.html.twig
templates/review/today.html.twig
templates/review/unfinalized_measurements.html.twig
templates/review/unfinalized_orders.html.twig
web/assets/js/views/today.js

| Jira Ticket(s)      | HPRO-1957

[HPRO-1957]  PPSC daily review integration

---

src/Helper/WorkQueue.php
tests/Helper/WorkQueueTest.php
tests/Service/WorkQueueServiceTest.php

| Target Release?     | 4.3.14 
| Jira Ticket(s)      | HPRO-1859

[HPRO-1859] Add new PST samples to WQ and Participant Summary Pages

---

src/Helper/WorkQueue.php
tests/Helper/WorkQueueTest.php
tests/Service/WorkQueueServiceTest.php
web/assets/js/views/workqueue.js

| Target Release?     | 4.3.14 
| Jira Ticket(s)      | HPRO-1856

[HPRO-1856] Add peds saliva field to WQ and Participant Summary Page

---

templates/workqueue/index.html.twig
web/assets/css/app.css

| Target Release?     | 4.3.14 
| Jira Ticket(s)      | HPRO-1856

[HPRO-1856] Fix WQ UI issues

---

web/assets/js/views/OrderCollect.js

Fix for both saliva tubes displaying

---

src/Controller/OrderController.php
src/Form/OrderType.php
templates/order/collect.html.twig
web/assets/css/app.css
web/assets/js/views/OrderCollect.js

[HPRO-1855] Show only collected samples for finalization.

---

src/Controller/DebugToolsController.php
src/Controller/MeasurementsController.php
src/Service/MeasurementQueueService.php
src/Service/MeasurementService.php
src/Service/Ppsc/PpscApiService.php
tests/Service/MeasurementServiceTest.php
tests/Service/PpscApiServiceTest.php

| Jira Ticket(s)      | HPRO-1961

[HPRO-1961] PPSC PM API integration

---

src/Entity/Order.php
src/Form/OrderType.php

| Target Release?     | 4.3.14 

[HPRO-1855] Change collected samples labels, disable field when appropriate.

---

templates/order/collect.html.twig

[HPRO-1855] Fix for mislabled tubes in help modal

---

src/Controller/CronController.php

| Jira Ticket(s)      | HPRO-1956

[HPRO-1956] Split pediatrics cron into 4 different calls.

---

src/Form/OrderType.php
templates/order/collect.html.twig
templates/order/modify.html.twig

[HPRO-1855] Only show collected sample for pediatric orders in order editing

---

src/Form/OrderType.php

[HPRO-1855] Fix for 500 error, throw error if atleast one sample is not selected.

---

src/Form/OrderType.php
web/assets/js/views/OrderCollect.js

[HPRO-1855] Remove errors when form elementsa are changed.

---

web/assets/js/views/OrderCollect.js

[HPRO-1855] Hide tube selection when dropdown is set to default value

---

src/Controller/NphBiobankController.php
src/Controller/NphOrderController.php
src/Entity/NphOrder.php

| Target Release?     | 4.3.14.1 
| Jira Ticket(s)      | HPRO-1964

[HPRO-1964] Change freeze time disable logic

---

src/Controller/NphBiobankController.php
src/Controller/NphOrderController.php
src/Entity/NphOrder.php
src/Entity/NphSample.php
src/Form/Nph/NphOrderCollect.php
src/Form/Nph/NphOrderForm.php
src/Form/Nph/NphOrderType.php
src/Form/Nph/NphSampleFinalizeType.php
src/Nph/Order/Samples/Module3.json
src/Nph/Order/Visits/Visit3DSMT.php
src/Service/Nph/NphOrderService.php
src/Service/PDFService.php
templates/program/nph/biobank/order-collect-details.html.twig
templates/program/nph/order/collect.html.twig
templates/program/nph/order/generate-orders.html.twig
templates/program/nph/order/partials/modals/optional-stool-kit-warning-modal.html.twig
templates/program/nph/order/partials/order-participant-details-barcode.html.twig
templates/program/nph/order/partials/participant-details.html.twig
templates/program/nph/order/sample-finalize.html.twig
templates/program/nph/order/sample-modify.html.twig
templates/program/nph/order/samples.html.twig
tests/Service/data/order_module_3.json
web/assets/js/views/NphOrderCreate.js

| Target Release?     | 4.3.15 
| Jira Ticket(s)      | HPRO-1905

[HPRO-1905] NPH module 3 add additional stool kit

---

src/Form/Nph/NphSampleFinalizeType.php
web/assets/js/views/NphSampleFinalize.js

| Target Release?     | 4.3.14.2 
| Jira Ticket(s)      | HPRO-1973

[HPRO-1973] Update aliquot edits time validations

---

web/assets/js/views/PhysicalEvaluation-0.3-peds.js

| Target Release?     | 4.3.14.3 
| Jira Ticket(s)      | HPRO-1905

[HPRO-1974] Fix peds auto apply protocol modifications

---

src/Controller/DefaultController.php
src/Controller/HpoPpscController.php
src/Controller/OrderController.php
src/Helper/PpscParticipant.php
src/Security/UserProvider.php
src/Service/Ppsc/PpscApiService.php
templates/measurement/index.html.twig
templates/order/check-pediatric.html.twig
templates/order/check.html.twig
templates/order/collect.html.twig
templates/order/create.html.twig
templates/order/finalize.html.twig
templates/order/header.html.twig
templates/order/modify.html.twig
templates/order/print-labels.html.twig
templates/order/print-requisition.html.twig
templates/order/process.html.twig
templates/partials/participant-orders-list-bs5.html.twig
templates/partials/participant-orders-list.html.twig
templates/program/hpo/ppsc/in-person-enrollment.html.twig
templates/program/hpo/ppsc/navbar-bs5.html.twig
templates/program/hpo/ppsc/navbar.html.twig
tests/Service/PpscApiServiceTest.php
web/assets/css/app.css
web/assets/js/views/PediatricOrderSafetyChecks.js

| Jira Ticket(s)      | HPRO-1913

[HPRO-1913] PPSC PM & Order UI customizations

---

templates/program/nph/order/collect.html.twig

| Target Release?     | 4.3.15 
| Jira Ticket(s)      | HPRO-1905

[HPRO-1905] Hide collection time label in the kit 2 order collection page

---

src/Controller/AuthController.php
src/EventListener/ResponseSecurityHeadersTrait.php
src/Service/EnvironmentService.php
src/Service/Ppsc/PpscApiService.php
src/Service/SalesforceAuthService.php
tests/Service/PpscApiServiceTest.php

| Jira Ticket(s)      | HPRO-1976

[HPRO-1976] PPSC load configurations from env variable

---

src/Controller/NphBiobankController.php
src/Form/Nph/NphOrderCollect.php
src/Form/Nph/NphOrderForm.php
src/Form/Nph/NphSampleFinalizeType.php
src/Service/Nph/NphOrderService.php
templates/program/nph/order/partials/sample-finalize-banner-message.html.twig
templates/program/nph/order/sample-finalize.html.twig
web/assets/js/views/NphSampleFinalize.js

| Target Release?     | 4.3.16
| Composer updates?   |/❌ 
| Jira Ticket(s)      | HPRO-1907

[HPRO-1907] NPH Biobank View resubmit orders

---

templates/partials/drc-support-text.html.twig

| Jira Ticket(s)      | HPRO-1918

[HPRO-1918] User management - update support text

---

src/Controller/OrderController.php
src/Form/OrderType.php
templates/partials/participant-orders-list-bs5.html.twig

| Jira Ticket(s)      | HPRO-1982

[HPRO-1982] Provide option for DV sites to remove the tube select dropdown

---

src/Entity/NphOrder.php
src/Form/Nph/NphSampleFinalizeType.php
templates/program/nph/order/sample-finalize.html.twig

| Target Release?     | 4.3.16
| Jira Ticket(s)      | HPRO-1949

[HPRO-1949] Disable volume field for hail & nail orders

---

src/Controller/NphBiobankController.php
src/Controller/NphOrderController.php
src/Entity/NphSample.php
src/Form/Nph/NphOrderCollect.php
src/Form/Nph/NphOrderForm.php
src/Form/Nph/NphSampleFinalizeType.php
src/Form/Nph/NphSampleResubmitType.php
src/Service/Nph/NphOrderService.php
templates/program/nph/order/partials/sample-finalize-confirmation-resubmit-modal.html.twig
templates/program/nph/order/sample-finalize.html.twig
web/assets/js/views/NphSampleFinalize.js

| Jira Ticket(s)      | HPRO-1907

[HPRO-1907] Fix NPH biobank view resubmit orders

---

templates/partials/drc-support-text.html.twig

| Jira Ticket(s)      | HPRO-1918

[HPRO-1918] Update DRC support text

---

src/Entity/NphOrder.php
templates/program/nph/order/macros/display-text.html.twig
templates/program/nph/order/partials/sample-finalize-banner-message.html.twig

| Jira Ticket(s)      | HPRO-1907

[HPRO-1907] Fix participant summary page badge status

---

src/Helper/PpscParticipant.php

| Jira Ticket(s)      | HPRO-1986

[HPRO-1986] Update PPSC participant fields values

---

src/Form/Nph/NphSampleFinalizeType.php

| Target Release?     | 4.3.16.1
| Jira Ticket(s)      | HPRO-1991

[HPRO-1991] Fix hair/nail field disable issue

---

src/Service/Ppsc/PpscApiService.php

| Jira Ticket(s)      | HPRO-1993

[HPRO-1993] PPSC request and participant details api changes

---

src/Controller/NphBiobankController.php
templates/program/nph/biobank/participant.html.twig
web/assets/css/nph.css

| Target Release?     | 4.3.17
| Jira Ticket(s)      | HPRO-1948

[HPRO-1948] NPH update biobank participant details page

---

templates/biobank/order.html.twig
templates/biobank/partials/biobank-order-details.html.twig

| Target Release?     |/Next available 
| Jira Ticket(s)      | HPRO-2008

[HPRO-2008] AOU fix biobank view dv sample codes

---

src/Controller/AuthController.php
src/Security/SalesforceAuthenticator.php
src/Service/MeasurementService.php
src/Service/SalesforceAuthService.php

| Jira Ticket(s)      | HPRO-2019

[HPRO-2019] Configure staff portal credentials

---

src/Service/GoogleGroupsService.php
templates/settings/settings.html.twig

| Jira Ticket(s)      | HPRO-1998

[HPRO -1998] [HPRO-1999] PPSC disable HPO site user access

---

src/Service/OrderService.php

| Jira Ticket(s)      | HPRO-2031

[HPRO-2031] Handle order revert error

---

templates/biobank/partials/biobank-order-details.html.twig

| Target Release?     | 4.3.18 
| Jira Ticket(s)      | HPRO-2008

[HPRO-2008] Fix saliva sample code issue

---

templates/biobank/orders-recent-modify.html.twig

| Jira Ticket(s)      | HPRO-2010

[HPRO-2010] Fix biobank recent modify script tag issue

---

templates/measurementform/metrics.html.twig

| Target Release?     | 4.3.19 
| Jira Ticket(s)      | HPRO-2009

[HPRO-2009] Fix finalized forms alternate units layouts issue

---

src/Model/Measurement/versions/0.3.3-ehr.json

| Target Release?     | 4.3.19 
| Jira Ticket(s)      | HPRO-2009

[HPRO-2009] Fix EHR forms alternate units fields layout issue

---

src/Service/Nph/NphDlwBackfillService.php

| Target Release?     | 4.3.19 
| Jira Ticket(s)      | HPRO-2022

[HPRO-2022] Reduce resend limit size

---

src/Form/DlwType.php
web/assets/js/views/NphDlw.js

| Jira Ticket(s)      | HPRO-2022

[HPRO-2022] Bug fixes for form crash and error message not getting removed.

---

src/Form/DlwType.php

| Jira Ticket(s)      | HPRO-2022

[HPRO-2022] Change today to now

---

templates/review/_macros.html.twig

| Jira Ticket(s)      | HPRO-2037

[HPRO-2037] Fix todays review order finailzed count

---

templates/biobank/order.html.twig
templates/biobank/participant.html.twig

| Jira Ticket(s)      | HPRO-2016

[HPRO-2016] Update biobank view headers

---

src/Controller/DebugToolsController.php
src/Controller/MeasurementsController.php
src/Service/MeasurementQueueService.php
src/Service/MeasurementService.php
src/Service/OrderService.php

| Jira Ticket(s)      | HPRO-2034

[HPRO-2034] PPSC api pass participant id to measurements and order api

---

src/Helper/Participant.php
tests/Helper/ParticipantTest.php

| Target Release?     | 4.3.20 
| Jira Ticket(s)      | HPRO-2051

[HPRO-2051] Remove gROR status check from blocking PM&B collection

---

templates/measurement/index.html.twig

| Jira Ticket(s)      | HPRO-2039

[HPRO-2039] Add return to in-person enrollment link in PM form

---

templates/review/_macros.html.twig
templates/review/modified_measurements.html.twig
templates/review/modified_orders.html.twig
templates/review/today.html.twig
templates/review/unfinalized_measurements.html.twig
templates/review/unfinalized_orders.html.twig

| Jira Ticket(s)      | HPRO-2050

[HPRO-2050] PPSC remove hyperlinks in daily review

---

src/Controller/CronController.php
src/Controller/SitesController.php
src/Form/SiteType.php
src/Service/DebugToolsService.php
src/Service/Ppsc/PpscApiService.php
templates/admin/sites/index.html.twig

| Jira Ticket(s)      | HPRO-2006

[HPRO-2006] Modify admin site management features

---

templates/program/hpo/ppsc/in-person-enrollment.html.twig

| Target Release?     | 4.3.20 
| Jira Ticket(s)      | HPRO-2057

[HPRO-2057] Add In-Person Enrollment header text

---

src/Controller/DefaultController.php
templates/logout.html.twig
templates/order/collect.html.twig
templates/order/print-labels.html.twig
templates/order/process.html.twig
templates/program/hpo/ppsc/base.html.twig
templates/program/hpo/ppsc/in-person-enrollment.html.twig
templates/program/hpo/ppsc/partials/display-site-name.html.twig
templates/program/hpo/ppsc/partials/participant-measurement-list.html.twig
templates/program/hpo/ppsc/partials/participant-orders-list.html.twig
templates/timeout.html.twig
web/assets/js/views/PhysicalEvaluation-0.3-ehr.js

| Jira Ticket(s)      | HPRO-2038

[HPRO-2038] FIX EHR PM form fields disable issue

---

composer.lock

| Target Release?     | 4.4.20 
| New feature?        |❌ 
| Jira Ticket(s)      | HPRO-2064

[HPRO-2064] Upgrade Symfony packages to latest 5.4.x

---

src/EventListener/RequestListener.php
src/Repository/NoticeRepository.php
src/Security/SalesforceAuthenticator.php
src/Security/UserProvider.php
templates/error-auth-salesforce.html.twig
web/assets/js/views/NoticeEdit.js

| Jira Ticket(s)      | HPRO-2056

[HPRO-2058] Update AOU page notice functionality

---

src/Entity/NphOrder.php
src/Service/Nph/NphProgramSummaryService.php

| Jira Ticket(s)      | HPRO-2040

[HPRO-2040] Fix visit display name issue

---

src/Form/MeasurementRevertType.php
src/Form/OrderRevertType.php
src/Form/ReviewTodayFilterType.php
templates/measurement/blood-donor-check.html.twig
templates/measurement/index.html.twig
templates/measurement/modify.html.twig
templates/order/check-pediatric.html.twig
templates/order/check.html.twig
templates/order/collect.html.twig
templates/order/create.html.twig
templates/order/finalize.html.twig
templates/order/modify.html.twig
templates/order/partials/create-pediatric.html.twig
templates/order/print-labels.html.twig
templates/order/print-requisition.html.twig
templates/order/process.html.twig
templates/program/hpo/ppsc/in-person-enrollment.html.twig
templates/review/today.html.twig
templates/settings/settings.html.twig
web/assets/css/app.css
web/assets/js/global.js

| Jira Ticket(s)      | HPRO-2061

[HPRO-2061] PPSC Update UI

---

composer.lock
src/Controller/DefaultController.php
src/Entity/Site.php
src/EventListener/RequestListener.php
src/Security/UserProvider.php
templates/bundles/TwigBundle/Exception/error.html.twig
templates/measurement/index.html.twig
templates/program/hpo/navbar-bs5.html.twig
templates/program/hpo/navbar.html.twig
templates/program/hpo/ppsc/partials/display-site-name.html.twig
templates/program/nph/navbar-bs5.html.twig
templates/program/nph/navbar.html.twig

| Target Release?     | 4.4.0
| Jira Ticket(s)      | HPRO-2064

[HPRO-2064] Upgrade Symfony packages 2

---

composer.json
composer.lock
templates/admin/sites/sync.html.twig
templates/macros/display-text.html.twig
templates/order/modify.html.twig
templates/partials/participant-activities.html.twig
templates/program/nph/biobank/participant.html.twig
templates/program/nph/order/macros/display-text.html.twig
templates/program/nph/participant/index.html.twig
web/assets/js/views/PhysicalEvaluation-0.3-ehr.js

| Jira Ticket(s)      | HPRO-2065

[HPRO-2065] Upgrade twig from version 2 to 3

---

src/Helper/NphParticipant.php
tests/Helper/NphParticipantTest.php

| Jira Ticket(s)      | HPRO-1966

[HPRO-1966] Update NPH participant module assignment logic

---

templates/program/nph/order/macros/display-text.html.twig

| Jira Ticket(s)      | HPRO-1820

[HPRO-1820] Fix Hair&Nail consent display issue

---

src/Controller/HpoPpscController.php
src/EventListener/RequestListener.php
src/Service/SiteService.php
templates/program/hpo/ppsc/invalid-site.html.twig

| Target Release?     | 4.4.0
| Jira Ticket(s)      | HPRO-2002

[HPRO-2002] Handle invalid sites

---

migrations/Version20241203173735.php
src/Controller/MeasurementsController.php
src/Controller/OrderController.php
src/Entity/Measurement.php
src/Entity/Order.php
src/Entity/Site.php
src/Helper/PpscParticipant.php
src/Model/Measurement/Fhir.php
src/Service/MeasurementService.php
src/Service/OrderService.php
src/Service/SiteService.php
src/Service/SiteSyncService.php
tests/Entity/MeasurementTest.php
tests/Entity/OrderTest.php

| Target Release?     | 4.4.0.1 
| Jira Ticket(s)      | HPRO-2088

[HPRO-2088] Handle site id prefixes in RDR awardee API

---

migrations/Version20241204044839.php

| Target Release?     | 4.4.0.1
| Jira Ticket(s)      | HPRO-2088

[HPRO-2088] Increase awardees table id column length

---

migrations/Version20241205215727.php
src/Controller/MeasurementsController.php
src/Controller/OrderController.php
src/Entity/Measurement.php
src/Entity/Order.php
src/Entity/Site.php
src/Helper/PpscParticipant.php
src/Model/Measurement/Fhir.php
src/Security/User.php
src/Security/UserProvider.php
src/Service/MeasurementService.php
src/Service/OrderService.php
src/Service/SiteService.php
src/Service/SiteSyncService.php
tests/Entity/MeasurementTest.php
tests/Entity/OrderTest.php

| Target Release?     | 4.4.0.2
| Jira Ticket(s)      | HPRO-2089

[HPRO-2089] Update site id prefix logic

---

src/EventListener/ResponseListener.php
src/EventListener/ResponseSecurityHeadersTrait.php
templates/admin/sites/index.html.twig
templates/biobank/order.html.twig
web/assets/js/views/BiobankOrder.js

| Target Release?     | 4.4.0.3 
| Jira Ticket(s)      | HPRO-2092

[HPRO-2092] Allow configuration of frame ancestors from the datastore

---

templates/error-auth-salesforce-groups.html.twig
templates/error-auth-salesforce-landing-page.html.twig
templates/error-auth-salesforce-request-id.html.twig
templates/error-auth-salesforce-session.html.twig
templates/error-auth-salesforce.html.twig

| Target Release?     | 4.4.0.4
| Jira Ticket(s)      | HPRO-2097

[HPRO-2097] Change PPSC pages navbar

---

config/packages/security.yaml
migrations/Version20241217164512.php
src/Controller/AccessManagementController.php
src/Controller/HelpController.php
src/Controller/NoticeController.php
src/Entity/Notice.php
src/EventListener/RequestListener.php
src/Repository/NoticeRepository.php
templates/notice/edit.html.twig
templates/notice/index.html.twig
templates/program/nph/admin/index.html.twig
web/assets/js/views/NoticeEdit.js

| Target Release?     | 4.4.1
| Jira Ticket(s)      | HPRO-1946

[HPRO-1946] NPH admin implement page notices

---

src/Controller/NphBiobankController.php

| Target Release?     | 4.4.1
| Jira Ticket(s)      | HPRO-2053

[HPRO-2053] Disable notes field for unfinalized samples in biobank view

---

web/assets/js/views/NphBiobankReview.js

| Target Release?     | 4.4.1 
| Jira Ticket(s)      | HPRO-1862

[HPRO-1862] Handle names that has comma separated values

---

templates/help/nph/faq.html.twig
templates/help/nph/index.html.twig
templates/help/nph/sop-pdf.html.twig

| Target Release?     | 4.4.2 
| Jira Ticket(s)      | HPRO-2080

[HPRO-2080] Update help support information

---

src/Controller/NphOrderController.php
src/Form/Nph/NphOrderForm.php
src/Form/Nph/NphSampleFinalizeType.php
src/Service/Nph/NphOrderService.php
templates/program/nph/order/collect.html.twig
templates/program/nph/order/partials/modals/aliquot-collection-notes-help-modal.html.twig
templates/program/nph/order/partials/modals/collection-notes-help-modal.html.twig
templates/program/nph/order/sample-finalize.html.twig
tests/Service/NphOrderServiceTest.php
web/assets/js/views/NphOrder.js
web/assets/js/views/NphSampleFinalize.js

| Target Release?     | 4.4.2
| Jira Ticket(s)      | HPRO-2054

[HPRO-2054] NPH add collection notes edit functionality in sample aliquot page

---

web/assets/js/views/NphSampleFinalize.js

| Target Release?     | 4.4.2
| Jira Ticket(s)      | HPRO-2054

[HPRO-2054] Add exclamation icon next to notes warning text

---

templates/program/nph/participant/quick-view.html.twig

| Target Release?     | 4.4.2 
| Jira Ticket(s)      | HPRO-2055

[HPRO-2055] Add comma b/w last name and first name in quick view

---

templates/program/nph/participant/quick-view.html.twig

| Target Release?     | 4.4.2
| Jira Ticket(s)      | HPRO-2055

[HPRO-2055] Add comma b/w last name and first name in quick view bootstrap 3 modal

---

templates/review/_page_heading.html.twig
templates/review/modified_measurements.html.twig
templates/review/modified_orders.html.twig
templates/review/today.html.twig
templates/review/unfinalized_measurements.html.twig
templates/review/unfinalized_orders.html.twig
web/assets/js/views/review.js

| Target Release?     | 4.4.3 
| Jira Ticket(s)      | HPRO-1623

[HPRO-1623] Update AOU daily review pages to bootstrap 5

---

templates/program/nph/biobank/participants.html.twig

| Target Release?     | 4.4.3
| Jira Ticket(s)      | HPRO-1800

[HPRO-1800] Update biobank view participant lookup page to bootstrap 5

---

templates/settings/settings.html.twig
web/assets/css/app.css

| Target Release?     | 4.4.3 
| Jira Ticket(s)      | HPRO-1803

[HPRO-1803] Update settings page to bootstrap 5

---

src/Controller/NphParticipantLookupController.php
templates/program/nph/index.html.twig
templates/program/nph/participantlookup/participants.html.twig

| Target Release?     | 4.4.4
| Jira Ticket(s)      | HPRO-2129

[HPRO-2129] NPH add participant search by biobank id

---

src/Mail/Sendgrid.php
src/Service/Message.php

| Target Release?     | 4.4.4 
| Jira Ticket(s)      | HPRO-2131

[HPRO-2131] Migrate mandrill to sendgrid

---

package-lock.json
package.json
templates/program/nph/admin/sites/edit.html.twig
templates/program/nph/admin/sites/index.html.twig
web/assets/js/app-bs5.js

| Target Release?     | 4.4.4 
| Jira Ticket(s)      | HPRO-1802

[HPRO-1802] Update NPH site management pages to bootstrap 5

---

templates/biobank/index.html.twig
templates/biobank/orders.html.twig
templates/biobank/participants.html.twig

| Target Release?     | 4.4.4 
| Jira Ticket(s)      | HPRO-1799

[HPRO-1799] AOU update biobank view home and lookup pages to bootstrap 5

---

templates/site-select.html.twig

| Target Release?     | 4.4.4 
| Jira Ticket(s)      | HPRO-2114

[HPRO-2114] Update NPH select site page to bootstrap 5

---

templates/biobank/index.html.twig
templates/program/nph/participantlookup/participants.html.twig

| Target Release?     | 4.4.4
| Jira Ticket(s)      | HPRO-2129

[HPRO-2129] Update search icon

---

src/Repository/MeasurementRepository.php
templates/order/check-pediatric.html.twig
templates/order/check.html.twig
templates/order/pediatric/blood-draw-modal.html.twig

| Target Release?     | 4.4.5 
| Jira Ticket(s)      | HPRO-1619

[HPRO-1619] AOU update order safety check pages to bootstrap 5

---

templates/order/check-pediatric.html.twig
templates/order/check.html.twig
templates/order/create.html.twig
templates/order/partials/create-pediatric.html.twig

| Target Release?     | 4.4.5 
| Jira Ticket(s)      | HPRO-1870

[HPRO-1870] Update AOU order create to bootstrap 5

---

templates/order/check-pediatric.html.twig
templates/order/check.html.twig
templates/order/create.html.twig
templates/order/header.html.twig
templates/order/partials/create-pediatric.html.twig
templates/order/print-labels.html.twig
templates/order/print-requisition.html.twig
web/assets/js/views/OrderRequisition.js

| Target Release?     | 4.4.5
| Jira Ticket(s)      | HPRO-1871

[HPRO-1871] AOU update print and requisition label tabs to bootstrap 5

---

src/Form/OrderRevertType.php
src/Form/OrderType.php
templates/order/collect.html.twig
templates/order/finalize.html.twig
templates/order/modify.html.twig
templates/order/print-labels.html.twig
web/assets/js/views/OrderCollect.js

| Target Release?     | 4.4.6 
| Jira Ticket(s)      | HPRO-1876

[HPRO-1876] Update Order modify pages to bootstrap 5

---

package-lock.json
package.json
src/Form/NoticeType.php
templates/notice/edit.html.twig
templates/notice/index.html.twig
web/assets/css/bs5.css
web/assets/js/app-bs5.js
web/assets/js/global.js
web/assets/js/views/NoticeEdit.js

| Target Release?     | 4.4.6
| Jira Ticket(s)      | HPRO-2110

[HPRO-2110] Update AOU/NPH admin page notices to bootstrap 5

---

docker-compose.yml

| Target Release?     | 4.4.6
| Jira Ticket(s)      | HPRO-2152

[HPRO-2152] Update docker image mysql version to 8

---

package-lock.json
package.json
templates/form/simple_checkbox-bs5.html.twig
templates/program/nph/order/generate-orders.html.twig
templates/program/nph/order/partials/generate-orders-header.html.twig
templates/program/nph/order/partials/modals/downtime-warning-modal.html.twig
web/assets/css/bs5.css
web/assets/css/nph.css
web/assets/js/app-bs5.js
web/assets/js/views/NphOrderCreate.js

| Target Release?     | 4.4.6 
| Jira Ticket(s)      | HPRO-1797,  HPRO-2145

[HPRO-1797] [HPRO-2145] NPH update samples generation page to bootstrap 5

---

templates/program/nph/order/generate-orders.html.twig

| Target Release?     | 4.4.6 
| Jira Ticket(s)      | HPRO-2145

[HPRO-2145] Align Enter Downtime button to extreme right

---

src/Entity/Order.php
src/Form/OrderType.php
templates/order/collect.html.twig
templates/order/finalize.html.twig
web/assets/js/views/OrderCollect.js

| Target Release?     | 4.4.7
| Jira Ticket(s)      | HPRO-2161

[HPRO-2161] Remove 2SAL0 sample for pediatric orders

---

migrations/Version20250320164653.php
src/Controller/CronController.php
src/Entity/Measurement.php
src/Repository/MeasurementRepository.php
src/Service/MeasurementService.php
tests/Service/MeasurementServiceTest.php

| Target Release?     | 4.4.7 
| Jira Ticket(s)      | HPRO-2154

[HPRO-2154] Pediatrics measurements save gender and backfill old measurements

---

src/Service/MeasurementService.php
src/Service/OrderService.php
src/Service/Ppsc/PpscApiService.php

| Target Release?     | 4.4.7 
| Jira Ticket(s)      | HPRO-2156

[HPRO-2156] PPSC implement token cache mechanism for MuleSoft API GET calls

---

src/Entity/Order.php

| Target Release?     | 4.4.7.1
| Jira Ticket(s)      | HPRO-2186

[HPRO-2186] Remove 2SAL0 sample form payload

---

package-lock.json
package.json
templates/program/nph/biobank/audit.html.twig
templates/program/nph/biobank/orders-downtime.html.twig
templates/program/nph/biobank/orders-recently-modified.html.twig
templates/program/nph/biobank/orders-today.html.twig
templates/program/nph/biobank/orders-unfinalized.html.twig
templates/program/nph/biobank/orders-unlocked.html.twig
templates/program/nph/biobank/partials/orders-review-table.html.twig
templates/program/nph/biobank/partials/review-page-heading.html.twig
web/assets/js/app-bs5.js
web/assets/js/views/NphBiobankReview.js

| Target Release?     | 4.4.8
| Jira Ticket(s)      | HPRO-2109

[HPRO-2109] Update NPH biobank daily review pages to bootstrap 5

---

web/assets/js/app.js

| Target Release?     | 4.4.8 
| Jira Ticket(s)      | HPRO-2109

[HPRO-2109] Fix datatables buttons js issue

---

src/Controller/NphOrderController.php
src/Service/HelpService.php
templates/program/nph/order/generate-orders.html.twig
templates/program/nph/order/partials/modals/downtime-references-modal.html.twig
web/assets/css/app.css
web/assets/js/views/NphOrderCreate.js

| Target Release?     | 4.4.9 
| Jira Ticket(s)      | HPRO-2167

[HPRO-2167] NPH add downtime references

---

templates/program/nph/order/collect.html.twig

| Target Release?     | 4.4.9
| Jira Ticket(s)      | HPRO-2159

[HPRO-2159] NPH display order generation time in collection page

---

templates/review/_page_heading.html.twig

| Target Release?     | 4.4.9
| Jira Ticket(s)      | HPRO-2132

[HPRO-2132] Update daily review title

---

src/Controller/AccessManagementController.php
src/Form/Nph/NphAdminOrderGenerationType.php
src/Service/Nph/NphOrderService.php
templates/program/nph/accessmanagement/order-manage.html.twig
templates/program/nph/accessmanagement/partials/order-lookup.html.twig
templates/program/nph/order/collect.html.twig
templates/program/nph/order/macros/display-text.html.twig
tests/Service/NphOrderServiceTest.php
web/assets/js/views/NphOrderManagement.js

| Target Release?     | 4.4.9
| Jira Ticket(s)      | HPRO-2160

[HPRO-2160] NPH admin order generation fixes

---

src/Controller/NphBiobankController.php
src/Entity/NphAdminOrderEditLog.php
src/Repository/NphAdminOrderEditLogRepository.php
templates/program/nph/biobank/admin-orders-generation-audit.html.twig
templates/program/nph/biobank/audit.html.twig
templates/program/nph/biobank/orders-downtime.html.twig
templates/program/nph/biobank/partials/orders-review-table.html.twig
templates/program/nph/biobank/partials/review-page-heading.html.twig

| Target Release?     | 4.4.10 
| Jira Ticket(s)      | HPRO-2163

[HPRO-2163] Create Biobank View for NPH admin order edit 

---

src/Controller/NphOrderController.php
src/Controller/NphParticipantSummaryController.php
src/Entity/NphOrder.php
src/Entity/NphSample.php
src/Nph/Order/Nomenclature.php
src/Service/Nph/NphOrderService.php
src/Service/Nph/NphProgramSummaryService.php
templates/program/nph/participant/index.html.twig
tests/Service/NphOrderServiceTest.php
tests/Service/data/order_module_1.json

| Target Release?     | 4.4.10 
| Jira Ticket(s)      | HPRO-2166

[HPRO-2166] NPH order generation stool kit updates

---

src/Entity/NphSample.php
src/Service/Nph/NphOrderService.php
tests/Service/NphOrderServiceTest.php

| Target Release?     | 4.4.10 
| Jira Ticket(s)      | HPRO-2188

[HPRO-2188] Include stool 2 samples for module 3

---

templates/measurementform/0.3-peds-weight.html.twig
templates/measurementform/0.3-peds.html.twig

| Jira Ticket(s)      | HPRO-2188

[HPRO-2188] Add colon for average and growth percentile text

---

templates/measurementform/0.3-peds-weight.html.twig
templates/measurementform/0.3-peds.html.twig
templates/program/nph/biobank/partials/orders-review-table.html.twig
web/assets/js/views/NphBiobankReview.js

| Jira Ticket(s)      | HPRO-2189

[HPRO-2189] NPH biobank daily review counts

---

templates/admin/sites/edit.html.twig
templates/admin/sites/index.html.twig
templates/admin/sites/sync.html.twig

| Jira Ticket(s)      | HPRO-2116

[HPRO-2116] Update AOU site management pages to bootstrap 5

---

src/Form/RemoveGroupMemberType.php
templates/accessmanagement/add-member.html.twig
templates/accessmanagement/dashboard.html.twig
templates/accessmanagement/group-members.html.twig
templates/accessmanagement/remove-member.html.twig
templates/program/hpo/accessmanagement/groups.html.twig
templates/program/nph/accessmanagement/groups.html.twig
templates/program/nph/admin/sites/edit.html.twig
web/assets/js/views/Datatable.js
web/assets/js/views/GroupMemberRemove.js

| Jira Ticket(s)      | HPRO-2113

[HPRO-2113] Migrate NPH User Management System to bootstrap 5

---

templates/jira/release.txt.twig

| Jira Ticket(s)      | HPRO-2171

[HPRO-2171] Update JIRA release notes

---

src/Entity/NphSample.php
templates/program/nph/order/sample-finalize.html.twig
web/assets/js/views/NphSampleFinalize.js

| Target Release?     | 4.4.12
| Jira Ticket(s)      | HPRO-2168

[HPRO-2168] Update aliquot time warning logic for 24 hr Urine sample

---

src/Controller/NphBiobankController.php
src/Controller/NphOrderController.php
src/Service/Nph/NphParticipantSummaryService.php
templates/program/nph/biobank/order-collect-details.html.twig
templates/program/nph/biobank/participant.html.twig
templates/program/nph/order/partials/form-participant-withdrawn-banner.html.twig
templates/program/nph/order/sample-finalize.html.twig

| Target Release?     | 4.4.13 
| Jira Ticket(s)      | HPRO-2194

[HPRO-2194] NPH biobank view - handle deactivation/withdrawn participants

---

templates/program/nph/order/sample-modify-bulk.html.twig
web/assets/js/views/NphOrderModify.js

| Target Release?     | 4.4.13
| Jira Ticket(s)      | HPRO-2193

[HPRO-2193] Group sample by diet period in cancel all page

---

templates/program/nph/biobank/participant.html.twig
templates/program/nph/participant/index.html.twig

| Target Release?     | 4.4.13
| Jira Ticket(s)      | HPRO-2194

[HPRO-2194] Display module specific withdrawn/deactivation banner messages

---

src/Form/DlwType.php
templates/program/nph/order/dlw-collect.html.twig
templates/program/nph/order/partials/pound-modal.html.twig
web/assets/js/bs5.js
web/assets/js/views/NphOrder.js

| Target Release?     | 4.4.16
| Jira Ticket(s)      | HPRO-2123

[HPRO-2123] Update NPH DLW collection to bootstrap 5

---

src/Controller/NphOrderController.php
src/Entity/NphOrder.php
src/Form/Nph/NphOrderCollect.php
src/Form/Nph/NphOrderForm.php
templates/program/nph/order/collect.html.twig
templates/program/nph/order/partials/modals/collection-notes-help-modal.html.twig
templates/program/nph/order/partials/order-collect-urine24.html.twig
templates/program/nph/order/partials/order-header.html.twig
templates/program/nph/order/sample-modify.html.twig
web/assets/css/bs5.css
web/assets/js/bs5.js
web/assets/js/views/NphOrder.js
web/assets/js/views/NphSampleFinalize.js

| Target Release?     | 4.4.16 
| Jira Ticket(s)      | HPRO-2122, HPRO-2228

[HPRO-2122] [HPRO-2228] NPH update order collection to bootstrap 5 and fix aliquot page barcode scan issues

---

templates/program/nph/order/label-print.html.twig
web/assets/css/nph.css

| Target Release?     | 4.4.16
| Jira Ticket(s)      | HPRO-2124

[HPRO-2124] Update NPH sample print labels to bootstrap 5

---

templates/program/nph/biobank/order-collect-details.html.twig
templates/program/nph/order/collect.html.twig

| Target Release?     | 4.4.17 
| Jira Ticket(s)      | HPRO-2221

[HPRO-2221] Update NPH biobank order collect page to bootstrap 5

---

src/Helper/Participant.php
src/Helper/PpscParticipant.php
templates/biobank/order.html.twig
templates/biobank/participant.html.twig

| Target Release?     | 4.4.18
| Jira Ticket(s)      | HPRO-2227

[HPRO-2227] Remove AIAN field from AOU biobank view

---

web/assets/js/views/NphSampleFinalize.js

| Target Release?     | 4.4.19
| Jira Ticket(s)      | HPRO-2241

[HPRO-2241] Autofill aliquot time on newly added aliquots

---

src/Form/MeasurementRevertType.php
src/Form/MeasurementType.php
templates/measurement/blood-donor-check.html.twig
templates/measurement/modify.html.twig
templates/measurementform/0.3-blood-donor.html.twig
templates/measurementform/0.3-ehr.html.twig
templates/measurementform/metrics.html.twig
web/assets/css/app.css
web/assets/js/bs5.js
web/assets/js/views/PhysicalEvaluation-0.1.js
web/assets/js/views/PhysicalEvaluation-0.2.js
web/assets/js/views/PhysicalEvaluation-0.3-blood-donor.js
web/assets/js/views/PhysicalEvaluation-0.3-ehr.js
web/assets/js/views/PhysicalEvaluation-0.3-peds.js
web/assets/js/views/PhysicalEvaluation-0.3.js

| Target Release?     | 4.4.21 
| Jira Ticket(s)      | HPRO-1874

[HPRO-1874] Update AOU PM modify form to bootstrap 5
