README.md
[[HPRO-401](https://precisionmedicineinitiative.atlassian.net/browse/HPRO-401)]
After moving the repository to the All of Us organization, we need to update the URL for the CircleCI badge image in the README file.
=> [HPRO-401] Update CircleCI badge image URL

composer.json, composer.lock, src/Pmi/Console/Command/DeployCommand.php, src/Pmi/Twig/Provider/TwigServiceProvider.php
The primary goal of this PR is to address [[HPRO-412](https://precisionmedicineinitiative.atlassian.net/browse/HPRO-412)] by upgrading to SensioLabs Security Checker 5.0.  This upgrade involved some changes to the way we are using it in our deploy command.  The formatting helper was removed since that is done server-side now, but we need both the JSON format for our ignore file implementation along with the formatting.  I accomplished this by copying some of the old formatting helper code from 4.1.
Until now, we have been updating specific composer packages as necessary (when we need changes made in newer versions or to address security vulnerabilities).  This PR updates all of our dependencies.  The most notable change is that this brings all of our Symfony components up to 3.4.x.  One …
=> [HPRO-412] Update composer dependencies and upgrade to SensioLabs Security Checker 5.0

package-lock.json, package.json
[[HPRO-410](https://precisionmedicineinitiative.atlassian.net/browse/HPRO-410)]
This PR updates our npm dependencies and the `package-lock.json` file.
The original intent of this PR was to get the `package-lock.json` file up to date, because a previous PR had added dependencies to `package.json` but did not update the lock file.  I took this opportunity to update our npm dependencies:
```
+ gulp-rename@1.4.0
+ datatables.net-buttons@1.5.4
+ browser-sync@2.26.0
+ jsbarcode@3.11.0
+ datatables.net-buttons-bs@1.5.4
```
The browser-sync update includes a fix for a low severity vulnerability in `browser-sync > localtunnel > debug`.
=> [HPRO-410] Update npm dependencies

src/Pmi/Console/Command/MetricsCommand.php
This threw an error in our PHP 5.5 runtime because it is using 5.6 syntax for a class constant that is an array. Downgrades it to a static variable instead. Also updates inline method documentation.
[[HPRO-413](https://precisionmedicineinitiative.atlassian.net/browse/HPRO-413)]
=> [HPRO-413] Metrics Command > Use static variable instead of constant

src/Pmi/Controller/WorkQueueController.php, src/Pmi/WorkQueue/WorkQueue.php, views/participant.html.twig, views/workqueue/index.html.twig, web/assets/js/views/workqueue.js
[[HPRO-408](https://precisionmedicineinitiative.atlassian.net/browse/HPRO-408)]
* Adds the withdrawal reason (and justification if it exists) to the message that is displayed when viewing a withdrawn participant (screenshot below)
* Adds the withdrawal reason to the work queue (table and CSV export)
* Fixes a bug where the biospecimen and physical measurements site columns in the work queue were incorrectly associated with the default column group button.
=> [HPRO-408] Add withdrawal reason to participant page and work queue

views/help/faq.html.twig, views/help/sop-pdf.html.twig, views/order-print-labels.html.twig, views/order-print-requisition.html.twig
[[HPRO-415](https://precisionmedicineinitiative.atlassian.net/browse/HPRO-415)]
Users who's browsers are configured to not allow embedded PDFs previously had no way of downloading or opening the PDFs in a new window/tab.  This adds a link that opens the PDF in a new window.  If a browser is not configured to view PDFs at all (embedded or not), the PDF will be downloaded (and, at least in Chrome, the new tab will be automatically closed).
A direct link to PDFs has been added for biobank order labels, biobank order requisitions, and SOP documents.
=> [HPRO-415] Add link to open embedded PDFs

src/Pmi/Evaluation/Evaluation.php, src/Pmi/Order/Order.php
Updates reason "codes" for consistency and clarity.  ("Codes" in quotes because these are still just free text fields in the RDR, but we want to maintain some consistency if/when the reason labels change).  The codes now all start with `(ORDER|PM)_(CANCEL|RESTORE|AMEND)`.
I also changed the way reasons are conditionally removed so that they are removed based on the code, and not the label.
Note: this also fixes a bug where the labeling error reason wasn't removed from the reasons when cancelling a DV kit order due to case sensitivity.
=> v1.5.0 Update reason codes

src/Pmi/Controller/AdminController.php, src/Pmi/Controller/OrderController.php, views/admin/sites/index.html.twig, views/order-print-labels.html.twig, views/order-print-requisition.html.twig
[[HPRO-434](https://precisionmedicineinitiative.atlassian.net/browse/HPRO-434)]
* Adds a space between the label error icon and title in the panel heading
* Fixes language to consistently refer to "labels" and "requisition"
* Fixes capitalization of MayoLINK
=> [HPRO-434] Minor changes to error messages and other text

.retireignore.json, package-lock.json, package.json, src/Pmi/Console/Command/DeployCommand.php
[[HPRO-438](https://precisionmedicineinitiative.atlassian.net/browse/HPRO-438)]
Note that the audit output will show up twice when building, since non-local builds run `npm install` first, which will include the audit status.  `npm audit` is later run separately so that we can catch the non-0 exit code if there are vulnerabilities.
=> [HPRO-438] Replace Retire.js with npm audit

src/Pmi/Controller/DefaultController.php
[[HPRO-448](https://precisionmedicineinitiative.atlassian.net/browse/HPRO-448)]
Selecting a site or awardee context uses the same interface, even though they are two different roles.  This change fixes a bug where users belonging to multiple site/awardee groups would get an error when selecting an awardee context because the awardee is not a valid site.
=> [HPRO-448] Fix selection of awardee in site selector

views/base-head.html.twig, views/dashboard/index.html.twig
Adds Google Analytics tracking to the tabs in Dashboard by setting a fake page (for now -- later version of dashboard may implement URL) and then sending a `pageview` event.
Also implements a change in the base template to mock a `ga()` object.
Reference: https://developers.google.com/analytics/devguides/collection/analyticsjs/single-page-applications
[[DASH1-72](https://precisionmedicineinitiative.atlassian.net/browse/DASH1-72)]
=> [DASH1-72] Track tab views in Dashboard

views/dashboard/index.html.twig
The API endpoint is not fast enough to meet the request deadline of 60 seconds, even with batching. This PR enforces that limit on the frontend.
[[DASH1-87](https://precisionmedicineinitiative.atlassian.net/projects/DASH1/issues/DASH1-87)]
=> [DASH1-87] Restrict realtime requests to 100 days

src/Pmi/Controller/DashboardController.php
Prior to this PR, the label for "Member" was incorrectly used. This aligns us with the new terms, outlined as:
> **Registered:** A person who created an account by entering a name and either a mobile phone number or an email address and has chosen a language preference but has not yet completed the informed consent process. A registered participant has a unique AoURP participant identifier (PID).
> **Consented:** A person who meets the eligibility and inclusion criteria and is enrolled in AoURP. A consented individual has completed the primary informed consent process and the HIPAA Authorization/EHR consent(if available and where relevant,based on AoURP capacity to effectively search for and access records). A consented individual hasn’t yet participated in any research program activities …
=> [DASH1-87] Update terminology for enrollment status

src/Pmi/Controller/DashboardController.php, views/dashboard/filters.html.twig
The old labels were ordered alphabetically for `ENROLLMENT_STATUS`, but that no longer applies with new labels. This PR refactors the code to rely on the display value order instead of an arbitrary reordering.
[[DASH1-87](https://precisionmedicineinitiative.atlassian.net/projects/DASH1/issues/DASH1-87)]
=> [DASH1-87] Fix ordering of metrics

gulpfile.js, package-lock.json, package.json, sql/healthpro/notices.sql, sql/migrations/026-create-notices.sql, src/Pmi/Application/HpoApplication.php, src/Pmi/Audit/Log.php, src/Pmi/Controller/AdminController.php, src/Pmi/EntityManager/EntityManager.php, src/Pmi/Form/NoticeType.php, src/Pmi/Service/NoticeService.php, views/admin/index.html.twig, views/admin/notices/edit.html.twig, views/admin/notices/index.html.twig, views/base.html.twig, views/full-page-notice.html.twig
[[HPRO-208](https://precisionmedicineinitiative.atlassian.net/browse/HPRO-208)]
This adds a new table for page notices and an admin section to manage these notices.  In the application's before callback middleware, notices that apply to the current page are loaded and passed to the view for rendering.  Also, a full page option is available which will just render the base template and message without executing or rendering the requested controller action.
Screenshots of an example:
=> [HPRO-208] Implement system for managing and displaying page-specific notices

views/dashboard/base.html.twig, views/dashboard/index.html.twig
- Adds the new Page Notices feature to the Dashboard base template.
- Adds a missing flash message type (not used, but should be there anyway)
- Removes deprecated `display_message()` call (replaced by Page Notices)
[[HPRO-208](https://precisionmedicineinitiative.atlassian.net/browse/HPRO-208)]
=> [HPRO-208] Add Page Notices feature to Dashboards

src/Pmi/Drc/RdrMetrics.php
This bug shows up when you have the same start and end date because internally the `DatePeriod` class does not consider that any period has elapsed between them. The fix is to append the appropriate times to the arguments, particularly the `$endDate`.
[[HPRO-458](https://precisionmedicineinitiative.atlassian.net/browse/HPRO-458)]
=> [HPRO-458] Fix DatePeriod bug when start and end dates are the same

src/Pmi/Console/Command/MetricsCommand.php, src/Pmi/Controller/DashboardController.php, views/dashboard/filters.html.twig, views/dashboard/index.html.twig, web/assets/js/dashboard.js
Adds an enrollment status filter to the `Participants by Region` tab, defaulting it show only `Core Participants` by default.
[[DASH1-82](https://precisionmedicineinitiative.atlassian.net/browse/DASH1-82)]
=> [DASH1-82] Add enrollment status filter for Region tab

src/Pmi/Controller/DashboardController.php
When viewing the `Registered` tier, the `UNSET` dot is outsized to the others, resulting in them being too small to mouse over on the map. This PR adjusts so that all dots are at least five units large.
[[DASH1-82](https://precisionmedicineinitiative.atlassian.net/browse/DASH1-82)]
=> [DASH1-82] Adjust minimum dot size on Recruitment Center Origin map

views/dashboard/base.html.twig, views/dashboard/partials/modal-dashboard-help.html.twig
This PR reduces the rather large help modal for the Dashboards to only apply to the tab route you are visiting. It also adds content for the new EHR Data tab.
[[DASH1-110](https://precisionmedicineinitiative.atlassian.net/browse/DASH1-110)]
=> [DASH1-110] Make contextual help tab-specific

src/Pmi/Controller/DashboardController.php, views/dashboard/partials/filters.html.twig, views/dashboard/participants-by-region.html.twig
> This allows the "Participant" Status to be more explicitly differentiated from "Fully Consented" as becoming a participant denotes signing the primary consent. "Fully Consented" lets users know that there is something above and beyond just signing the primary consent.
[[DASH1-134](https://precisionmedicineinitiative.atlassian.net/projects/DASH1/issues/DASH1-134)]
=> [DASH1-134] Relabel 'Consented' to 'Fully Consented'

web/assets/js/dashboard.js
@jt2k noticed this while testing something else. When the page is resized, Plotly attempts to re-render its graphs. However, our logic also tells it to stop the spinner when drawing the chart. Because there isn't a spinner to stop, the console log shows an error.
[[DASH1-138](https://precisionmedicineinitiative.atlassian.net/projects/DASH1/issues/DASH1-138)]
=> [DASH1-138] Fix console JavaScript error on page resize

src/Pmi/Controller/DashboardController.php
Ensures that we have a proper mapping for the new field as it comes in.
Note that #530 has the fix for the table showing a blank row when this is added.
[[DASH1-118](https://precisionmedicineinitiative.atlassian.net/projects/DASH1/issues/DASH1-118)]
=> [DASH1-118] Add key for 'More than one gender identity'

web/assets/js/dashboard.js
This bug fix was part of the now-reverted #530. Without it, the "More than one gender identity" row will appear without any cell values until the RDR update/backfill deploys.
[[DASH1-118](https://precisionmedicineinitiative.atlassian.net/browse/DASH1-118)]
=> [DASH1-118] Hide empty rows from dashboard table

src/Pmi/Controller/DashboardController.php, views/dashboard/ehr.html.twig
This PR remove the time-series nature of the EHR Metrics dashboard and shows only the most recent day. This is done as a workaround to some issues we have with historical tracking.
(Includes #512)
[[DASH1-110](https://precisionmedicineinitiative.atlassian.net/browse/DASH1-119)]
=> [DASH1-119] EHR Metrics > Flatten to current day

src/Pmi/Application/AbstractApplication.php, src/Pmi/Drc/RdrHelper.php, views/dashboard/partials/filters.html.twig
The prior implementation of this took the name, lowercased it, split on whitespace and then joined it back together with dashes. Trouble with that is when the name contains other characters that may trip up the selector in jQuery. This implementation abstracts that away into a custom Twig function that 'slugify's the the name a bit better, though there are still cases where an org name could trip it up. If we needed a more robust solution, I'd advise using a third-party package specialized to the task.
[[DASH1-140](https://precisionmedicineinitiative.atlassian.net/browse/DASH1-140)]
=> [DASH1-140] Fix filter toggles where name has parenthesis

src/Pmi/Console/Command/MetricsEHRCommand.php, src/Pmi/Controller/DashboardController.php, src/Pmi/Drc/RdrHelper.php, src/Pmi/Drc/RdrMetrics.php, views/dashboard/ehr.html.twig
This is the follow-on work to DASH1-124. During QA, we caught some inconsistencies in the data being returned between the ParticipantsOverTime and Organizations endpoint, most likely attributed to cache timing. There is a consolidated endpoint (by omitting the type of data the user is after) that would guarantee the two data sets would be in sync at all times. This ticket is to refactor the existing dashboard to rely on that approach.
[[DASH1-141](https://precisionmedicineinitiative.atlassian.net/browse/DASH1-141)]
=> [DASH1-141] Refactor EHR dashboard to use single endpoint

views/dashboard/partials/modal-dashboard-help.html.twig
When launching the EHR dashboard, we had some leftover help text that is no longer applicable.
[[DASH1-143](https://precisionmedicineinitiative.atlassian.net/browse/DASH1-143)]
=> [DASH1-143] Remove extraneous help copy

views/dashboard/ehr.html.twig
Goal here is to communicate to the user whether they are viewing some or all of the organizations.
[[DASH1-146](https://precisionmedicineinitiative.atlassian.net/projects/DASH1/issues/DASH1-146)]
=> [DASH1-146] Make EHR Chart Title Dynamic

src/Pmi/Controller/DashboardController.php, views/dashboard/participants-by-lifecycle.html.twig
This PR adds counts for the three retention PPI modules (as well as their aggregate full completion count) to the dashboard by way of splitting out "Baseline" and "Retention" modules into separate graphs.
[[DASH1-137](https://precisionmedicineinitiative.atlassian.net/projects/DASH1/issues/DASH1-137)]
=> [DASH1-137] Add Retention PPI modules to Lifecycle dashboard

src/Pmi/Controller/DashboardController.php
This made more sense to folks, having the latter step appearing after the "Core Participants" column. _Note: This column is empty in the test environment, but populated in stable/production._
[[DASH1-151](https://precisionmedicineinitiative.atlassian.net/browse/DASH1-151)]
=> [DASH1-151] Move Retention PPI column to end of chart

.circleci/config.yml
This was a round about way to address an issue that is blocking test runs. The error we received in the console looked something like this:
>CircleCI was unable to run the job runner because we were unable to execute commands in build container.
>
>This typically means that the build container entrypoint or command is terminating the container prematurely, or interfering with executed commands.  Consider clearing entrypoint/command values and try again.
Upon digging, we found [this issue](https://discuss.circleci.com/t/circleci-was-unable-to-run-the-job-runner/31894/17) that appears to line up with what we're experiencing. The support team has pointed out that our Docker image hasn't been updated in more than two years, a product of the migration from their Config v1 to Config v2 …
=> [HPRO-510] Fix issues with CircleCI test build process

src/Pmi/Application/AbstractApplication.php, src/Pmi/Application/HpoApplication.php, src/Pmi/Audit/Log.php, src/Pmi/Drc/RdrHelper.php, src/Pmi/Mail/Message.php, src/Pmi/Order/Mayolink/MayolinkOrder.php, src/Pmi/Security/GoogleGroupsAuthenticator.php, src/Pmi/Security/UserProvider.php, src/Pmi/Service/EvaluationsQueueService.php, src/Pmi/Service/PatientStatusService.php, src/Pmi/Util.php
[[HPRO-522](https://precisionmedicineinitiative.atlassian.net/browse/HPRO-522)]
Refactors our application logging to use [Monolog](https://github.com/Seldaek/monolog). This will make integrating StackDriver logging and other adjustments for the 2nd gen runtime easier and cleaner.
This PR enables the Monlog service provider and configures it with the SyslogHandler in a way that is equivalent to our previous logging methods (calling syslog directly throughout the application).  This also makes use of Monolog's error handler for exceptions.
=> [HPRO-522] Use Monolog for logging

composer.json, composer.lock, dev_config/config.yml.dist, src/Pmi/Application/AbstractApplication.php, src/Pmi/Audit/Log.php, src/Pmi/Monolog/StackdriverHandler.php, web/local-router.php
Well this was a fun one. Shyam did the initial work of figuring out how to write directly to Stackdriver logs using the Google Cloud Logging client. After refactoring our logs to use Monolog (#572) I was able to implement the Stackdriver integration as a Monolog handler.
This solution makes use of the Buffer handler wrapper, allowing us to delay pushing logs to Stackdriver until after the request is completed (and batches them all into one request instead of making multiple remote requests).
This handler also sets the log trace so that it can be associated with the parent App Engine request log entry.
Note that this PR is for merging the logging updates into our PHP 7.2 / App Engine 2nd gen branch
=> [HPRO-518] Add Stackdriver logging

src/Pmi/Application/AbstractApplication.php
HPRO-532
Previously, errors in retrieving or saving cache data were silently failing. By passing the logger in to the cache adapter, warnings will now be logged.
=> [HPRO-532] Enable logging for the cache component

.gitignore, docker-compose.yml, src/Pmi/Application/HpoApplication.php
HPRO-540
This change allows for environment variables to override the DB configuration when running locally and sets the necessary environment variables in the `healthpro-web` container.
As a result of this change, you will no longer need to change the local `dev_config/config.yml` file to match your Docker configuration.
=> [HPRO-540] Allow defining DB connection in docker-compose configuration

php.ini.dist
HPRO-552
Session garbage collection is currently failing due to the limit of datastore entities that can be deleted at once. This temporarily disables garbage collection on user requests. We should probably move this cleanup to a cron job anyways.
=> [HPRO-552] Disable session garbage collection

src/Pmi/Drc/RdrHelper.php, src/Pmi/Drc/RdrParticipants.php
HPRO-554
Note that the validation on participant ID only enforces word characters to avoid adding RDR business logic to HealthPro in case participant ID format changes in the future. There is no harm in checking for an alphanumeric participant ID even if it doesn't match the current `P1234...` format. We just want to prevent cache lookup errors and avoid completely unnecessary RDR requests.
In addition to the id validation, I am also catching exceptions from cache retrieval and logging so that we can gracefully fail on unexpected cache exceptions.
=> [HPRO-554] Add participant id validation before checking cache and hitting RDR

.gitignore, composer.json, composer.lock, phpunit.xml, tests/Pmi/AbstractWebTestCase.php, tests/Pmi/Drc/CodeBookTest.php, tests/Pmi/Drc/ParticipantSearchTest.php, tests/Pmi/EntityManager/EntityManagerTest.php, tests/Pmi/Evaluation/EvaluationTest.php, tests/Pmi/Order/OrderNotesIdentifierTest.php, tests/Pmi/Order/OrderTest.php, tests/Pmi/Participant/ParticipantTest.php, tests/Pmi/Security/UserTest.php, tests/Pmi/UtilTest.php
This PR updates PHPUnit to 8.5 from 4.8. With it comes several structural changes to the test suite.
- `syntaxCheck` is no longer a valid flag in `phpunit.xml`
- Several dependencies had to be updated as well to satisfy requirements
- The `Silex\WebTestCase` `setUp()` method signature was incompatible
- New version uses proper namespaces for test cases
- Ignoring a generated cached file
[HPRO-585]
[HPRO-585]: https://precisionmedicineinitiative.atlassian.net/browse/HPRO-585
=> [HPRO-585] Update to PHPUnit 8.5

.circleci/config.yml
We received an email March 16 letting us know that all projects in Circle CI would be transitioning to the new Pipelines feature. In an effort to ensure that this does not break anything in our CI/CD setup, this PR aims to address any change we need to make.
[HPRO-590]
[HPRO-590]: https://precisionmedicineinitiative.atlassian.net/browse/HPRO-590
=> [HPRO-590] Enable Circle CI Pipelines, Adjust Configuration as Needed

src/Pmi/Application/HpoApplication.php, src/Pmi/Controller/WorkQueueController.php, views/biobank/order.html.twig, views/partials/participant-orders-list.html.twig
I'm not sure if want to display participant id in the order detail page for scripps super user. We can display participant id by checking roles but when a user has both (ROLE_AWARDEE and ROLE_BIOBANK) roles the biobank non-pii view will display the participant id.
=> [HPRO-591] Make scripps/biobank order ready only view available to scripps super user

src/Pmi/Application/HpoApplication.php, src/Pmi/Console/Command/BiobankOrderCommand.php, src/Pmi/Controller/BiobankController.php, src/Pmi/Drc/RdrParticipants.php, src/Pmi/Order/Order.php, views/biobank/order-quanum.html.twig, views/biobank/order.html.twig, views/biobank/participant.html.twig, views/partials/biobank-order-details.html.twig, views/partials/participant-orders-list.html.twig
This PR introduces a means of accessing Biobank orders that did not originate in HealthPro.
```bash
bin/console pmi:biobank --origin careevolution --start_date 2019-12-01
```
[HPRO-578]
[HPRO-578]: https://precisionmedicineinitiative.atlassian.net/browse/HPRO-578
=> [HPRO-578] Enable users of the non-PII biospecimen view to look up Quest Samples

package-lock.json
Removed node_moudles files and ran `npm update` to fix this issue.
=> [HPRO-598] Update npm dependencies to address security issue with minimist (minimal/no risk to HealthPro)

src/Pmi/Controller/BiobankController.php, src/Pmi/Order/Order.php, views/biobank/orders-quanum-today.html.twig, views/biobank/orders-recent-modify.html.twig, views/biobank/orders-unfinalized.html.twig, views/biobank/orders-unlocked.html.twig, views/biobank/partials/participant-review-tabs.html.twig
Add a view of orders matching the current date from the Quest Biobank data source. Non-production deployments can use the `?days=<int>` flag for testing purposes.
Also centralized the tabs into a partial to reduce repeated code.
[HPRO-589]
[HPRO-589]: https://precisionmedicineinitiative.atlassian.net/browse/HPRO-589
=> [HPRO-589] Add 'Today's Quest Biobank Orders' Tab

Dockerfile
In HPRO-596, we added updated the local server command to use the php.ini to match the GAE configuration. This includes loading the grpc PHP extension. However, the grpc extension is not installed in the Docker container. This PR adds the install steps.
[HPRO-601]
[HPRO-601]: https://precisionmedicineinitiative.atlassian.net/browse/HPRO-601
=> [HPRO-601] Add GRPC module to Docker container

src/Pmi/Order/Order.php
There was a formatting mismatch between what the `revertOrder` method this was modeled on and what our dataset needed.
[HPRO-606]
[HPRO-606]: https://precisionmedicineinitiative.atlassian.net/browse/HPRO-606
=> [HPRO-606] Fix processed timestamps under "Process" tab in Biobank view

src/Pmi/Application/HpoApplication.php, src/Pmi/Security/User.php, src/Pmi/Security/UserProvider.php, src/Pmi/Service/UserService.php
It looks like passing whole session data from `UserProvider` class to `User` class is resulting in duplicate `SessionBagProxydata` in session. Fixed it by passing only desired session info to `User` class.
I deployed this to dev and did some testing haven’t seen any issues.
=> [HPRO-588] Fix session duplicate data issue

src/Pmi/Controller/WorkQueueController.php
This issue is we are calling session variable`$app->getSiteOrganizationId()` in `participantSummarySearch` function which is being looped while doing work queue export and causing the session start error.
=> [HPRO-614] Work queue export fails when a patient status filter is set

src/Pmi/Controller/WorkQueueController.php, src/Pmi/WorkQueue/WorkQueue.php
HPRO-610
COPE surveys have been added to the participant details tab and the work queue.
Because the new survey columns need to be added at the end of the CSV export, we can no longer just loop through the surveys for the export, which resulted in this solution that stores the "initial" set of surveys in an array and then tacks on the new surveys manually at the end.
=> [HPRO-610] Add COPE surveys

composer.json, composer.lock, symfony.lock, symfony/.env, symfony/config/bundles.php, symfony/config/packages/dev/web_profiler.yaml, symfony/config/packages/test/web_profiler.yaml, symfony/config/routes/dev/web_profiler.yaml
This PR adds the [Symfony Profiler](https://symfony.com/doc/current/profiler.html) so we can catch deprecation warnings, performance warnings, etc. for the new Symfony routes.
[HPRO-599]
[HPRO-599]: https://precisionmedicineinitiative.atlassian.net/browse/HPRO-599
=> [HPRO-599] Add Symfony profiler

web/local-router.php
We had a rule in place where we tried to load the old Silex controller (which is no longer the primary entry point) when a URL ended in certain file extensions.
[HPRO-599]
[HPRO-599]: https://precisionmedicineinitiative.atlassian.net/browse/HPRO-599
=> [HPRO-599] Fix Export CSV Routes

src/Pmi/Application/HpoApplication.php, src/Pmi/Security/GoogleGroupsAuthenticator.php, symfony/config/services.yaml, symfony/src/EventListener/ResponseListener.php, symfony/src/EventListener/ResponseSecurityHeadersTrait.php
[HPRO-625]
The main change in this PR is to simply add the `frame-ancestors 'self'` directive to our Content-Security-Policy header.
In the process, I also refactored the way we set all of these security-related headers in order to make it available in one place for both Silex and Symfony. It might be easier to review this PR by looking at each commit in order.
[HPRO-625]: https://precisionmedicineinitiative.atlassian.net/browse/HPRO-625
=> [HPRO-625] Add frame-ancestors CSP directive and add security headers to Symfony application

symfony/config/packages/dev/monolog.yaml, symfony/config/packages/prod/monolog.yaml, symfony/config/services.yaml, symfony/src/EventListener/RequestListener.php, symfony/src/EventListener/ResponseListener.php
HPRO-599
This PR adjusts the logging in Symfony a bit. It still doesn't match our Silex implementation exactly, but it is closer.
I'm taking the shortcut of just using Symfony's dev vs. prod environment and not worrying about the differences between our environments. For now, we can assume that when running locally we will be using Symfony's dev environment and when running in App Engine, it will be using the prod environment.
To that end, I'm removing the default prod.log file and relying on syslog and Stackdriver only in production. In dev, I have removed the Stackdriver handler, as we don't want this on by default. In Silex we have a local configuration option that can be used to test. To test locally in the Symfony, just add the handler temporarily back to the dev monolog …
=> [HPRO-599] Adjust Symfony logging

bin/dx, bin/symfony, symfony/config/services.yaml
HPRO-644
Accomplished this by overriding the router_listener service definition and passing in `null` for the logger.
Also added a few helper scripts into the `bin` directory.
=> [HPRO-644] Suppress router listener logs in Symfony

phpunit.xml, src/Pmi/Controller/AdminController.php, src/Pmi/Security/User.php, symfony/config/packages/security.yaml, symfony/config/routes.yaml, symfony/config/routes/dev/framework.yaml, symfony/src/Controller/NoticeController.php, symfony/src/Form/NoticeType.php, symfony/src/Service/TimezoneService.php, symfony/src/Twig/AppExtension.php, symfony/templates/base.html.twig, symfony/templates/bundles/TwigBundle/Exception/error.html.twig, symfony/templates/notice/edit.html.twig, symfony/templates/notice/index.html.twig, symfony/tests/Service/TimezoneServiceTest.php, views/admin/index.html.twig
This takes a relatively contained piece of functionality of the site (the Page Notices tool) and migrates it into the Symfony framework. Among the things to discuss:
- Maintaining routes between the two frameworks (use static mapping file?)
- Checking for permissions/security (controller vs. firewall route matching)
- Migrating form types backed by Entities
- Maintaining the two `base.html.twig` files
- Route naming conventions
- Twig globals (e.g. `app.userTimezoneDisplay`)
[HPRO-650]
[HPRO-650]: https://precisionmedicineinitiative.atlassian.net/browse/HPRO-650
=> [HPRO-650] Migrate 'Page Notices' to Symfony

phpunit.xml
As discovered in #706, the phpunit setting for `convertNoticesToExceptions` doesn't do anything if notices aren't included in the error_reporting setting. We set it to E_ALL in our runtime php.ini file, but this isn't included when running our unit tests. This PR sets the error_reporting setting using the [<ini>](https://phpunit.readthedocs.io/en/8.5/configuration.html#the-ini-element) element in our phpunit configuration file.
=> [HPRO-650] Set phpunit error reporting to E_ALL

web/assets/css/app.css
HPRO-653
Fixed the problem by making the CSS selector more specific.
=> [HPRO-653] Prevent required asterisk from displaying on radio button labels

symfony/src/Form/DeceasedReportType.php
Adjustments based on UX feedback.
- Adds help text under phone and email fields specifying how the information is used.
- Clarifies to collect date and cause of death if _offered_ instead of provided.
[HPRO-630]
=> [HPRO-630] Updates to Deceased Report Form

src/Pmi/Controller/DefaultController.php, src/Pmi/Controller/SymfonyMigrationController.php, src/Pmi/Entities/Participant.php, symfony/src/Controller/DeceasedReportsController.php, symfony/templates/deceasedreports/history.html.twig, symfony/templates/deceasedreports/new.html.twig, tests/Pmi/Participant/ParticipantTest.php, views/partials/deceased-participant-notice.html.twig, views/partials/participant-notice.html.twig, views/participant.html.twig
Adds page alerts when a Participant has been flagged as deceased. Adds a history view that allows the user to see a log of Deceased Participant Report submissions.
TODO:
[HPRO-681]
[HPRO-681]: https://precisionmedicineinitiative.atlassian.net/browse/HPRO-681
=> [HPRO-681] Deceased Reports > Participant Summary Updates

src/Pmi/Controller/WorkQueueController.php
Typo led to the ~defeault~ default case not being activated.
[HPRO-630]
=> [BUG][HPRO-630] Ensure '0' appears in column for non-deceased participants

src/Pmi/Controller/DefaultController.php, src/Pmi/Entities/Participant.php
Leverages our `editExistingOnly` calculated field to prevent new submissions while allowing the viewing of old ones.
[HPRO-630]
=> [HPRO-630] Allow viewing of prior PM&B for deceased participants

src/Pmi/Controller/WorkQueueController.php, symfony/src/Controller/DeceasedReportsController.php, views/participant.html.twig
This PR removes the cog icon on the Participant Summary page for deactivated and withdrawn participants. It also adds logic that prevents new Deceased Reports from being created for those participants.
Additionally, it fixes a bug where the Deactivated filter would not work in the Work Queue because of a restriction on combining it with Deceased Status.
[HPRO-687]
[HPRO-687]: https://precisionmedicineinitiative.atlassian.net/browse/HPRO-687
=> [HPRO-687] Disable deceased reporting for withdrawn/deactivated participants

symfony/templates/base.html.twig, views/base.html.twig, web/assets/css/app.css
HPRO-671
Previously, we had the logo image (and before the logo image, the star icon) in it's own `a.nav-brand` element and the word link in another `a.nav-brand`. The Bootstrap navbar was not intended to have multiple `.nav-brand` elements, which led to the extra left padding/margin when the navbar was collapsed.
I fixed this by combining the logo image and the "HealthPro" text into the same `a.nav-brand` element. I then adjusted the image alignment and margin to display correctly.
Note that the resulting space between the logo and word is now slightly less than the previous non-collapsed spacing. This is intentional, as I decided this looked better.
**Before**:  
**After**:
=> [HPRO-671] Fix unintended extra spacing between logo and text link when navbar is collapsed

src/Pmi/WorkQueue/WorkQueue.php
- Removes dash between label and date.
- Capitalizes "Pending Acceptance"
[HPRO-691]
[HPRO-691]: https://precisionmedicineinitiative.atlassian.net/browse/HPRO-691
=> [HPRO-691] Deceased Participants > Update Activity Status Label in WQ

README.md, package.json, src/Pmi/Console/Command/DeployCommand.php
This brings the project in line with the default recipe from the Webpack Encore project. Has the added benefit of abstracting the command away from the underlying build process should we need to change it in the future.
- Adds `npm-scripts` entries for `build`, `watch`, `dev` and `dev-server`
- Adjusts deploy scripts to leverage `build`
[HPRO-695]
[HPRO-695]: https://precisionmedicineinitiative.atlassian.net/browse/HPRO-695
=> [HPRO-695] Javascript asset compile process improvements

views/participants-list.html.twig
Basic status column in the participant search results page when searched using last name and dob is displaying a green check mark for participants who's basic status in not submitted. This PR fixes basic status column.
Old:
New:
=> [HPRO-709] Fix basic status field in the participant lookup results page

README.md
During our conversion to the second generation runtime for App Engine, we lost the composer `post-install-cmd` stanzy because it prevented deployments (doesn't mesh well with their Cloud Deploy tool). As a result, we no longer have a way of ensuring that a developer has installed the `git-secrets` utiliity that scans for potentially leaked credentials prior to commit. This PR updates the README to include instructions to run the helper script manually.
[HPRO-699]
[HPRO-699]: https://precisionmedicineinitiative.atlassian.net/browse/HPRO-699
=> [HPRO-699] Update README for credential scanning

symfony/src/Service/RdrApiService.php
Wires in the cache layer so that each request doesn't regenerate an access token.
[HPRO-706]
[HPRO-706]: https://precisionmedicineinitiative.atlassian.net/browse/HPRO-706
=> [HPRO-706] Add OAuth caching to new RdrApiService class

views/participant.html.twig, views/workqueue/participant.html.twig
Prior to this PR, we would execute the JsBarCode generation script on the participant view without ensuring that the barcode was actually to be displayed. This caused a console error, but did not affect site operation. This PR adds a sanity check before generating the barcode.
[HPRO-651]
[HPRO-651]: https://precisionmedicineinitiative.atlassian.net/browse/HPRO-651
=> [HPRO-651] Ensure barcode container exists before generating

package-lock.json
HPRO-714
Ran `npm audit fix` which updated `adjust-sourcemap-loader` to a version that no longer uses `object-path`.
=> [HPRO-714] Remove object-path dependency

symfony/src/Service/RdrApiService.php
Reverts all-of-us/healthpro#764
We're seeing some interplay between the Symfony and Silex versions of this that may be causing the incorrect token to be cached, resulting in `HTTP/401` errors in certain circumstances on the Symfony side. Until that can be looked into, this should come out as a hotfix.
=> Revert "[HPRO-706] Add OAuth caching to new RdrApiService class"

src/Pmi/Order/Order.php, views/biobank/order-quanum.html.twig, views/biobank/order.html.twig, views/macros/display-text.html.twig
HPRO-634
Adds the address and adjusts the column layout.
Also adds the missing `biobank_finalized` field in the method that maps the RDR order response to mimic our local order object (this was throwing a warning).
=> [HPRO-634] Add collection site address to Quest orders

src/Pmi/Entities/Participant.php, tests/Pmi/Participant/ParticipantTest.php, views/participant.html.twig
The hierarchy for activity status has been reorganized, and as a result this PR refactors the logic for returning the correct string.
The priority for these should be:
1. Withdrawn
1. Deactivated
1. Deceased
[HPRO-721]
[HPRO-721]: https://precisionmedicineinitiative.atlassian.net/browse/HPRO-721
=> [HPRO-721] Refactor Participant::getActivityStatus

.circleci/config.yml, Dockerfile, app.yaml.dist, ci/test.sh, composer.json, composer.lock, symfony.lock, tests/Pmi/UtilTest.php
HPRO-726
This upgrades our Docker image, Circle CI build, and Google App Engine runtime to PHP 7.3.
To build the new docker image, run:
```sh
docker-compose build web
docker-compose up -d
```
(Note that rebuilding the web image will take a while.)
I updated the `config.platform.php` value to `7.3.21` in our composer.json file. I deployed a temporary phpinfo page to dev to determine the exact version currently running in the GAE standardy php73 runtime, which was 7.3.21. This will ensure that we won't run into any issues with dependencies requiring a specific minor version as we know for sure that GAE, Circle, and Docker will all be running 7.3.21 or higher.
Now that we are on PHP 7.3, I also upgraded PHPUnit to 9.2 and replaced a deprecated assertion (`assertRegExp` -> …
=> [HPRO-726] Upgrade to PHP 7.3 and PHPUnit 9.2

symfony/src/Controller/DeceasedReportsController.php, symfony/src/Service/RdrApiService.php
Ran into some trouble with the last roll-out of this. This PR aims to address those issues.
- Use the `rdr_auth_json` if present
- Do not useApplicationDefaultCredentials in that scenario
- Streamline cache usage in `DeceasedReportsController`
[HPRO-706]
[HPRO-706]: https://precisionmedicineinitiative.atlassian.net/browse/HPRO-706
=> [HPRO-706] OAuth Caching for RdrApiService

.github/PULL_REQUEST_TEMPLATE.md
| ------------------- | -------
| Target Release?     | Next available
| Bug fix?            | ❌
| New feature?        | ❌
| Database migration? | ❌
| New configuration?  | ❌
| Composer updates?   | ❌
| Jira Tickets        | HPRO-733
This is a non-user facing change that adds a suggested template when opening a PR through the web interface (or when using the official `gh` command line tool). The idea is partially stolen from `symfony/symfony`.
Is there any additional information we might want to capture or share?
=> [HPRO-733] Adds Pull Request template

symfony/src/Service/SiteSyncService.php
| Target Release?     | 2.3.8
| Jira Ticket(s)      | HPRO-717 
- This fixes mayo account number sync in stable
- Set `emsicentralregion` site mayo account number to 7035500.
- Change `isStable` to `isLocal` to allow mayo account number sync in local env
- The new column in the site sync preview should display hpo account number 7037059
=> [HPRO-717] Fix mayo account sync issue in stable

views/participants-list.html.twig
| Target Release?     | 2.4.0
| Bug fix?            | ❌
| Database migration? | ❌
| New configuration?  | ❌
| Composer updates?   | ❌
| Jira Ticket(s)      | HPRO-746
* Adds deceased and deactivated badges to the participant list
* Changes "Basics Complete" status to whether or not the participant's status allows for creating new in-person enrollment data
Perform participant lookup searches against RDR Test
Last Name: **UpdatedLastName**
DOB: **10/10/1902**
Last name: **Overton**  
DOB: **11/05/1970**
Last name: **Web**  
DOB: **02/02/1990**
=> [HPRO-746] Update participant lookup results page

src/Pmi/Controller/WorkQueueController.php, src/Pmi/WorkQueue/WorkQueue.php
| Target Release?     | 2.4.0 
| Jira Ticket(s)      | HPRO-750 
Following are the changes that's included in this PR:
- Add Cope survey fields in the WQ export
- Remove Jan Cope survey field from WQ and WQ export
- Rename survey label "Health Access" to "Health"
=> [HPRO-750] [HPRO-723] [HPRO-521] Fixes and changes

src/Pmi/WorkQueue/WorkQueue.php
| Target Release?     | 2.4.0.2 
| Jira Ticket(s)      | HPRO-762
I am unable to find a participant who's questionnaire survey status is `UNSET` OR `SUBMITTED_NO_CONSENT`. So, for testing add `$rdrParticipant->questionnaireOnCopeDecAuthored = '2020-12-17T11:50:52';` in line [62](https://github.com/all-of-us/healthpro/blob/develop/src/Pmi/Entities/Participant.php#L62) and remove when done.
=> [HPRO-762] Always display date for survey fields if exists

src/Pmi/Controller/SymfonyMigrationController.php
| Target Release?     | 2.4.2 
| Jira Ticket(s)      | HPRO-749 
This PR fixes a bug where the interplay between Silex and Symfony requires a trailing slash.
=> [HPRO-79] Fix redirect by including forward slash

dev_config/config.yml.dist, src/Pmi/Application/HpoApplication.php, src/Pmi/Drc/AppsClient.php, src/Pmi/Drc/MockAppsClient.php, src/Pmi/Security/User.php, src/Pmi/Security/UserProvider.php, src/Pmi/Service/UserService.php, symfony/src/Security/UserProvider.php
| New configuration?  | ✅ 
| Jira Ticket(s)      | HPRO-768 
Adds new `ROLE_MANAGE_USERS` role based on the user's role in the Google Group for the current site. This role is not yet used, but paves the way for implementing the new user management features.
Currently, this is behind a feature flag to avoid unnecessary API calls in production.
`dev_config/config.yml`:
* Enable `feature.manageusers` feature flag
* Disable `gaBypass`
Log in with an actual @pmi-ops.org account.
From any Symfony route, you can use the dev toolbar to check your user's roles. …
=> [HPRO-768] Add user management role based on Google Group role

src/Pmi/Controller/WorkQueueController.php, src/Pmi/Drc/CodeBook.php, src/Pmi/Entities/Participant.php, src/Pmi/WorkQueue/WorkQueue.php, symfony/src/Helper/Participant.php, symfony/templates/partials/participant-dl.html.twig, views/partials/participant-dl.html.twig
| Target Release?     | 2.4.3 
| Jira Ticket(s)      | HPRO-777 
I didn't find any participants having `CORE_MINUS_PM` in dev env. For testing, manually add below code in Participant class for both [Silex](https://github.com/all-of-us/healthpro/blob/develop/src/Pmi/Entities/Participant.php#L62) and [Symfony](https://github.com/all-of-us/healthpro/blob/develop/symfony/src/Helper/Participant.php#L63)
`$rdrParticipant->enrollmentStatus = 'CORE_MINUS_PM';`
`$rdrParticipant->enrollmentStatusCoreMinusPMTime = '2020-11-16T18:52:58';`
=> [HPRO-777] Add Core Minus PM Enrollment Status

symfony/src/Service/OrderService.php
| Jira Ticket(s)      | HPRO-784 
This fixes updating `rdr_id` field in the orders table when we get 409 response from RDR
=> [HPRO-784] Fix undefined getMayoId method call

src/Pmi/Controller/EvaluationController.php, symfony/src/Controller/OrderController.php
| Jira Ticket(s)      | HPRO-779 
Allows a user to access specific debug tools that were previously only available in the local development enviroment. It checks whether the user has admin access.
=> [HPRO-779] Enable PMs and Orders JSON endpoint

web/assets/js/views/PhysicalEvaluation-0.3-ehr.js, web/assets/js/views/PhysicalEvaluation-0.3.js
| Target Release?     | 2.4.6
| Jira Ticket(s)      | PD-6032
1. Disables corresponding input fields when pandemic protocol modification is selected
2. For height/weight protocol modification selects wheelchair/pregnant protocol modification if applicable when toggling back to in-person measurement source
=> Release 2.4.6 bug fixes

src/Pmi/Evaluation/Evaluation.php, web/assets/js/views/PhysicalEvaluation-0.3-ehr.js
| Target Release?     | 2.4.6 
| Jira Ticket(s)      | PD-6302
1. This PR prevents enabling first reading fields when the form is locked (finalized)
=> Release 2.4.6 Bug Fixes - 2

symfony/src/Service/OrderService.php
| Jira Ticket(s)      | HPRO-814 
This fixes 500 RDR error when the order from the careevolution doesn't have kit id in the identifiers
=> [HPRO-814] Fix kit id identifier issue

symfony/src/Controller/SitesController.php, symfony/templates/admin/sites/sync.html.twig
| Jira Ticket(s)      | HPRO-811 
Trivial fix to align the flash messages for the Sites management tool (were inadvertently left as the ones for Page Notices).
=> [HPRO-811] Adjust flash messages on Sites admin

bin/phpunit, ci/test.sh
| Jira Ticket(s)      | HPRO-819 
We have a "Tests" tab in Circle CI that wasn't showing anything because PHPUnit wasn't set up to generate a log file. This PR adjusts our test script to write it out.
=> [HPRO-819] Log test output using JUnit XML format for CircleCI

sql/healthpro/users.sql, sql/migrations/043-alter-user-table-add-last-login.sql, src/Pmi/Security/GoogleGroupsAuthenticator.php, src/Pmi/Security/User.php, src/Pmi/Service/UserService.php, symfony/src/Entity/User.php, symfony/src/EventListener/RequestListener.php, symfony/src/Security/GoogleGroupsAuthenticator.php, symfony/src/Service/UserService.php
| Jira Ticket(s)      | HPRO-801 
We would like to record when a user last logged in to the platform. This data is already available in logs, but this would put it a bit more in reach for easier reporting. I updated on both the Silex and Symfony side, though I don't think we've got a pathway to run it on the Symfony side yet.
- Be sure to run the migrations
- Log in as a test user
- Observe that the `last_login` column has been updated in MySQL
=> [HPRO-801] Record last login for user

symfony/src/Service/WorkQueueService.php
| Jira Ticket(s)      | HPRO-729
=> [HPRO-729]  Warning is thrown in Work Queue when reading patient status that is not iterable

php.ini.dist
| Jira Ticket(s)      | HPRO-812 
In #868, I made the assumption that "Strict" was the best option for the SameSite cookie setting. Upon some additional research, the more important thing is that the flag is both set and that it is consistent. The actual reported issue summary reads:
>- Cookie without SameSite attribute.When cookies lack the SameSite attribute, Web browsers may apply different and sometimes unexpected defaults. It is thereforerecommended to add a SameSite attribute with an appropriate value of either "Strict", …
=> [HPRO-812] Set SameSite Cookie

docker-compose.yml
| Jira Ticket(s)      | HPRO-829 
In some circumstances, stopping our development Docker containers or running `docker compose down` will destroy the existing database data, prompting it to be rebuilt on a subsequent run. This PR attaches a volume to persist the database.
1. Back up any specific test cases you would like to keep
1. Run `docker compose down` to clean up existing containers
1. Run `docker compose up` or `docker compose up -d` to create the volume
1. Use Docker as usual
Note: If you do not do these steps, there …
=> [HPRO-829] Persist MySQL data between Docker runs

symfony/templates/admin/base.html.twig, symfony/templates/admin/debug/missing-measurements.html.twig, symfony/templates/admin/debug/missing-orders.html.twig, symfony/templates/admin/debug/participant.html.twig, symfony/templates/admin/debug/participants.html.twig, symfony/templates/admin/index.html.twig, symfony/templates/admin/notifications.html.twig, symfony/templates/admin/sites/edit.html.twig, symfony/templates/admin/sites/index.html.twig, symfony/templates/admin/sites/sync.html.twig, symfony/templates/base.html.twig, symfony/templates/biobank/base.html.twig, symfony/templates/biobank/index.html.twig, symfony/templates/biobank/order-quanum.html.twig, symfony/templates/biobank/order.html.twig, symfony/templates/biobank/orders-quanum-today.html.twig, symfony/templates/biobank/orders-recent-modify.html.twig, symfony/templates/biobank/orders-today.html.twig, symfony/templates/biobank/orders-unfinalized.html.twig, symfony/templates/biobank/orders-unlocked.html.twig, symfony/templates/biobank/orders.html.twig, symfony/templates/biobank/participant.html.twig, symfony/templates/biobank/participants.html.twig, symfony/templates/macros/display-text.html.twig, symfony/templates/problem/problem-details.html.twig, symfony/templates/problem/problem-reports.html.twig, views/base.html.twig, web/assets/css/app.css
| Jira Ticket(s)      | HPRO-519 
Previously, our navbar has links to specific pages for regular site and awardee users, and then links to home pages for other roles (like admin, dashboard, biobank, etc.)
This PR replaces the main HealthPro home page link with a dropdown when a user has access to more than one role. Note that this frees up space in the navbar so in the future, we could add navbar links for different roles (like sites, page notices, etc. when in the admin context) but that is outside the scope of this PR.
I …
=> [HPRO-519] Add role selector to navbar

symfony/src/Form/MeasurementType.php, web/assets/js/views/PhysicalEvaluation-0.3-ehr.js
| Jira Ticket(s)      | HPRO-865 
Limits the user's ability to select a date in the future or more than six months in the past when completing a physical measurement that relies on EHR data rather than one collected at the point of service.
The test participant must be one that can 1) accept new physical measurements and 2) be paired to a site where the `ehr_modification_protocol` flag is set to `1`.
In the screenshots below, invalid dates are greyed out and are unable to be selected nor manually entered.
=> [HPRO-865] Restrict EHR PM date selector to prior six months

src/Pmi/Application/HpoApplication.php, symfony/config/packages/twig.php, symfony/src/Service/HelpService.php, symfony/templates/base.html.twig, symfony/templates/help/index.html.twig, views/base.html.twig
| Jira Ticket(s)      | HPRO-8788 
This PR links the REDCap form for collecting user feedback for the HealthPro application in two places:
- Drop down menu in upper right
- As a button on the Help and Training Resources page
Notable is the requirement that the link display the External Site warning pop-up before continuing on in a new tab.
=> [HPRO-878] Add Feedback Links

symfony/templates/login.html.twig, web/assets/css/login.css
| Target Release?     | 2.6.0
| Jira Ticket(s)      | HPRO-882 
Increasing the vertical height of the white "action" box on the login landing page based on feedback.
=> [HPRO-882] Increase size of action box on login page

src/Pmi/Drc/CodeBook.php, symfony/src/Helper/Participant.php, symfony/src/Helper/WorkQueue.php
| Jira Ticket(s)      | HPRO-833 
Looks like `digitalHealthSharingStatus` field values are returned as an stdClass object instead of json string.
Below is the participant which is tied to awardee `AZ_TUCSON` for testing in WQ
Participant Id: P741896610
=> [HPRO-833] Fix digital health sharing status field parse error

web/assets/js/views/PhysicalEvaluation-0.3-ehr.js
| Jira Ticket(s)      | HPRO-906 
Only run `.pmiDateTimePicker()` against non-finalized orders.
=> [HPRO-906] Preserve previously set date

symfony/src/Helper/WorkQueue.php
| Jira Ticket(s)      | HPRO-912
=> [HPRO-912] Return null for digital health sharing date fields when status is not set

symfony/templates/index.html.twig
| Jira Ticket(s)      | HPRO-910 
When a user lacks `ROLE_USER`, we were still calling the `/s/deceased-reports/stats` endpoint to get a badge count, resulting in a HTTP 403 error appearing in the logs. This PR wraps the AJAX request in a check of whether the relevant block appears on the page.
=> [HPRO-910] Deceased > Check for `ROLE_USER` before making AJAX request

composer.json, composer.lock, symfony.lock, symfony/src/Controller/CronController.php, symfony/tests/Controller/CronControllerTest.php
| Jira Ticket(s)      | HPRO-917 
Adjusts routing rules around `/s/cron` endpoints.
Provide the `X-Appengine-Cron: true` header when interacting with the endpoints. Omitting it will return a 404 error.
Example:
```
$ curl -H 'X-Appengine-Cron: true' http://localhost:8080/s/cron/ping-test
```
=> [HPRO-917] Adjust routing rules for `/s/cron` endpoints

symfony/src/Controller/DefaultController.php, symfony/src/Service/LoggerService.php
| Jira Ticket(s)      | HPRO-895 
Looking to collect some more context around the HTTP 403 errors we're seeing for certain users where the CSRF token doesn't match the submitted value.
=> [HPRO-895] Add debug logs to keepalive CSRF token mismatch

symfony/config/routes.yaml, symfony/src/Controller/AuthController.php, symfony/src/Controller/DefaultController.php, symfony/src/Controller/HomeRedirectController.php, symfony/src/Security/GoogleGroupsAuthenticator.php, symfony/src/Service/AuthService.php, symfony/templates/accessmanagement/add-member.html.twig, symfony/templates/accessmanagement/dashboard.html.twig, symfony/templates/accessmanagement/group-members.html.twig, symfony/templates/accessmanagement/groups.html.twig, symfony/templates/accessmanagement/remove-member.html.twig, symfony/templates/timeout.html.twig
Fixes issue with absolute URL being generated for location header when using the Symfony built-in RedirectController
| Target Release?     | 2.6.3 
| Jira Ticket(s)      | HPRO-851 
I had originally used the Symfony built-in RedirectController to accomplish two things:
1. Maintain the existing use of the named `home` route
2. Redirect `/` to `/s/`
This created a problem when behind the WAF because the RedirectController [generates an absolute URL](https://github.com/symfony/symfony/blob/4.4/src/Symfony/Bundle/FrameworkBundle/Controller/RedirectController.php#L88). …
=> [HPRO-851] Fix absolute URL redirect

dev_config/migrations-db.php
| Jira Ticket(s)      | HPRO-943 
Ran into trouble with reading from `$_ENV` in the configuration file. The value was available in `$_SERVER` and using `getenv()`. I suspect some of the globals may be cleaned up a bit to only those defined in a `.env` file. Also addresses a constant casing issue.
=> [HPRO-943] Fix Doctrine Migration environment variable reading

templates/partials/workqueue-consents-columns.html.twig
| Jira Ticket(s)      | HPRO-928 
This `data-consent-columns-url` got removed when the UI is changed [Line](https://github.com/all-of-us/healthpro/pull/984/files#diff-c0451496feed1f82f1e34f692bf7774d2707e73c9f67b501a6b2521c0b241b68L11)
=> [HPRO-928] Fix column check/uncheck url

.circleci/config.yml, .gitignore, ci/phpstan.sh, phpstan-baseline.neon, src/Controller/MeasurementsController.php
| Jira Ticket(s)      | HPRO-935 
Wires in PHPStan to our Circle CI runs.
=> [HPRO-935] Add PHPStan to Circle CI

src/Command/SyncSiteEmailsCommand.php, src/Controller/AccessManagementController.php, src/Controller/SitesController.php, src/Service/GoogleGroupsService.php, src/Service/SiteSyncService.php
| Jira Ticket(s)      | HPRO-965 
As currently written, our application treats any error from the Google Groups API "getMembers" call as an empty response. This could cause empty data to be written to the `sites.email` field. This PR handles the exception at the controller level, preventing invalid data from being written to the table.
=> [HPRO-965] Ensure Google Groups error not handled as empty response

src/Helper/WorkQueue.php, src/Service/WorkQueueService.php
| Jira Ticket(s)      | HPRO-963 
The Genetic Return of Results (gRoR) column should use the `displayConsentStatus` method for rendering so that it can pick up the PDF link if available.
=> [HPRO-963] Adjust gRoR column to link to PDF consent

src/Command/SyncSiteEmailsCommand.php, src/Service/SiteSyncService.php
| Jira Ticket(s)      | HPRO-914 
This PR prevents extraneous log entries when the site admin emails are identical to the previous value.
=> [HPRO-914] Log only if site admin emails change

src/Helper/WorkQueue.php, src/Service/WorkQueueService.php
| Target Release?     | 2.6.7 
| Jira Ticket(s)      | HPRO-963 
This restores the previous static method that had a slightly different set of icons while adding the capability to link content as requested.
=> [HPRO-963] Revert to use prior Genomics Consent Status icons

cron.yaml.dist
| Jira Ticket(s)      | HPRO-914 
The existing cron job path works as-is because of our redirect setup, but we can remove an extra hop.
=> [HPRO-914] Update cron path for email sync job

Dockerfile
Co-Authored-By: Jason Tan <860499+jt2k@users.noreply.github.com>
| Jira Ticket(s)      | HPRO-980
Upgrade gcloud sdk to support python3
=> [HPRO-980] Update Docker image with the latest gcloud version and python 3 support

src/Entity/Order.php, templates/biobank/orders-quanum-today.html.twig, templates/biobank/orders-recent-modify.html.twig, templates/biobank/orders-today.html.twig, templates/biobank/orders-unfinalized.html.twig, templates/biobank/orders-unlocked.html.twig, templates/order/print-requisition.html.twig, templates/partials/participant-orders-list.html.twig, tests/Entity/OrderTest.php
| Jira Ticket(s)      | HPRO-1020
=> [HPRO-1020] Display the type of biobank order created on the in-person enrollment tab order overview. (Blood, Urine, Saliva)

composer.json, phpstan.neon.dist, src/Controller/OrderController.php, src/Controller/PatientStatusController.php, src/Controller/ProblemController.php, src/Entity/Order.php, src/Entity/PatientStatusImport.php, src/Helper/WorkQueue.php, src/Security/GoogleGroupsAuthenticator.php, src/Service/OrderService.php, src/Service/SiteSyncService.php
| Target Release?     | 0.0.0
| Jira Ticket(s)      | HPRO-1089 
This PR completes the PHPStan level 2 fixes, updates the PHPStan config to run level 2, and adds `ext-json` to the `composer.json` file because PHPStorm was complaining about it.
=> [HPRO-1089] PHPStan level 2: Part III

composer.json, phpstan.neon.dist, src/Command/ReleaseTicketCommand.php, src/Controller/DeceasedReportsController.php, src/Controller/OrderController.php, src/Controller/PatientStatusController.php, src/Controller/ProblemController.php, src/Entity/Measurement.php, src/Entity/Order.php, src/Entity/PatientStatusImport.php, src/Helper/Util.php, src/Helper/WorkQueue.php, src/Model/Measurement/Fhir.php, src/Security/GoogleGroupsAuthenticator.php, src/Service/DeceasedReportsService.php, src/Service/OrderService.php, src/Service/SiteSyncService.php, src/Util.php
| Bug fix?            | ❌
| Jira Ticket(s)      | HPRO-1089 
This PR expands on the previous PHPStan fixes by addressing a few other issues NOT related to the `getUser` errors.
=> [HPRO-1089] PHPStan level 2: Part II

templates/accessmanagement/add-member.html.twig, templates/accessmanagement/remove-member.html.twig, templates/measurement/modify.html.twig, templates/order/modify.html.twig
| Jira Ticket(s)      | HPRO-1024 
Reversed placement of some submit/cancel buttons to match placement in other places in healthpro.
=> [HPRO-1024] Reversed placement of some submit/cancel buttons

src/Service/ContextTemplateService.php, src/Twig/ContextLoaderExtension.php, templates/base-head.html.twig, tests/Service/ContextTemplateServiceTest.php, web/assets/css/hpo.css, web/assets/css/nph.css
| Jira Ticket(s)      | HPRO-1227 
small service that adds a function to build an include string that changes the file to be loaded based upon a users selected program.
=> [HPRO-1227] Asset loader for site specific templates

src/Controller/NphOrderController.php, src/Form/Nph/NphOrderType.php, src/Repository/NphOrderRepository.php, src/Service/Nph/NphOrderService.php, templates/program/nph/order/generate-orders.html.twig, templates/program/nph/order/partials/generate-orders-header.html.twig, templates/program/nph/order/samples.html.twig
| Jira Ticket(s)      | HPRO-1274
=> [HPRO-1274] Display and disable existing orders & samples

Dockerfile
Symfony appears to have changed the way they distribute their binary since the last time the dockerfile was updated. They now appear to be appending a version number to where it extracts.
| Jira Ticket(s)      | HPRO-1197
=> [HPRO-1197] Updated Dockerfile - Symfony Fix

src/Controller/NphPDFController.php, src/Service/PDFService.php, templates/program/nph/order/label-print.html.twig, templates/program/nph/pdf/biospecimen-label.html.twig
| Jira Ticket(s)      | HPRO-1294 
Only print one PDF for the stool kit, also moved DOB back up to top. Maximum 20 characters for name, abbreviated first name if over 20 characters. Stool label identifier should also be "ST KIT" as opposed to its normal identifier.
=> [HPRO-1294] Change pdf label generation based on feedback, stool specific changes.

src/Service/EnvironmentService.php, src/Service/TimezoneService.php
| Jira Ticket(s)      | HPRO-1330
=> [HPRO-1330] Move Atlantic standard time option above eastern time

templates/program/nph/participant/index.html.twig
| Jira Ticket(s)      | HPRO-1331
=> [HPRO-1331] Display proper status for sample collection state, partial collections.

templates/program/nph/review/recently_modified.html.twig
=> [HPRO-1182] Added fix for spelling mistake on restore samples.

src/Controller/OrderController.php, src/Entity/Order.php, src/Form/OrderType.php, src/Service/OrderService.php, templates/order/finalize.html.twig, tests/Entity/OrderTest.php
| Jira Ticket(s)      | HPRO-1356
=> [HPRO-1356] Add Fedex Tracking field to HPO order workflow

src/Controller/NphParticipantSummaryController.php, src/Entity/NphOrder.php, src/Entity/NphSample.php, src/Repository/NphOrderRepository.php, src/Service/Nph/NphOrderService.php, src/Service/Nph/NphProgramSummaryService.php, templates/program/nph/participant/index.html.twig, tests/Entity/NphOrderTest.php, tests/Service/NphOrderServiceTest.php
| Bug fix?            | ✅/❌ 
| New feature?        | ✅/❌ 
| Database migration? | ✅/❌ 
| New configuration?  | ✅/❌ 
| Composer updates?   | ✅/❌ 
| NPM updates?        | ✅/❌ 
| Jira Ticket(s)      | HPRO-1385
=> [HPRO-1385] Show multiple samples status per order

src/Form/Nph/NphSampleFinalizeType.php
| Jira Ticket(s)      | HPRO-1374 
Added messages to tell user maximum volume for aliquot
=> [HPRO-1374] Added extra messages for 500 and 1000 volume aliquots.

src/Controller/NphOrderController.php, src/Entity/NphOrder.php, src/Form/Nph/NphSampleModifyType.php, src/Repository/NphSampleRepository.php, templates/program/nph/order/collect.html.twig, templates/program/nph/order/sample-modify.html.twig, web/assets/css/nph.css
| Target Release?     | 3.2.0
| Jira Ticket(s)      | HPRO-1387
=> [HPRO-1387] Only allow restore of samples without active samples.

src/Repository/NphOrderRepository.php, templates/program/nph/review/recently_modified.html.twig
| Jira Ticket(s)      | HPRO-1388 
Changes references to constants and removes cancelled orders from the unfinalized view.
=> [HPRO-1388] Fix for unknown constants, don't display cancelled orders in unfinalized

templates/program/nph/order/sample-finalize.html.twig
| Jira Ticket(s)      | HPRO-1396
=> [HPRO-1396] Fix aliquot time field width in sample finalize page

templates/program/nph/order/sample-finalize.html.twig
| Jira Ticket(s)      | HPRO-1411
=> [HPRO-1411] Prevent finalized button from clicking when the form is disabled

src/Service/Nph/NphOrderService.php, src/Service/Nph/NphProgramSummaryService.php, src/Service/PDFService.php, templates/program/nph/order/label-print.html.twig, templates/program/nph/participant/index.html.twig, tests/Service/NphOrderServiceTest.php
Missed File.
| Jira Ticket(s)      | HPRO-1409
=> [HPRO-1409] Display all old orders, even cancelled. Display cancelled status text.

migrations/Version20230406141013.php
| Target Release?     | 3.4.0 
| Jira Ticket(s)      | HPRO-1426
Fixing sort for 180 timepoint on participant Review.
=> [HPRO-1426] Migration to update sort order for 180 timepoint.

templates/program/nph/review/recently_modified.html.twig, templates/program/nph/review/unfinalized.html.twig
| Jira Ticket(s)      | HPRO-1479
The route for the participant review pages were incorrectly pointed to AOU participant pages instead of NPH ones.
=> [HPRO-1479] Changed Route to correct NPH route.

migrations/Version20230519135344.php, src/Controller/NphBiobankController.php, src/Controller/NphOrderController.php, src/Entity/NphOrder.php, src/Entity/NphSample.php, src/Service/Nph/NphOrderService.php, templates/program/nph/biobank/order-collect-details.html.twig, templates/program/nph/order/collect.html.twig, templates/program/nph/order/macros/display-text.html.twig, templates/program/nph/order/sample-finalize.html.twig, tests/Entity/NphOrderTest.php, tests/Service/NphOrderServiceTest.php, web/assets/css/nph.css
| Jira Ticket(s)      | HPRO-1419 
Biobank view shows the same aliquot page as any other user, allows finalizing of only stool samples. All other samples are disabled and read only.
=> [HPRO-1419] Biobank aliquot page

web/assets/js/views/NphSampleFinalize.js
| Jira Ticket(s)      | HPRO-1592 
Adds a fix for aliquot time not populating after using the eraser icon.
=> [HPRO-1592] Fix for date time not populating.

templates/program/nph/order/partials/sample-finalize-participant-details.html.twig
| New configuration?  | ✅ 
| Jira Ticket(s)      | HPRO-1566
=> [HPRO-1566] Add links to participant name and order id in aliquot page

src/Order/versions/3.1-ped-16.4.json, src/Order/versions/3.1-ped-2.5.json, src/Order/versions/3.1-ped-5.json, src/Order/versions/3.1-ped-9999.json, tests/Helper/ParticipantTest.php
| Jira Ticket(s)      | HPRO-1655 
Temporarily removing 2ED04 sample until biobank resolves an issue with multiple 2ED samples on order generation.
=> [HPRO-1655] Temporarily removed 2ED04 sample, updated test to better test weight breakpoints.

src/Order/versions/3.1-ped-16.4.json, src/Order/versions/3.1-ped-2.5.json, src/Order/versions/3.1-ped-5.json, src/Order/versions/3.1-ped-9999.json
| Jira Ticket(s)      | HPRO-1686, HPRO-1683 
Updates sample identifiers according to new ticket (HPRO-1686). Also resolves issue of Urine samples requesting two labels.
=> [HPRO-1686][HPRO-1683]Change sample identifiers according to new request.

src/Repository/MeasurementRepository.php
| Jira Ticket(s)      | HPRO-1696 
Fixes an issue where safety check would load amended physical measurements parent's whenever the child physical measurement was unfinalized..
=> [HPRO-1696] Don't allow amended measurements in safety check.

src/Form/Nph/NphOrderForm.php, templates/program/nph/order/partials/order-collect-urine24.html.twig, templates/program/nph/order/sample-finalize.html.twig
| Target Release?     |Next available 
| Jira Ticket(s)      | HPRO-1654
=> [HPRO-1654] Move errors outside form group, check 0 before null

templates/partials/participant-measurement-summary.html.twig
| Jira Ticket(s)      | HPRO-1754
=> [HPRO-1754] Add head circumference growth percentiles to summary view

templates/partials/participant-dl-bs5.html.twig
| Jira Ticket(s)      | HPRO-1760
=> [HPRO-1760] Added related participants for adult participants

.circleci/config.yml, Dockerfile, app.yaml.dist
| Target Release?     | 4.3.19 
| Jira Ticket(s)      | HPRO-2000
=> [HPRO-2000] Migrate app engine to php82 runtime

src/Entity/NphAdminOrderEditLog.php
| Target Release?     | 4.4.9.1 
| Jira Ticket(s)      | HPRO-2197
=> [HPRO-2197] Allow order generation timezone id to be null
