all-of-us/healthpro

src/Pmi/Application/HpoApplication.php
src/Pmi/Controller/HelpController.php
views/help/videos.html.twig

[[HPRO-402](https://precisionmedicineinitiative.atlassian.net/browse/HPRO-402)]
This adds training videos to the help resources.  Videos are hosted on YouTube and embedded in our Training Videos page.

[HPRO-402] Add training videos browser/viewer

---

src/Pmi/Controller/WorkQueueController.php
src/Pmi/WorkQueue/WorkQueue.php
views/participant.html.twig
views/workqueue/index.html.twig
web/assets/css/app.css
web/assets/js/views/workqueue.js

[[HPRO-372](https://precisionmedicineinitiative.atlassian.net/browse/HPRO-373)]

[HPRO-373] Add DV-only EHR Sharing status

---

composer.lock

[[HPRO-436](https://precisionmedicineinitiative.atlassian.net/browse/HPRO-436)]
Updates all composer dependencies

[HPRO-436] Update composer dependencies

---

src/Pmi/Controller/HelpController.php
views/help/videos.html.twig
web/assets/css/app.css

[[HPRO-439](https://precisionmedicineinitiative.atlassian.net/browse/HPRO-439)]
* Adds new videos
* Moves chapter numbers into video titles (since new videos do not have chapter numbers)
* Adjusts spacing between categories in video navigation

[HPRO-439] Add new video content

---

src/Pmi/Controller/DefaultController.php
views/workqueue/index.html.twig

The issue is since we are adding `searchField` field in to the array for each search result, php's `array_unique` didn't work. I have re-written the code to use participant id as array index key and filtered out duplicates.

[HPRO-399 ] Fix phone number lookup issues

---

src/Pmi/Drc/RdrMetrics.php

Prior to this PR, a date range greater than 100 days would cause the realtime tab to fail because of an uncaught API error. This PR adjusts the logic so that a realtime (`history=FALSE`) request will batch in 100 day totals, while `history=TRUE` can handle 600 day increments. Because Memcache is capped at 1 MiB per key, it is reduced further to 200.
[[DASH1-75](https://precisionmedicineinitiative.atlassian.net/browse/DASH1-75)]

[DASH1-75] Fix 100 day bug in Realtime tab

---

src/Pmi/Controller/HelpController.php
views/help/videos.html.twig

Added new videos and updated links for existing ones.
I also refactored the videos data and corresponding view slightly.  This reduces redundancy and is a necessary step for when we have a self-hosted video option in the future.
[[HPRO-450](https://precisionmedicineinitiative.atlassian.net/browse/HPRO-450)]

[HPRO-450] New biobank training videos

---

src/Pmi/Console/Command/MetricsCommand.php
src/Pmi/Controller/DashboardController.php
views/dashboard/index.html.twig
web/assets/js/dashboard.js

This PR refactors the "Participants by Region" endpoint to use the new MAPI2 as well as remove the "target enrollment" calculations.
[[DASH1-81](https://precisionmedicineinitiative.atlassian.net/browse/DASH1-81)]

[DASH1-81] Update Dashboard Region endpoints

---

src/Pmi/Console/Command/MetricsCommand.php
src/Pmi/Controller/DashboardController.php
src/Pmi/Drc/RdrMetrics.php
views/dashboard/index.html.twig
web/assets/js/dashboard.js

This PR refactors the "Participants by Lifecycle Phase" tab to use the new Metrics API 2 (MAPI2) endpoints to retrieve the data. It also removes several deprecated endpoints to keep the code cleaner.
NOTE: This also includes the commits for #479, which can be merged first.
[[DASH1-84](https://precisionmedicineinitiative.atlassian.net/browse/DASH1-84)]

[DASH1-84] Update Lifecycle Phase tab to use MAPI2

---

views/dashboard/dashboard_help.html.twig

With the new enrollment status breakdowns, we need to clarify the definitions.
[[DASH1-88](https://precisionmedicineinitiative.atlassian.net/browse/DASH1-88)]
[[DASH1-89](https://precisionmedicineinitiative.atlassian.net/browse/DASH1-88)]

[DASH1-88][DASH1-89] Copy updates to help modals

---

src/Pmi/Controller/WorkQueueController.php
src/Pmi/Entities/Participant.php

**Testing:**
In dev participant id `P366212116` has streetAddress2 field. This participant is paired with awardee `ILLINOIS`, so if you set your site configuration to this awardee you can view it.

[HPRO-443] Add street address2 field in WQ

---

src/Pmi/Controller/HelpController.php

[[HPRO-463](https://precisionmedicineinitiative.atlassian.net/browse/HPRO-463)]

[HPRO-463] Remove training presentations from SOP documents

---

views/dashboard/ehr.html.twig
views/dashboard/partials/modal-dashboard-help.html.twig

- [DASH1-114](https://precisionmedicineinitiative.atlassian.net/browse/DASH1-114) - Removing/renaming data columns
- [DASH1-115](https://precisionmedicineinitiative.atlassian.net/browse/DASH1-115) - Updating help modal text to match

[DASH1-85] Updates from testing

---

src/Pmi/Controller/WorkQueueController.php
src/Pmi/WorkQueue/WorkQueue.php
views/participant.html.twig

[HPRO-467] Display authored timestamps for consents, PPI modules, and withdrawals

---

views/dashboard/partials/modal-dashboard-help.html.twig

More clarifications related to participant status.
[[DASH1-135](https://precisionmedicineinitiative.atlassian.net/browse/DASH1-135)]

[DASH1-135] Update help content on Dashboards

---

src/Pmi/Console/Command/MetricsCommand.php
src/Pmi/Controller/DashboardController.php
src/Pmi/Drc/RdrMetrics.php
views/dashboard/partials/filters.html.twig
views/dashboard/participants-by-region.html.twig
web/assets/js/dashboard.js

Adds a 'Participant' status, defined as:
>A person who has completed the informed consent process and is enrolled in AoURP will become an official Participant. All Participants will have the opportunity to respond to the HIPAA Authorization/EHR Consent or the DV EHR Intent to Share agreement. If the participant agrees to the sharing EHR data, this person will move to the next status: Fully Consented. If the individual does not agree to share EHR data, the status will remain as a participant. Participants do then have the ability to complete PPI questionnaires and become eligible for PM&B, but will not be considered Core Participants.
[[DASH1-102](https://precisionmedicineinitiative.atlassian.net/browse/DASH1-102)]

[DASH1-102] Add 'Participant' enrollment status

---

src/Pmi/Controller/WorkQueueController.php

Hotfix to address [[HPRO-495](https://precisionmedicineinitiative.atlassian.net/browse/HPRO-495)].  (This was already in the 1.6.7 release.)

[HPRO-495] Remove street address 2 from limited work queue export

---

dev_config/config.yml.dist
src/Pmi/Controller/WorkQueueController.php
src/Pmi/WorkQueue/WorkQueue.php
views/workqueue/index.html.twig
web/assets/js/views/workqueue.js

[[HPRO-499](https://precisionmedicineinitiative.atlassian.net/browse/HPRO-499)]
Makes the previously hard-coded export limit and page size configurable.

[HPRO-499] Work Queue export configuration

---

src/Pmi/Controller/WorkQueueController.php
src/Pmi/WorkQueue/WorkQueue.php
views/participant.html.twig
views/workqueue/index.html.twig
web/assets/js/views/workqueue.js

[[HPRO-445](https://precisionmedicineinitiative.atlassian.net/browse/HPRO-445)]

[HPRO-445] Add number of distinct visits

---

src/Pmi/Controller/WorkQueueController.php
src/Pmi/WorkQueue/WorkQueue.php
views/participant.html.twig
views/workqueue/index.html.twig
web/assets/js/views/workqueue.js

Reverts all-of-us/healthpro#547

Revert "[HPRO-445] Add number of distinct visits"

---

package-lock.json

Noticed several vulnerabilities in the npm audit report. This update will fix them.

[HPRO-505] Update npm dependencies

---

src/Pmi/Controller/DashboardController.php

Request is to swap the bar positions so the total available appears on the left.
[[DASH1-145](https://precisionmedicineinitiative.atlassian.net/browse/DASH1-145)]

[DASH1-145] Reverse bars in EHR Dashboard

---

views/dashboard/ehr.html.twig

We need a bit more context for what these terms mean.
[[DASH1-148](https://precisionmedicineinitiative.atlassian.net/browse/DASH1-148)]

[DASH1-148] Tooltips for EHR Metrics columns

---

views/dashboard/ehr.html.twig

This PR allows the user to sort the detail table for the EHR Metrics view.
[[DASH1-147](https://precisionmedicineinitiative.atlassian.net/browse/DASH1-147)]

[DASH1-147] Add column sorting to EHR table

---

views/dashboard/ehr.html.twig

This PR adds a calculated column to show what percent of participants we have EHR consent for have also provided EHR data.
[[DASH1-149](https://precisionmedicineinitiative.atlassian.net/browse/DASH1-149)]

[DASH1-149] Add calculated percentage column to EHR data view

---

src/Pmi/Controller/WorkQueueController.php
src/Pmi/WorkQueue/WorkQueue.php
views/partials/participant-dl.html.twig
views/participant.html.twig
views/participants-list.html.twig
views/workqueue/index.html.twig
web/assets/js/views/workqueue.js

Reverts all-of-us/healthpro#561

Revert "[HPRO-509] Add middle initial of participants in work queue and participant summary page"

---

views/dashboard/partials/modal-dashboard-help.html.twig

Updates the help copy to align with the new content.
[[DASH1-152](https://precisionmedicineinitiative.atlassian.net/browse/DASH1-152)]

[DASH1-152] New Help Copy for Lifecycle Tab

---

src/Pmi/Controller/WorkQueueController.php
src/Pmi/WorkQueue/WorkQueue.php
views/partials/participant-dl.html.twig
views/participant.html.twig
views/participants-list.html.twig
views/workqueue/index.html.twig
web/assets/js/views/workqueue.js

This PR reverts the previously reverted middle initial name field

[HPRO-509] Add middle initial of participants in work queue and participant summary page

---

views/dashboard/partials/modal-dashboard-help.html.twig

Clarifies how we arrive at some of the counts and what is included/excluded.
This rolls up a handful of substasks:
- [DASH1-155](https://precisionmedicineinitiative.atlassian.net/browse/DASH1-155) - Update Help Copy for Tab 1
- [DASH1-156](https://precisionmedicineinitiative.atlassian.net/browse/DASH1-156) - Update Help Copy for Tab 2
- [DASH1-157](https://precisionmedicineinitiative.atlassian.net/browse/DASH1-157) - Update Help Copy for Tab 3
- [DASH1-154](https://precisionmedicineinitiative.atlassian.net/browse/DASH1-154) - Update Help Copy for Tab 4
- [DASH1-158](https://precisionmedicineinitiative.atlassian.net/browse/DASH1-158) - Update Help Copy for Tab 5
[[DASH1-164](https://precisionmedicineinitiative.atlassian.net/browse/DASH1-164)]

[DASH1-164] Help copy updates for Tabs 1-5

---

views/dashboard/partials/modal-dashboard-help.html.twig

QA found a few more things that needed changing.
[[DASH1-164](https://precisionmedicineinitiative.atlassian.net/browse/DASH1-164)]

[DASH1-164] Fixes typos in original help modal update

---

src/Pmi/Audit/Log.php

HPRO-525
The 2nd gen App Engine runtime is adding its own proxy IP headers. It is setting both the `Forwarded` and `X-Forwarded-For` headers. When this is running behind the WAF, the X-Forwarded-For is already set, and App Engine tacks on the WAF's IP address (i.e. `user_ip, waf_ip`).
This PR fixes two things. First, it tells the Request class to only trust the `X-Forwarded-For` header since that's the one that has the user's IP that we want. Second, it uses `getClientIps` instead of `getClientIp` because we want the earliest IP. The Request class actually reverses the IPs in the case of multiple, so we need to get the last in the array.

[HPRO-525] Fix forwarded IP detection

---

views/dashboard/participants-by-lifecycle.html.twig

Adds the enrollment status filter options to the "Participant by Lifecycle" dashboard (Tab 4).
[DASH1-166]

[DASH1-166] Add enrollment status filter to Lifecycle tab

---

views/dashboard/total-progress.html.twig

Adds the enrollment status filter options to the "Participant by Lifecycle" dashboard (Tab 1).
[DASH1-165]

[DASH1-165] Add enrollment status to Total Progress tab

---

src/Pmi/Application/HpoApplication.php
src/Pmi/Controller/HelpController.php
views/help/videos.html.twig
web/assets/css/app.css

HPRO-548
* Adds new tabs for help video playlists
* Biobank video groups are replaced by new Kaltura playlists
* Default tab is based on site context

[HPRO-548] Video playlists

---

src/Pmi/Form/NoticeType.php
views/admin/index.html.twig
views/admin/missing/measurements.html.twig
views/admin/missing/orders.html.twig
views/admin/notices/edit.html.twig
views/admin/notices/index.html.twig
views/admin/notifications/withdrawal.html.twig
views/admin/sites/edit.html.twig
views/admin/sites/index.html.twig
views/admin/sites/sync.html.twig
views/admin/testing/participant.html.twig
views/admin/testing/participants.html.twig
web/assets/js/app.js

HPRO-566
Page notice updates:
* Add drop-down select of common URL pattern options with an "Other" option to manually enter a pattern
* Add timezone display and link to change in user settings
* Relabel "Full Page?" to "Take Page/Application Down"
* Add help text for Take Page/Application Down setting and Start/End Time
Other admin updates:
* Add breadcrumbs to all admin pages
* Change Sync Preview button to make it clear that it will not perform a sync

[HPRO-566] Page notices UI improvements

---

views/dashboard/real-time.html.twig

Enable filtering by Participant Origination in Tab 2 (Real-Time Data).
[DASH1-176]

[DASH1-176] Participant Origination Filtering for Tab 2

---

package-lock.json

Co-Authored-By: Jason Tan <jt2k@users.noreply.github.com>

[HPRO-587] Update npm dependencies to fix vulnerabilities in kind-of package

---

bin/phpunit

Updates alias to accept arguments. Also removes outdated comment.
[HPRO-594]
[HPRO-594]: https://precisionmedicineinitiative.atlassian.net/browse/HPRO-594

[HPRO-594] Allow phpunit alias to accept arguments

---

src/Pmi/Application/HpoApplication.php
src/Pmi/Controller/BiobankController.php
src/Pmi/Controller/WorkQueueController.php

[HPRO-577] Create a read-only biobank order page for Quest samples in the Scripps super user view

---

src/Pmi/Controller/WorkQueueController.php

Accidental cleanup removed it.
[HPRO-577]
[HPRO-577]: https://precisionmedicineinitiative.atlassian.net/browse/HPRO-577

[HPRO-577] Add Pmi\Order\Order use statement

---

Dockerfile
src/Pmi/Console/Command/DeployCommand.php

_Aimed to land as part of #654 by merging into its branch._
---
This leverages the `--no-interaction` flag for Console commands to skip prompts that block Docker from launching.
[HPRO-599]
[HPRO-599]: https://precisionmedicineinitiative.atlassian.net/browse/HPRO-599

[HPRO-599] Skip interactive questions when launching in Docker

---

src/Pmi/Entities/Participant.php
src/Pmi/WorkQueue/WorkQueue.php
tests/Pmi/Participant/ParticipantTest.php
views/macros/display-text.html.twig
views/partials/participant-consent.html.twig

[HPRO-613] Modify EHR Consent PM&B logic and display (Cohort 3)

---

src/Pmi/Controller/WorkQueueController.php
src/Pmi/Entities/Participant.php
src/Pmi/WorkQueue/WorkQueue.php
tests/Pmi/Participant/ParticipantTest.php
web/assets/js/views/workqueue.js
web/local-router.php

This PR handles the work queue and participant views if for some reason the EARLY_OUT status were to slip through the HealthPro UI.
[HPRO-635]
[HPRO-635]: https://precisionmedicineinitiative.atlassian.net/browse/HPRO-635

[HPRO-635] Handle EARLY_OUT withdrawal status

---

symfony/src/Entity/Notice.php
symfony/src/EventListener/RequestListener.php
symfony/src/Repository/NoticeRepository.php
symfony/templates/full-page-notice.html.twig

HPRO-599
Implements the page notice system in the Symfony part of our application.

[HPRO-599] Add Symfony support for page notices

---

src/Pmi/Application/HpoApplication.php
src/Pmi/Controller/DefaultController.php
src/Pmi/Drc/RdrHelper.php
src/Pmi/Drc/RdrParticipants.php
src/Pmi/Entities/Participant.php
tests/Pmi/Participant/ParticipantTest.php
views/partials/participant-notice.html.twig

This PR also modifies the existing logic for cohort 2 participants.

[HPRO-628] Add new PM&B disabling logic to support workflow for Cohort 1 participants

---

src/Pmi/Application/HpoApplication.php
src/Pmi/Controller/DefaultController.php
src/Pmi/Controller/SymfonyMigrationController.php
src/Pmi/Security/MockUser.php
src/Pmi/Security/User.php
src/Pmi/Security/UserProvider.php
src/Pmi/Service/MockUserService.php
symfony/config/packages/security.yaml
symfony/config/routes.yaml
symfony/src/Controller/SettingsController.php
symfony/src/Form/SettingsType.php
symfony/src/Service/UserService.php
symfony/templates/base-head.html.twig
symfony/templates/settings/settings.html.twig
tests/Pmi/AbstractWebTestCase.php
tests/Pmi/Application/HpoApplicationTest.php
web/silex-index.php

This PR migrates the `/settings` route to Symfony. It also introduces a spot in the Silex controller to register migrated routes so that they continue to function.
[HPRO-661]
[HPRO-661]: https://precisionmedicineinitiative.atlassian.net/browse/HPRO-661

[HPRO-661] Migrate 'Settings' to Symfony

---

src/Pmi/Controller/SymfonyMigrationController.php
views/admin/index.html.twig

[HPRO-672] Fix symfony redirects missing trailing slashes

---

symfony/src/Controller/DeceasedReportsController.php
views/index.html.twig
web/assets/css/app.css

Adds a badge that shows the number of Pending Deceased Reports for the logged in user on the main Welcome page.
Note: It takes a second or so for it to show up, and will only appear if the organization has pending reports (i.e. it won't appear if there are zero pending reports).
[HPRO-683]
[HPRO-683]: https://precisionmedicineinitiative.atlassian.net/browse/HPRO-683

[HPRO-683] Deceased Reports > Add badge to Welcome Page

---

symfony/src/Entity/DeceasedReport.php
symfony/templates/deceasedreports/review.html.twig

I missed this requirement earlier.
[HPRO-630]

[HPRO-630] Deceased Reports > Add Denial reason to summary

---

src/Pmi/Controller/WorkQueueController.php
src/Pmi/Entities/Participant.php
src/Pmi/WorkQueue/WorkQueue.php

Adds Deceased Participant data to the Work Queue and its CSV export feature.
[HPRO-680]
[HPRO-680]: https://precisionmedicineinitiative.atlassian.net/browse/HPRO-680

[HPRO-680] Deceased Reports > Work Queue + Export Updates

---

src/Pmi/Controller/WorkQueueController.php
src/Pmi/WorkQueue/WorkQueue.php
views/partials/deceased-participant-notice.html.twig

We don't need  to take into account the user's timezone for this field.
[HPRO-630]

[BUG][HPRO-630] Deceased > Remove timezone adjustment for dateOfDeath

---

symfony/templates/deceasedreports/review.html.twig

No need to show the previously submitted information once reviewed as denied.
[HPRO-630]

[HPRO-630] Redact submission when Deceased Report is denied

---

package-lock.json
package.json

Fixes CVE-2020-7720, bumps package versions of other modules.
[HPRO-686]
[HPRO-686]: https://precisionmedicineinitiative.atlassian.net/browse/HPRO-686

[HPRO-686] Update node-forge, other packages

---

src/Pmi/WorkQueue/WorkQueue.php
symfony/src/Entity/DeceasedReport.php
symfony/src/Form/DeceasedReportReviewType.php
symfony/templates/deceasedreports/index.html.twig
symfony/templates/emails/deceased-approved.txt.twig
symfony/templates/emails/deceased-pending.txt.twig
views/partials/deceased-participant-notice.html.twig
views/partials/participant-notice.html.twig

Language update post-release.
[HPRO-688]
[HPRO-688]: https://precisionmedicineinitiative.atlassian.net/browse/HPRO-688

[HPRO-688] Switch "Approved" to "Accepted" in Deceased Reports

---

sql/healthpro/011-patient_status.sql
sql/migrations/037-alter-patient-status-table.sql
src/Pmi/Controller/DefaultController.php
src/Pmi/PatientStatus/PatientStatus.php
symfony/src/Service/PatientStatusImportService.php

This PR fixes combination of duplicate participant_id and organization insertions in the patient_status table

[HPRO-692] Fix patient status bulk import issue

---

composer.json
composer.lock
sensioignore.json
symfony.lock

We shouldn't need this polyfill now that we're on PHP 7.2. Allows us to clear the `sensioignore.json` entry.
[HPRO-701]
[HPRO-701]: https://precisionmedicineinitiative.atlassian.net/browse/HPRO-701

[HPRO-701] Drop random_compat package

---

src/Pmi/Controller/WorkQueueController.php
src/Pmi/WorkQueue/WorkQueue.php
views/macros/display-text.html.twig
views/participant.html.twig
views/workqueue/index.html.twig
web/assets/js/views/workqueue.js

Reverts all-of-us/healthpro#754

Revert "[HPRO-652] Add active and passive retention metrics to the Participant Work Queue page"

---

src/Pmi/Application/AbstractApplication.php
symfony/src/Service/LoggerService.php

[HPRO-707] Catch exceptions and fail gracefully when generating log metadata

---

src/Pmi/Controller/WorkQueueController.php
src/Pmi/WorkQueue/WorkQueue.php

[HPRO-705] Change COPE Oct to COPE Nov

---

symfony/src/Controller/DebugToolsController.php
views/admin/index.html.twig

[HPRO-719] Enable admin participant summary lookup tool in prod

---

src/Pmi/Application/AbstractApplication.php
symfony/src/Service/StackdriverHandler.php

[HPRO-724] Fix StackDriver logging when request object cannot be retrieved

---

views/emails/deactivates.txt.twig
views/emails/withdrawals.txt.twig

[HPRO-732] Update language of withdrawal and deactivation emails

---

symfony/src/Service/DeceasedNotificationService.php

[HPRO-731] Allow reported death dates up to one month prior to current date for automated deceased status emails

---

src/Pmi/Controller/WorkQueueController.php
views/participant.html.twig
views/workqueue/index.html.twig
web/assets/css/app.css

| Target Release?     | 2.3.8
| Jira Ticket(s)      | HPRO-730

[HPRO-730] Rename label for Biospecimens Received in UI and add help text that clarifies definition

---

sql/healthpro/sites.sql
sql/migrations/039-alter-sites-add-unique-key-site-id.sql
symfony/src/Controller/SitesController.php
symfony/src/Service/SiteSyncService.php

| Target Release?     | 2.3.8
| New feature?        |❌ 
| Jira Ticket(s)      | HPRO-739

[HPRO-739] Fix duplicate sites issue when performing sites sync

---

src/Pmi/Controller/WorkQueueController.php
src/Pmi/WorkQueue/WorkQueue.php

| Target Release?     | 2.3.9 
| Jira Ticket(s)      | HPRO-723

[HPRO-723] Add January COPE survey details to the Participant Work Queue and the Participant Summary pages

---

src/Pmi/Controller/WorkQueueController.php
src/Pmi/WorkQueue/WorkQueue.php

Reverts all-of-us/healthpro#799

Revert "[HPRO-723] Add January COPE survey details to the Participant Work Queue and the Participant Summary pages"

---

views/workqueue/index.html.twig
web/assets/js/views/workqueue.js

| Target Release?     | 2.3.9 
| Jira Ticket(s)      | HPRO-734

[HPRO-734] Adding/removing fields from WorkQueue column views

---

dev_config/config.yml.dist
src/Pmi/Application/HpoApplication.php
symfony/src/Service/SiteSyncService.php

| Target Release?     | 2.3.10 
| New configuration?  | ✅ 
| Jira Ticket(s)      | HPRO-741

[HPRO-741] Make diversion pouch site type configurable

---

src/Pmi/WorkQueue/WorkQueue.php
views/workqueue/index.html.twig
web/assets/js/views/workqueue.js

| Target Release?     | 2.4.0 
| Jira Ticket(s)      | HPRO-736

[HPRO-736] Combine PPI and PPI Date fields in the WorkQueue

---

src/Pmi/WorkQueue/WorkQueue.php
views/workqueue/index.html.twig
web/assets/css/app.css
web/assets/js/views/workqueue.js

| Target Release?     | 2.4.0 
| Jira Ticket(s)      | HPRO-735 , HPRO-737

[HPRO-735] [HPRO-737] Rearrange columns & Create Consent Column Group/View in the WorkQueue

---

src/Pmi/Controller/WorkQueueController.php
src/Pmi/WorkQueue/WorkQueue.php
views/workqueue/index.html.twig

| Target Release?     | 2.4.0 
| Jira Ticket(s)      | HPRO-750

[HPRO-750] Re-ordering of .csv export to match order of columns in the WorkQueue

---

src/Pmi/WorkQueue/WorkQueue.php

| Jira Ticket(s)      | HPRO-759

[HPRO-759] Fix WQ sort issue

---

src/Pmi/Controller/WorkQueueController.php

| Target Release?     | 2.4.0.2 
| New feature?        |❌ 
| Jira Ticket(s)      | HPRO-761
Switch to scripps super user view and go to Work Queue. You should see the Export button.

[HPRO-761] Fix WQ export disable issue for SCRIPPS super user

---

src/Pmi/Controller/WorkQueueController.php
src/Pmi/WorkQueue/WorkQueue.php

| Target Release?     | 2.4.1 
| Database migration? | ✅
| New configuration?  | ✅
| Composer updates?   | ✅
| NPM updates?        | ✅
| Jira Ticket(s)      | HPRO-723

[HPRO-723] Add February COPE survey details to the Participant Work Queue and the Participant Summary pages

---

symfony/src/Controller/OrderController.php
symfony/src/Service/OrderService.php

| Target Release?     | 2.4.2 
| Jira Ticket(s)      | HPRO-748

[HPRO-748] Fix order view issue for withdrawn participants 

---

.circleci/config.yml
Dockerfile
app.yaml.dist
composer.json
composer.lock
symfony.lock

| Jira Ticket(s)      | HPRO-776 
Updates the Docker image for local development and CI. Also bumps the Composer "platform" declaration to conform with the running version.
Run `docker-compose build` (will take a long time to complete).

[HPRO-776] Update to PHP 7.4 runtime

---

symfony/src/Service/ParticipantSummaryService.php
symfony/src/Service/PatientStatusService.php
symfony/templates/order/header.html.twig
symfony/templates/partials/participant-withdrawn-notice.html.twig

| Target Release?     | 2.4.4 
| Jira Ticket(s)      | HPRO-767 
Deployed this branch to dev env with out modifying any datastore configs and didn't notice any issues.

[HPRO-767] Fix cache time datatype and other migration issues

---

symfony/config/routes.yaml

| Target Release?     | 2.4.4 
| Jira Ticket(s)      | HPRO-767

[HPRO-767] Fix patientStatus route

---

symfony/src/Service/WorkQueueService.php

| Target Release?     | 2.4.4 
| Jira Ticket(s)      | HPRO-753

[HPRO-753] Fix WQ Physical Measurements date

---

symfony/src/Service/ParticipantSummaryService.php

| Target Release?     | 2.4.4 
| Jira Ticket(s)      | HPRO-767

[HPRO-767] Fix participant cohort status

---

symfony/src/Controller/ParticipantLookupController.php
symfony/src/Service/ParticipantSummaryService.php

| Jira Ticket(s)      | HPRO-783 
Query parameters were not properly mapped to their RDR counterparts, resulting in the API returning more records than actually matched the query provided. This PR addresses this by porting over the mapping functionality. It also addresses a missing Exception that, should it have been called, would not have been located.
Providing a non-existent phone number or a mismatched DOB should not return a result.

[HPRO-783] Address multiple issues with Participant Lookup

---

dev_config/config.yml.dist
sql/healthpro/sites.sql
sql/migrations/042-alter-sites-table-add-ehr-protocal-modification-column.sql
src/Pmi/Controller/EvaluationController.php
src/Pmi/Evaluation/Evaluation.php
src/Pmi/Evaluation/Fhir.php
src/Pmi/Evaluation/versions/0.3.3-diversion-pouch.json
src/Pmi/Evaluation/versions/0.3.3-ehr.json
src/Pmi/Evaluation/versions/0.3.3.json
symfony/src/Entity/Site.php
symfony/src/Form/SiteType.php
tests/Pmi/Evaluation/EvaluationTest.php
tests/Pmi/Evaluation/ehr-measurement-source-fhir.json
views/evaluation.html.twig
views/evaluationform/0.3-ehr.html.twig
web/assets/css/app.css
web/assets/js/views/PhysicalEvaluation-0.3-ehr.js
webpack.config.js

| Jira Ticket(s)      | HPRO-772,  HPRO-771

[HPRO-772] [HPRO-771] Add EHR and Pandemic protocol modifications

---

symfony/templates/partials/participant-evaluation-list.html.twig

| Target Release?     | 2.4.5 
| Jira Ticket(s)      | HPRO-786

[HPRO-786] Fix parent id variable name in evaluations list twig file

---

web/assets/js/views/PhysicalEvaluation-0.3-ehr.js

| Bug fix?            | ❌
| Jira Ticket(s)      | HPRO-772

[HPRO-772] Add EHR Physical Measurements modification to protocol - 2

---

web/assets/js/views/PhysicalEvaluation-0.3-ehr.js

| Jira Ticket(s)      | HPRO-772

[HPRO-772] Fix EHR date issue for waist and hip circumference

---

src/Pmi/Evaluation/Evaluation.php

| Jira Ticket(s)      | HPRO-...

[HPRO-782] Require users to enter a reason when selecting Modification to Protocol="Other"

---

web/assets/js/views/PhysicalEvaluation-0.3-diversion-pouch.js
web/assets/js/views/PhysicalEvaluation-0.3-ehr.js
web/assets/js/views/PhysicalEvaluation-0.3.js

| Jira Ticket(s)      | HPRO-785

[HPRO-785] Wheelchair user protocol modification is not auto-selected when wheelchair user question is answered "yes"

---

symfony/templates/biobank/order.html.twig

| Target Release?     | 2.4.6 
| Jira Ticket(s)      | HPRO-754

[HPRO-754] Fix check all in biobank finalize tab

---

src/Pmi/Evaluation/Evaluation.php

| Target Release?     | 2.4.6.1
| Jira Ticket(s)      | HPRO-788

[HPRO-788] Fix field to check for other protocol modification reason

---

symfony/config/packages/security.yaml

| Target Release?     | 2.4.6.2 
| Jira Ticket(s)      | HPRO-789

[HPRO-789] Fix biobank permission issue

---

src/Pmi/Controller/DefaultController.php
symfony/src/Controller/BiobankController.php
symfony/src/Controller/OrderController.php
symfony/src/Controller/ParticipantDetailsController.php
symfony/src/Service/OrderService.php
symfony/src/Service/PatientStatusImportService.php
symfony/src/Service/WorkQueueService.php
symfony/templates/base-head.html.twig
symfony/templates/biobank/order-quanum.html.twig
symfony/templates/biobank/order.html.twig
symfony/templates/biobank/orders-quanum-today.html.twig
symfony/templates/biobank/partials/biobank-order-details.html.twig
symfony/templates/biobank/summary.html.twig
symfony/templates/macros/display-text.html.twig
symfony/templates/order/header.html.twig
symfony/templates/order/modify.html.twig
symfony/templates/partials/deceased-participant-notice.html.twig
symfony/templates/partials/participant-deactivated-status-notice.html.twig
symfony/templates/partials/participant-dl.html.twig
symfony/templates/partials/participant-evaluation-list.html.twig
symfony/templates/partials/participant-orders-list.html.twig
symfony/templates/partials/participant-unanticipated-problems-list.html.twig
symfony/templates/partials/participant-withdrawn-notice.html.twig
symfony/templates/partials/patient-status-history-dl.html.twig
symfony/templates/participant/details.html.twig
symfony/templates/patientstatus/import.html.twig
symfony/templates/workqueue/participant.html.twig

| Target Release?     | 2.4.6.3 
| Jira Ticket(s)      | HPRO-793

[HPRO-793] Fix Symfony timezone issues

---

src/Pmi/Controller/EvaluationController.php
src/Pmi/Evaluation/Evaluation.php
src/Pmi/Evaluation/versions/0.3.3-blood-donor.json
tests/Pmi/Evaluation/blood-donor-fhir.json
tests/Pmi/Evaluation/ehr-measurement-source-fhir.json
web/assets/js/views/PhysicalEvaluation-0.3-blood-donor.js

| Jira Ticket(s)      | HPRO-579

[HPRO-579] Diversion pouch new updates

---

src/Pmi/Evaluation/versions/0.3.3-blood-donor.json
symfony/src/Controller/ParticipantDetailsController.php
symfony/src/Controller/WorkQueueController.php

| Target Release?     | 2.4.7 

Release 2.4.7 bug fixes

---

web/assets/js/views/PhysicalEvaluation-0.3-blood-donor.js
web/assets/js/views/PhysicalEvaluation-0.3-ehr.js
web/assets/js/views/PhysicalEvaluation-0.3.js

| Target Release?     | 2.4.8 
| Jira Ticket(s)      | HPRO-799

[HPRO-799] Clear out blood pressure, waist, and hip circumference readings when the fields are disabled

---

symfony/src/Service/PatientStatusImportService.php
web/assets/js/views/PatientStatusImport.js

| Jira Ticket(s)      | HPRO-802

[HPRO-802] Format imported PatientStatus comments

---

src/Pmi/Entities/Participant.php
symfony/src/Helper/Participant.php

| Jira Ticket(s)      | HPRO-816

[HPRO-816] Allow cohort 3 participants to view existing PM&B

---

composer.lock

| Composer updates?   |  ✅  
| Jira Ticket(s)      | HPRO-824

[HPRO-824] Fix symfony/security vulnerability

---

symfony/src/Helper/WorkQueue.php
symfony/src/Service/WorkQueueService.php

| Jira Ticket(s)      | HPRO-823

[HPRO-823] All of Us Minute Survey on Covid-19

---

symfony/src/Controller/MeasurementsController.php

| Target Release?     | 2.5.0.1 
| Jira Ticket(s)      | HPRO-828

[HPRO-828] Fix entity class

---

symfony/src/Controller/ProblemController.php
symfony/src/Controller/ReviewController.php

| Jira Ticket(s)      | HPRO-837

[HPRO-837] Fix return type errors

---

symfony/src/Repository/OrderRepository.php

| Target Release?     | 2.5.3 
| Bug fix?            | ✅  
| Jira Ticket(s)      | HPRO-844

[HPRO-844] Fix duplicate Fedex tracking issue

---

symfony/src/Service/GoogleGroupsService.php
symfony/src/Service/SiteService.php

| Target Release?     | 2.5.4 
| Jira Ticket(s)      | HPRO-764

[HPRO-764] Fix error on SiteService class

---

symfony/src/EventListener/RequestListener.php

| Target Release?     | 2.5.4 
| Jira Ticket(s)      | HPRO-764

[HPRO-764] Fix session timeout issue

---

symfony/src/EventListener/RequestListener.php

| Target Release?     | 2.5.4 
| Jira Ticket(s)      | HPRO-764

[HPRO-764] Fix on kernel requests

---

symfony/src/Controller/BiobankController.php

| Target Release?     | 2.5.4 
| Jira Ticket(s)      | HPRO-859

[HPRO-859] Fix Scripps view duplicate order issue

---

symfony/src/EventListener/RequestListener.php
symfony/src/Service/SiteService.php

| Target Release?     | 2.5.4
| Jira Ticket(s)      | HPRO-756

[HPRO-756] Fix site dropdown display names

---

symfony/src/Service/SiteService.php

| Target Release?     | 2.5.4.2 
| New configuration?  |❌ 
| Jira Ticket(s)      | HPRO-873

[HPRO-873] Fix dv site type issue

---

cron.yaml.dist
dev_config/config.yml.dist
symfony/src/Controller/CronController.php
symfony/src/Controller/ParticipantDetailsController.php
symfony/src/Repository/OrderRepository.php

| Jira Ticket(s)      | HPRO-874

[HPRO-874] Fix processed timestamp issue

---

symfony/src/Entity/Measurement.php
symfony/templates/review/unfinalized_measurements.html.twig

| Target Release?     | 2.5.4.3 
| Jira Ticket(s)      | HPRO-885

[HPRO-885] Fix physical measurements cancel issue

---

dev_config/config.yml.dist
src/Pmi/Audit/Log.php
symfony/src/Controller/AccessManagementController.php
symfony/src/Form/RemoveGroupMemberType.php
symfony/src/Service/AccessManagementService.php
symfony/templates/accessmanagement/add-member.html.twig
symfony/templates/accessmanagement/group-members.html.twig
symfony/templates/accessmanagement/remove-member.html.twig
symfony/templates/emails/group-member-removal-email.txt.twig
web/assets/js/views/GroupMemberRemove.js
webpack.config.js

| Jira Ticket(s)      | HPRO-882

[HPRO-862] Email Notification for Users Removed from the Google Groups

---

symfony/templates/order/finalize.html.twig
symfony/templates/order/header.html.twig

| Jira Ticket(s)      | HPRO-839

[HPRO-839] Create a warning message when finalizing a mix-matched biobank Order

---

symfony/src/Repository/OrderRepository.php

| Target Release?     | 2.5.5 
| Jira Ticket(s)      | HPRO-874

[HPRO-874] Change back fill processed timestamp criteria

---

symfony/src/Form/OrderType.php
symfony/templates/base.html.twig
symfony/templates/participant/details.html.twig
views/base.html.twig

| Jira Ticket(s)      | HPRO-886

[HPRO-886] Address symfony deprecations

---

symfony/src/Repository/OrderRepository.php

| Jira Ticket(s)      | HPRO-880

[HPRO-880] Fix missing orders list query

---

symfony/src/Controller/AccessManagementController.php
symfony/src/EventListener/RequestListener.php
symfony/src/Service/GoogleGroupsService.php
symfony/templates/accessmanagement/add-member.html.twig
symfony/templates/accessmanagement/group-members.html.twig

| Target Release?     | 2.6.0 
| Jira Ticket(s)      | HPRO-856

[HPRO-856] Managed access dashboard new changes

---

symfony/src/Service/GoogleGroupsService.php

| Target Release?     | 2.6.0 
| Jira Ticket(s)      | HPRO-856

[HPRO-856] Change member add remove success messages

---

web/assets/js/views/GroupMemberRemove.js

| Target Release?     | 2.6.0 
| Jira Ticket(s)      | HPRO-856
https://user-images.githubusercontent.com/6041980/130694432-b29a1a16-06f5-43b0-8dd7-fb1ba12f03c5.mov

[HPRO-856] Fix select current date

---

symfony/templates/emails/group-member-removal-email.txt.twig

| Target Release?     | 2.6.0 
| Jira Ticket(s)      | HPRO-862

[HPRO-862] Update email text

---

web/assets/js/views/PhysicalEvaluation-0.3-blood-donor.js
web/assets/js/views/PhysicalEvaluation-0.3-ehr.js
web/assets/js/views/PhysicalEvaluation-0.3.js

| Jira Ticket(s)      | HPRO-889

[HPRO-889] Clear pre-pregnancy weight when weight field is disabled

---

dev_config/config.yml.dist
symfony/src/Command/ReleaseTicketCommand.php
symfony/src/Service/JiraService.php
symfony/templates/jira/approval-request-comment.txt.twig

| Jira Ticket(s)      | HPRO-887 
Run `bin/console pmi:jira --comment=approval`
Enter ticket id ex: HPRO-810

[HPRO-887] Add security approval request comment to JIRA release ticket tool

---

symfony/templates/macros/display-text.html.twig

| Jira Ticket(s)      | HPRO-833

[HPRO-833] Fix digital health field parse error in twig

---

symfony/src/Controller/OrderController.php
symfony/src/Service/OrderService.php
symfony/templates/order/print-labels.html.twig

| Jira Ticket(s)      | HPRO-894

[HPRO-894] Automatically Switch to Next Tab during a Biobank Order

---

README.md
symfony/src/Command/ReleaseTicketCommand.php
symfony/src/Service/JiraService.php
symfony/templates/jira/deploy-output-comment.txt.twig

| Composer updates?   |❌ 
| Jira Ticket(s)      | HPRO-888 
Run `bin/console pmi:jira --comment=file` and follow instructions

[HPRO-888] Add deploy output attachment comment to JIRA release ticket tool

---

symfony/src/Form/MeasurementType.php
symfony/templates/deceasedreports/new.html.twig
web/assets/js/views/PhysicalEvaluation-0.3-ehr.js

| Jira Ticket(s)      | HPRO-911

[HPRO-911] Fix selecting current date in EHR physical measurements and deceased report page

---

dev_config/config.yml.dist
symfony/src/Controller/WorkQueueController.php
symfony/src/Helper/WorkQueue.php
symfony/src/Service/WorkQueueService.php
symfony/templates/workqueue/_page_heading.html.twig
symfony/templates/workqueue/consents.html.twig
symfony/templates/workqueue/index.html.twig
web/assets/css/app.css
web/assets/js/views/WorkQueueConsents.js
webpack.config.js

| Jira Ticket(s)      | HPRO-903

[HPRO-903] Create WQ Participant Consents

---

cron.yaml.dist

| Target Release?     | 2.6.2 
| Jira Ticket(s)      | HPRO-907

[HPRO-907] Add resend measurements cron job

---

symfony/templates/accessmanagement/groups.html.twig

| Target Release?     | 2.6.2 
| Jira Ticket(s)      | HPRO-915

[HPRO-915] Rename text Groups to HealthPro Groups

---

symfony/src/Service/MeasurementQueueService.php

| Target Release?     | 2.6.2 
| Jira Ticket(s)      | HPRO-.907

[HPRO-907] Fix undefined method error

---

symfony/src/Controller/WorkQueueController.php
symfony/src/Helper/WorkQueue.php
symfony/src/Service/WorkQueueService.php
symfony/templates/workqueue/consents.html.twig
web/assets/js/views/WorkQueueConsents.js

| Jira Ticket(s)      | HPRO-904

[HPRO-904] Create columns definitions for WQ participants consent

---

symfony/templates/accessmanagement/remove-member.html.twig

| Jira Ticket(s)      | HPRO-924

[HPRO-924] Change email label text to credentials

---

symfony/src/Helper/WorkQueue.php

| Target Release?     | 2.6.5 
| Jira Ticket(s)      | HPRO-932

[HPRO-932] Fix PFHH field

---

src/Controller/WorkQueueController.php
src/Helper/WorkQueue.php
templates/base.html.twig
templates/index.html.twig
templates/partials/workqueue-consents-advance-filters.html.twig
templates/partials/workqueue-consents-columns.html.twig
templates/workqueue/consents.html.twig
web/assets/css/app.css
web/assets/js/views/WorkQueueConsents.js

[HPRO-928] WQ participant consents filters new updates

---

.gcloudignore

| Jira Ticket(s)      | HPRO-855

[HPRO-855] Update gcloud ignore file

---

templates/partials/workqueue-consents-advance-filters.html.twig
web/assets/js/views/WorkQueueConsents.js

[HPRO-928] Add reset button next to select dates

---

src/Helper/WorkQueue.php

[HPRO-928] Consent WQ Fix typo

---

phpstan.neon.dist

| Jira Ticket(s)      | HPRO-855

[HPRO-855] Fix path in phpstan dist file

---

src/Command/SyncSiteEmailsCommand.php

| Jira Ticket(s)      | HPRO-914 
Need to add Audit Log entries when update the Sites table.

[HPRO-914] Add Audit Log entry for Site Sync > Email updates

---

src/Helper/WorkQueue.php
templates/partials/workqueue-consents-advance-filters.html.twig

[HPRO-928] Fix consent date filters

---

src/Service/GcsBucketService.php

[HPRO-928] Fix auth json parse error

---

src/Controller/AccessManagementController.php
src/Form/RemoveGroupMemberType.php
src/Service/AccessManagementService.php
templates/accessmanagement/remove-member.html.twig
templates/emails/group-member-removal-email.txt.twig

| Jira Ticket(s)      | HPRO-955

[HPRO-955] Add Attestation Selection for User Removal

---

src/Controller/MeasurementsController.php
src/Controller/ParticipantDetailsController.php
src/Repository/MeasurementRepository.php

| Jira Ticket(s)      | HPRO-962

[HPRO-962] Fix amended measurements display issue

---

src/Controller/ParticipantDetailsController.php
templates/macros/display-text.html.twig
templates/participant/details.html.twig

| Jira Ticket(s)      | HPRO-964

[HPRO-964] Add consent pdf links in participant overview tab

---

package-lock.json
package.json
templates/workqueue/index.html.twig
web/assets/css/app.css
web/assets/js/app.js
web/assets/js/views/WorkQueueConsents.js
web/assets/js/views/workqueue.js

Reverts all-of-us/healthpro#986

Revert "[HPRO-935] Freeze top row in Work Queue"

---

src/Controller/OrderController.php

| Jira Ticket(s)      | HPRO-983

[HPRO-983] Fix DV order redirect issue after finalize step

---

templates/measurement/index.html.twig
templates/partials/participant-dl.html.twig

| Jira Ticket(s)      | HPRO-973

[HPRO-973] Display biobank id and participant status fields in PM form

---

templates/participant/details.html.twig

| Jira Ticket(s)      | HPRO-978

[HPRO-978] Redesign refresh button

---

templates/participant/details.html.twig

| Jira Ticket(s)      | HPRO-977

[HPRO-977] Change Report Deceased Participant dropdown to button

---

src/Entity/OrderHistory.php

| Jira Ticket(s)      | HPRO-972

[HPRO-972] Display other text reason for cancel orders

---

templates/measurementform/metrics.html.twig
web/assets/js/views/PhysicalEvaluation-0.3-blood-donor.js
web/assets/js/views/PhysicalEvaluation-0.3-ehr.js
web/assets/js/views/PhysicalEvaluation-0.3.js

| Jira Ticket(s)      | HPRO-974

[HPRO-974] Add Converted Metric display above Hip and Waist on PM form

---

src/Helper/WorkQueue.php

| Jira Ticket(s)      | HPRO-984

[HPRO-984] Fix column names in WQ CSV export

---

src/Helper/WorkQueue.php
src/Service/WorkQueueService.php
tests/Service/WorkQueueServiceTest.php

| Jira Ticket(s)      | HPRO-994

[HPRO-994] Fix CSV export zip code RDR field name

---

templates/order/header.html.twig
web/assets/js/views/OrderSubPage.js

| Jira Ticket(s)      | HPRO-970

[HPRO-970] Display order unlock warning message

---

src/Controller/ReviewController.php
src/Service/ReviewService.php
templates/review/modified_measurements.html.twig
templates/review/modified_orders.html.twig
templates/review/today.html.twig
templates/review/unfinalized_measurements.html.twig
templates/review/unfinalized_orders.html.twig
web/assets/js/views/review.js
web/assets/js/views/today.js
webpack.config.js

| Jira Ticket(s)      | HPRO-975

[HPRO-975] Add PID & Name to Participant Review tabs

---

config/packages/prod/monolog.yaml
src/Audit/Log.php
src/Controller/DefaultController.php
src/EventListener/RequestListener.php
src/Service/LoggerService.php

| Jira Ticket(s)      | HPRO-958

[HPRO-958] Adjust log level for 404 not found exceptions

---

src/Command/ReleaseTicketCommand.php
src/Service/JiraService.php

| Jira Ticket(s)      | HPRO-986

[HPRO-986] Set component field in JIRA release ticket generator

---

composer.json
composer.lock

| Jira Ticket(s)      | HPRO-999

[HPRO-999] Upgrade phpstan to latest version

---

src/Helper/WorkQueue.php
tests/Service/WorkQueueServiceTest.php
tests/Service/data/participant_summary_search.json

| Jira Ticket(s)      | HPRO-996

[HPRO-996] Add New Year Minute Survey Field

---

phpstan.neon.dist
src/Command/DeployCommand.php
src/Controller/ProblemController.php
src/Controller/WorkQueueController.php
src/Helper/Participant.php
src/Model/Measurement/Fhir.php
src/Service/GoogleGroupsService.php
src/Service/SiteSyncService.php
src/Service/UserService.php

| Jira Ticket(s)      | HPRO-1000

[HPRO-1000] Increase phpstan level to 1

---

src/Service/UserService.php

| Target Release?     | 2.7.0 
| Jira Ticket(s)      | HPRO-1000

[HPRO-1000] Fix user empty check

---

web/assets/js/views/PhysicalEvaluation-0.3-blood-donor.js
web/assets/js/views/PhysicalEvaluation-0.3-ehr.js
web/assets/js/views/PhysicalEvaluation-0.3.js

| Jira Ticket(s)      | HPRO-993

[HPRO-993] Remove link to enter metrics for Waist & Hip fields when form is finalized

---

src/Controller/BiobankController.php
src/Controller/OrderController.php
src/Entity/Order.php
src/Service/BiobankOrderFinalizeNotificationService.php
src/Service/ReviewService.php
templates/biobank/order.html.twig
templates/order/finalize.html.twig
templates/order/header.html.twig
templates/order/modify.html.twig
templates/review/modified_orders.html.twig
templates/review/today.html.twig
templates/review/unfinalized_orders.html.twig
tests/Entity/OrderTest.php
web/assets/js/views/FinalizeOrder.js
webpack.config.js

| Jira Ticket(s)      | HPRO-971

[HPRO-971] - Remove 'Processing' tab from Saliva workflow

---

templates/order/check.html.twig
web/assets/js/views/OrderSafetyChecks.js

| Jira Ticket(s)      | HPRO-1001

[HPRO-1001] Add syncope question in order check form

---

src/Command/SyncSiteEmailsCommand.php
src/Repository/SiteRepository.php
src/Service/GoogleGroupsService.php

| Target Release?     | 2.7.1 
| Jira Ticket(s)      | HPRO-1050

[HPRO-1050] Fix site sync emails cron job

---

templates/review/today.html.twig

| Target Release?     | 2.7.2 
| Jira Ticket(s)      | HPRO-971

[HPRO-971] Fix undefined order type error in today's review tab

---

templates/review/today.html.twig
web/assets/js/views/today.js

| Jira Ticket(s)      | HPRO-1048

[HPRO-1048] Fix PM created & finalized count issue in today's review tab

---

templates/order/collect.html.twig
templates/order/finalize.html.twig
templates/order/header.html.twig
templates/order/process.html.twig
web/assets/js/views/OrderSubPage.js

| Jira Ticket(s)      | HPRO-1023

[HPRO-1023] Add Biobank Order Missing Help Text

---

src/Entity/Order.php

| Target Release?     | 2.7.2 
| Jira Ticket(s)      | HPRO-1001
This method got removed when we migrated order workflow to Symfony.

[HPRO-1001] Fix undefined getUrineSample method

---

templates/order/check.html.twig
web/assets/js/views/OrderSafetyChecks.js

Looks like the product team wants to hold on HPRO-1001 and asked me pull this off from 2.7.2 release.

Revert [HPRO-1001] Add syncope question in order check form

---

templates/order/collect.html.twig
templates/order/finalize.html.twig
templates/order/process.html.twig

| Jira Ticket(s)      | HPRO-1037

[HPRO-1037] Update notes warning text

---

src/Form/ParticipantLookupTelephoneType.php
templates/participantlookup/participants.html.twig
web/assets/js/views/ParticipantLookup.js
web/assets/js/views/WorkQueueConsents.js
webpack.config.js

| Jira Ticket(s)      | HPRO-1036

[HPRO-1036] Add mask to dob field in participant lookup

---

src/Form/DeceasedReportType.php
src/Form/NoticeType.php
src/Form/RemoveGroupMemberType.php
src/Form/ReviewTodayFilterType.php

| Target Release?     | 2.7.2.1 
| Jira Ticket(s)      | HPRO-1053

[HPRO-1053] Fix date constraint error

---

src/Controller/SitesController.php
src/Form/SiteType.php
templates/admin/sites/index.html.twig
templates/macros/display-text.html.twig

| Jira Ticket(s)      | HPRO-1002

[HPRO-1002] Add new columns in admin sites table

---

src/Controller/OrderController.php
templates/order/check.html.twig
web/assets/js/views/OrderSafetyChecks.js

| Jira Ticket(s)      | HPRO-1001

[HPRO-1001] Add New Syncope Question for Biobank Workflow

---

templates/participant/details.html.twig
templates/problem/problem-details.html.twig
templates/problem/problem-reports.html.twig
templates/problem/problem.html.twig
templates/settings/settings.html.twig
web/assets/js/views/Participant.js
web/assets/js/views/ProblemReports.js
web/assets/js/views/Settings.js
webpack.config.js

| Jira Ticket(s)      | HPRO-1052

[HPRO-1052] Remove settings, problems, and participant view JS files in twig

---

templates/measurement/index.html.twig

| Jira Ticket(s)      | HPRO-1031

[HPRO-1031] Update buttons in PM form

---

templates/deceasedreports/new.html.twig
templates/deceasedreports/review.html.twig

| Jira Ticket(s)      | HPRO-1028

[HPRO-1028] Add cancel button in deceased form

---

templates/deceasedreports/review.html.twig

| Target Release?     | 0Next available 
| Jira Ticket(s)      | HPRO-1027

[HPRO-1027] Add return link in deceased reports page

---

composer.json
composer.lock
config/services.php
dev_config/config.yml.dist
src/SecretManager/SecretManager.php
symfony.lock

| Jira Ticket(s)      | HPRO-947

[HPRO-947] Integrate google secret manager

---

config/packages/google_apiclient.yaml
src/Security/UserProvider.php
src/Service/AuthService.php
src/Service/GoogleGroupsService.php
src/Service/MockGoogleGroupsService.php
src/Service/RdrApiService.php

| Jira Ticket(s)      | HPRO-957

[HPRO-957] Update namespaces google client classes

---

src/Controller/WorkQueueController.php
src/Helper/WorkQueue.php

| Target Release?     | 2.7.5.1 
| Jira Ticket(s)      | HPRO-1069

[HPRO-1069] Fix awardee filter issue for awardee user

---

src/Controller/WorkQueueController.php

| Target Release?     | 2.7.6 
| Jira Ticket(s)      | HPRO-1071

[HPRO-1071] Fix WQ pairing filter

---

src/Controller/OrderController.php
templates/order/header.html.twig

| Target Release?     | 2.7.6 
| Jira Ticket(s)      | HPRO-...

[HPRO-1067] Fix biobank summary read only view

---

templates/partials/participant-incentive.html.twig
templates/partials/participant-organization-patient-status-details.html.twig
templates/partials/participant-patient-status.html.twig
templates/partials/patient-status-history-dl.html.twig
templates/partials/patient-status-history-list.html.twig
web/assets/css/app.css
web/assets/js/views/Incentive.js
web/assets/js/views/Participant.js

| Jira Ticket(s)      | HPRO-1065

[HPRO-1065] Patient status history UI changes

---

src/Form/RemoveGroupMemberType.php
templates/accessmanagement/remove-member.html.twig
templates/form/simple_checkbox_label.twig
web/assets/css/app.css
web/assets/js/views/GroupMemberRemove.js

| Jira Ticket(s)      | HPRO-1073

[HPRO-1073] Change options text

---

web/assets/js/views/Incentive.js

| Jira Ticket(s)      | HPRO-1064

[HPRO-1064] Fix gift card field toggle

---

templates/partials/participant-incentive.html.twig

| Target Release?     | 2.8.0 
| Jira Ticket(s)      | HPRO-1060

[HPRO-1060] Fix incentive field date/time issues

---

src/Form/IncentiveType.php
templates/partials/participant-incentive.html.twig

| Target Release?     | 2.8.0 
| Jira Ticket(s)      | HPRO-1060

[HPRO-1060] Release 2.8.0 fixes

---

src/Controller/ParticipantDetailsController.php
src/Service/IncentiveService.php
templates/partials/participant-incentive.html.twig
templates/partials/participant-patient-status.html.twig
templates/participant/details.html.twig
web/assets/css/app.css
web/assets/js/views/Incentive.js

| Target Release?     | 2.8.0 
| Jira Ticket(s)      | HPRO-1060

[HPRO-1060] Release 2.8.0 fixes 2

---

src/Form/IncentiveType.php
web/assets/js/views/Incentive.js

| Target Release?     | 2.8.0 
| Jira Ticket(s)      | HPRO-1060

[HPRO-1060] Fix date picker in edit incentive modal

---

src/Controller/BiobankController.php

| Jira Ticket(s)      | HPRO-1075

[HPRO-1075] Fix timezone issue in biobank view

---

src/Controller/ParticipantDetailsController.php

| Target Release?     | 2.8.0.1 
| Jira Ticket(s)      | HPRO-1091

[HPRO-1091] Fix on site details tab issue for dv sites

---

src/Audit/Log.php
src/Controller/ParticipantDetailsController.php
src/Form/IdVerificationType.php
src/Service/IdVerificationService.php
templates/partials/participant-id-verification.html.twig
templates/partials/participant-patient-status.html.twig
templates/participant/details.html.twig
tests/Service/IdVerificationServiceTest.php
web/assets/css/app.css
web/assets/js/views/IdVerification.js
web/assets/js/views/Incentive.js
web/assets/js/views/Participant.js
webpack.config.js

| Target Release?     | 2.8.1 
| Jira Ticket(s)      | HPRO-1017

[HPRO-1017] Implement id verification

---

templates/order/check.html.twig

| Target Release?     | 2.8.1 
| Jira Ticket(s)      | HPRO-1080

[HPRO-1080] Update syncope question language

---

src/Controller/BiobankController.php
src/Entity/Order.php
tests/Entity/OrderTest.php

| Jira Ticket(s)      | HPRO-1086

[HPRO-1086] Biobank – Timestamp Values for Blanks 

---

src/Service/HelpService.php

| Jira Ticket(s)      | HPRO-1087

[HPRO-1087] Add HealthPro SOP Links

---

templates/partials/participant-id-verification.html.twig
web/assets/css/app.css
web/assets/js/views/IdVerification.js

| Jira Ticket(s)      | HPRO-1098

[HPRO-1098] Create id verification help modal

---

src/Form/IdVerificationType.php

| Jira Ticket(s)      | HPRO-1108

[HPRO-1108] Update verification type dropdown text

---

templates/partials/participant-id-verification.html.twig

| Target Release?     | 2.8.2 
| Jira Ticket(s)      | HPRO-1098

[HPRO-1098] Update help text

---

templates/workqueue/index.html.twig

| Target Release?     | 2.8.2 
| Jira Ticket(s)      | HPRO-690

[HPRO-690] Fix colspan in WQ

---

migrations/Version20220504033557.php
src/Entity/Incentive.php
src/Form/IncentiveType.php
templates/partials/participant-incentive.html.twig
web/assets/js/views/Incentive.js

| Jira Ticket(s)      | HPRO-1092

[HPRO-1092] Incentive tracking add declined field

---

src/Form/IncentiveType.php
web/assets/js/views/Incentive.js

| Target Release?     | 2.8.3 
| Jira Ticket(s)      | HPRO-1092

[HPRO-1092] Fix incentive declined issues

---

templates/partials/participant-incentive.html.twig

| Target Release?     | 2.8.3 
| Jira Ticket(s)      | HPRO-1092

[HPRO-1092] Update incentive given label

---

src/Form/IdVerificationType.php

| Target Release?     | 2.8.3 
| Jira Ticket(s)      | HPRO-1133

[HPRO-1133 ]Update biospecimen redraw enum

---

src/Helper/WorkQueue.php
src/Service/WorkQueueService.php
templates/partials/workqueue-advance-filters.html.twig
web/assets/css/app.css
web/assets/js/views/WorkQueueFilters.js

| Jira Ticket(s)      | HPRO-1109

[HPRO-1109] Enable participant lookup when withdrawal status is set

---

src/Controller/IncentiveImportController.php
src/Service/IncentiveImportService.php
templates/incentive/confirmation.html.twig
templates/incentive/import-details.html.twig
web/assets/js/views/IncentiveImport.js

| Jira Ticket(s)      | HPRO-1100

[HPRO-1100] Incentive tracking view import details

---

src/Controller/DeceasedReportsController.php
src/Form/DeceasedReportType.php

| Jira Ticket(s)      | HPRO-1113

[HPRO-1113] Set Next Kin Support Center checked by default for support center view

---

templates/incentive/import-details.html.twig
templates/incentive/import.html.twig
web/assets/js/views/IncentiveImport.js

| Target Release?     | 2.8.4 
| Jira Ticket(s)      | HPRO-1100

[HPRO-1100] Fix import details columns

---

src/Repository/PatientStatusRepository.php
templates/partials/patient-status-history-dl.html.twig

| Target Release?     | 2.8.4 
| Jira Ticket(s)      | HPRO-1103

[HPRO-1103] Display imported badge for patient status history

---

src/Controller/IdVerificationImportController.php
src/Entity/IdVerificationImport.php
src/Service/IdVerificationImportService.php
src/Service/IncentiveImportService.php
src/Service/PatientStatusImportService.php
templates/idverification/import-details.html.twig
tests/Service/IdVerificationImportServiceTest.php
tests/Service/IncentiveImportServiceTest.php
web/assets/js/views/IdVerificationImport.js

| Bug fix?            |❌ 
| Jira Ticket(s)      | HPRO-1107

[HPRO-1107] Id verification import details

---

README.md
composer.json
docker-compose.yml
package-lock.json

| Jira Ticket(s)      | HPRO-1143

[HPRO-1143] Update README and other config for new installation of project

---

src/Service/HelpService.php

| Jira Ticket(s)      | HPRO-1142

[HPRO-1142] Add patient status & import feature sop links

---

cron.yaml.dist
src/Controller/CronController.php
src/Entity/IdVerificationImportRow.php
src/Entity/IncentiveImport.php
src/Entity/IncentiveImportRow.php
src/Entity/PatientStatusHistory.php
src/Entity/PatientStatusImport.php
src/Helper/Import.php
src/Repository/IdVerificationImportRowRepository.php
src/Service/IdVerificationImportService.php
src/Service/IdVerificationService.php
src/Service/IncentiveImportService.php
src/Service/PatientStatusService.php
templates/partials/participant-id-verification.html.twig
tests/Repository/IdVerificationImportRowRepositoryTest.php
tests/Repository/IncentiveImportRowRepositoryTest.php
tests/Service/IdVerificationImportServiceTest.php
tests/Service/IdVerificationServiceTest.php

| Jira Ticket(s)      | HPRO-1105

[HPRO-1105] ID verification cron job

---

templates/idverification/import.html.twig

| Target Release?     | 2.8.5 

Release 2.8.5 fixes

---

src/Controller/PatientStatusController.php
src/Helper/Import.php
src/Service/PatientStatusImportService.php

| Target Release?     | 2.8.5 

Release 2.8.5 Fixes - Fix import helper hasDuplicateParticipantId method

---

src/Controller/OnSiteDetailsReportingController.php
src/EventListener/RequestListener.php
src/Repository/PatientStatusRepository.php
src/Service/OnSiteDetailsReportingService.php
templates/base.html.twig
templates/onsite/patient-status.html.twig
tests/Repository/PatientStatusRepositoryTest.php
tests/Service/OnSiteDetailsReportingServiceTest.php
web/assets/css/app.css
web/assets/js/app.js
web/assets/js/parsley-validator.js
web/assets/js/views/OnSitePatientStatus.js
webpack.config.js

| Jira Ticket(s)      | HPRO-1136

[HPRO-1136] On site details reporting patient status

---

src/Controller/BaseController.php
src/Controller/OnSiteDetailsReportingController.php
src/Entity/Incentive.php
src/Entity/PatientStatus.php
src/EventListener/RequestListener.php
src/Repository/IncentiveRepository.php
src/Repository/PatientStatusRepository.php
src/Service/IncentiveImportService.php
src/Service/OnSiteDetailsReportingService.php
templates/onsite/incentive-tracking.html.twig
templates/onsite/partials/_page_heading.html.twig
templates/onsite/partials/paging_export.html.twig
templates/onsite/partials/participant-id-filter.html.twig
templates/onsite/patient-status.html.twig
templates/workqueue/consents.html.twig
templates/workqueue/index.html.twig
tests/Repository/IncentiveRepositoryTest.php
tests/Repository/PatientStatusRepositoryTest.php
tests/Service/OnSiteDetailsReportingServiceTest.php
web/assets/js/views/ExportWarningModal.js
web/assets/js/views/OnSiteIncentiveTracking.js
web/assets/js/views/OnSitePatientStatus.js
web/assets/js/views/workqueue.js
webpack.config.js

| Jira Ticket(s)      | HPRO-1135

[HPRO-1135] On site incentive tracking

---

templates/base.html.twig
templates/index.html.twig

| Target Release?     | 2.8.6 
| Jira Ticket(s)      | HPRO-1136

[HPRO-1136] On-site details reporting fixes

---

src/Controller/OnSiteDetailsReportingController.php
templates/onsite/partials/paging_export.html.twig

| Target Release?     | 2.8.6 
| Jira Ticket(s)      | HPRO-1136

[HPRO-1136] Fix On-site details reporting filter & export issues

---

src/Repository/IncentiveRepository.php
src/Repository/PatientStatusRepository.php
tests/Repository/IncentiveRepositoryTest.php
tests/Repository/PatientStatusRepositoryTest.php

| Target Release?     | 2.8.6 
| Jira Ticket(s)      | HPRO-1135

[HPRO-1135] Fix On-site reporting filters end date issue

---

src/Controller/AccessManagementController.php
src/Service/GoogleGroupsService.php
templates/accessmanagement/add-member.html.twig
web/assets/css/app.css

| Jira Ticket(s)      | HPRO-1101

[HPRO-1101] Add mfa check while adding users to a group

---

templates/partials/workqueue-participant-lookup.html.twig

| New configuration?  |❌ 
| Jira Ticket(s)      | HPRO-1034

[HPRO-1034] Add placeholders in the WQ participant lookup

---

templates/base.html.twig

| Jira Ticket(s)      | HPRO-1145

[HPRO-1145] Fix typo

---

src/Helper/WorkQueue.php
templates/partials/workqueue-filters-text.html.twig
tests/Helper/WorkQueueTest.php

| Target Release?     | 2.8.7 
| Jira Ticket(s)      | HPRO-1085

[HPRO-1085] Fix option values display text

---

src/Helper/Participant.php
tests/Helper/ParticipantTest.php

| Target Release?     | 2.8.7.1 
| Jira Ticket(s)      | HPRO-1153

[HPRO-1153] Handle upcoming physical measurements fields changes on RDR participant summary API in HealthPro

---

src/Helper/WorkQueue.php
templates/workqueue/index.html.twig
tests/Service/WorkQueueServiceTest.php
tests/Service/data/participant_summary_search.json

| Jira Ticket(s)      | HPRO-1134

[HPRO-1134] Add IDV Column to WQ

---

src/Helper/WorkQueue.php

| Target Release?     | 2.8.7.1
| Jira Ticket(s)      | HPRO-1153

[HPRO-1153] Disable sort for PM fields

---

src/Helper/WorkQueue.php

| Target Release?     | 2.8.8
| Jira Ticket(s)      | HPRO-1124

[HPRO-1124] Disable sort for Bio-specimens Site field

---

templates/participant/details.html.twig
templates/workqueue/index.html.twig
web/assets/css/app.css

| Target Release?     | 2.8.8 

Release 2.8.8 fixes

---

src/Controller/DefaultController.php
src/Entity/FeatureNotification.php
src/EventListener/RequestListener.php
src/Repository/FeatureNotificationRepository.php
templates/base.html.twig
templates/notifications-modal.html.twig
templates/partials/notifications-confluence-link.html.twig
templates/partials/notifications-dropdown.html.twig
web/assets/css/app.css
web/assets/js/app.js

| Target Release?     | /Next available 
| Jira Ticket(s)      | HPRO-1114

[HPRO-1114] New feature notification UI

---

migrations/Version20220808153750.php
src/Controller/DefaultController.php
src/Entity/FeatureNotificationUserMap.php
src/EventListener/RequestListener.php
src/Repository/FeatureNotificationRepository.php
src/Repository/FeatureNotificationUserMapRepository.php
src/Service/UserService.php
templates/base.html.twig
templates/partials/notifications-dropdown.html.twig
web/assets/js/app.js

| Jira Ticket(s)      | HPRO-1115

[HPRO-1115] New Feature Notifications - Customize View Per User

---

migrations/Version20220810214346.php
src/Controller/ReviewController.php
src/Helper/Participant.php
src/Service/ReviewService.php
templates/review/today.html.twig
web/assets/js/views/today.js

| Jira Ticket(s)      | HPRO-1121

[HPRO-1121] Add On-Site details incentive column in todays participant review page

---

src/Controller/FeatureNotificationController.php
src/Controller/WorkQueueController.php
src/Helper/WorkQueue.php
templates/base.html.twig
templates/macros/display-text.html.twig
templates/notifications-modal.html.twig
templates/partials/notifications-dropdown.html.twig
web/assets/js/views/FeatureNotification.js

| Target Release?     | 2.8.9 
| Jira Ticket(s)      | HPRO-1115

Release 2.8.9 Fixes

---

templates/macros/display-text.html.twig

| Target Release?     | 2.8.9 
| Jira Ticket(s)      | HPRO-1146

[HPRO-1146 ]Display green check for consent in participant overview tab

---

templates/macros/display-text.html.twig

| Target Release?     | 2.8.9 
| Jira Ticket(s)      | HPRO-1146

[HPRO-1146] Display green check for SUBMITTED consent else display red cross

---

config/packages/security.yaml
web/assets/js/views/workqueue.js

| Target Release?     | 2.8.9 
| Jira Ticket(s)      | HPRO-1114

[HPRO-1114] Allow awardee, biobank, scripps users to view notification details and fix WQ default sort

---

src/Controller/ParticipantDetailsController.php
templates/macros/display-text.html.twig
templates/partials/participant-id-verification.html.twig
templates/partials/participant-incentive.html.twig
templates/partials/participant-organization-patient-status-details.html.twig
templates/partials/participant-patient-status.html.twig
templates/partials/patient-status-history-list.html.twig
web/assets/css/app.css
web/assets/js/views/IdVerification.js
web/assets/js/views/Incentive.js

| Jira Ticket(s)      | HPRO-1076

[HPRO-1076] On-Site Details Forms – Flash Message, UI Updates

---

migrations/Version20220815203359.php
migrations/Version20220816153624.php
src/Entity/WorkqueueView.php

| Jira Ticket(s)      | HPRO-1149

[HPRO-1149] Customized WQ create entity

---

web/assets/js/views/ExportWarningModal.js

| Jira Ticket(s)      | HPRO-1074

[HPRO-1074] Change contact email in WQ warning modal

---

web/assets/js/views/FeatureNotification.js

| Jira Ticket(s)      | HPRO-1163

[HPRO-1163] Fix notification view new feature dropdown help & review urls

---

templates/partials/participant-organization-patient-status-details.html.twig
templates/partials/participant-patient-status.html.twig
web/assets/css/app.css

| Target Release?     | 2.9.0
| Jira Ticket(s)      | HPRO-1076

[HPRO-1076] On site details fix UI

---

web/assets/js/views/Incentive.js

| Jira Ticket(s)      | HPRO-1116

[HPRO-1116] Fix incentive type field promotional value validation issue

---

web/assets/js/views/Incentive.js

| Jira Ticket(s)      | HPRO-1167

[HPRO-1167] Fix incentive form submit issue

---

web/assets/js/views/Incentive.js

| Database migration? |/❌ 
| Jira Ticket(s)      | HPRO-1167

[HPRO-1167] For promotional item remove required attribute for amount field

---

src/Service/HelpService.php

| Jira Ticket(s)      | HPRO-1165

[HPRO-1165] Update confluence links

---

templates/notifications-modal.html.twig
templates/partials/notifications-dropdown.html.twig

| Jira Ticket(s)      | HPRO-1166

[HPRO-1166] Display line breaks in the feature notifications dropdown and modal

---

src/Controller/ReviewController.php

| Target Release?     | 2.9.1 
| Jira Ticket(s)      | HPRO-1156

[HPRO-1156] Increase date range from 7 to 30 days

---

migrations/Version20220901210751.php
src/Controller/ReviewController.php
src/Controller/WorkQueueController.php
src/Entity/WorkqueueView.php
src/Service/HelpService.php
src/Service/WorkQueueService.php
templates/notifications-modal.html.twig
templates/partials/notifications-dropdown.html.twig
templates/partials/workqueue-columns.html.twig
templates/partials/workqueue-page-export.html.twig
templates/workqueue/_page_heading.html.twig
templates/workqueue/index.html.twig
tests/Controller/AuthControllerTest.php
web/assets/js/views/Incentive.js
web/assets/js/views/WorkQueueViews.js

| Jira Ticket(s)      | HPRO-1151

[HPRO-1151] Implement Customized Work Queue

---

src/Controller/OrderController.php
src/Form/OrderType.php
templates/order/finalize.html.twig
web/assets/js/views/FinalizeOrder.js

| Jira Ticket(s)      | HPRO-1160

[HPRO-1160] Require DV Sites to Enter FedEx Tracking Number

---

migrations/Version20220913185859.php
src/Controller/ParticipantDetailsController.php
src/Entity/IdVerification.php
src/Service/IdVerificationImportService.php
src/Service/IdVerificationService.php
src/Service/ReviewService.php
templates/partials/participant-id-verification.html.twig
templates/review/today.html.twig
tests/Service/IdVerificationImportServiceTest.php
tests/Service/IdVerificationServiceTest.php
web/assets/js/views/today.js

| Jira Ticket(s)      | HPRO-1169

[HPRO-1169] Save ID verifications in HealthPro db and add IDV column in todays participant review page

---

templates/review/today.html.twig

| Jira Ticket(s)      | HPRO-1169

[HPRO-1169] Fix max count in todays review page

---

templates/biobank/order-quanum.html.twig
templates/biobank/order.html.twig

| Target Release?     | 2.9.2
| Jira Ticket(s)      | HPRO-1160

[HPRO-1160] Add tracking number in biobank order details page

---

src/Controller/OnSiteDetailsReportingController.php
src/EventListener/RequestListener.php
src/Repository/IdVerificationRepository.php
src/Service/OnSiteDetailsReportingService.php
templates/base.html.twig
templates/onsite/id-verification.html.twig
templates/onsite/partials/_page_heading.html.twig
tests/Repository/IdVerificationRepositoryTest.php
tests/Service/OnSiteDetailsReportingServiceTest.php
web/assets/js/views/OnSiteIdVerification.js
webpack.config.js

| Jira Ticket(s)      | HPRO-1141

[HPRO-1141] Create ID verification reporting tool

---

src/Form/OrderType.php
templates/macros/form-render.html.twig
templates/order/process.html.twig

| Target Release?     | 2.9.3 
| Jira Ticket(s)      | HPRO-1171

[HPRO-1171] DV centrifuge selection update

---

src/Helper/WorkQueue.php
tests/Service/WorkQueueServiceTest.php
tests/Service/data/participant_summary_search.json

| Target Release?     | 2.9.3 
| Jira Ticket(s)      | HPRO-1188

[HPRO-1188] Add Life Functioning survey field

---

src/Controller/ParticipantDetailsController.php
templates/partials/participant-id-verification.html.twig

| Target Release?     | 2.9.2.1 
| Jira Ticket(s)      | HPRO-1195

[HPRO-1195] Fetch IDV histories from RDR

---

dev_config/config.yml.dist

| Jira Ticket(s)      | HPRO-1186

[HPRO-1186] Specify to get RDR key from secret manager

---

README.md

| Composer updates?   |❌ 
| Jira Ticket(s)      | HPRO-1186 
Adding more details and WSL-specific notes for the Google Cloud installation section of the README.md file.

Update WSL directions in README.md

---

src/Service/GoogleGroupsService.php

| Jira Ticket(s)      | HPRO-1196

[HPRO-1196] Fix local google groups bypass issue

---

composer.lock

| New feature?        |❌ 
| Jira Ticket(s)      | HPRO-1201
Fix this below vulnerability
https://symfony.com/blog/twig-security-release-possibility-to-load-a-template-outside-a-configured-directory-when-using-the-filesystem-loader

[HPRO-1201] Upgrade twig bundle to fix security vulnerability

---

src/Controller/WorkQueueController.php
src/Entity/WorkqueueView.php
src/Form/WorkQueueViewUpdateType.php
src/Helper/WorkQueue.php
src/Repository/WorkqueueViewRepository.php
templates/workqueue/_page_heading.html.twig
templates/workqueue/consents.html.twig
templates/workqueue/index.html.twig
templates/workqueue/partials/delete-view-modal.html.twig
templates/workqueue/partials/manage-views-modal.html.twig
templates/workqueue/partials/save-manage-view-buttons.twig
templates/workqueue/partials/save-view-modal.html.twig
tests/Repository/WorkqueueViewRepositoryTest.php
web/assets/css/app.css
web/assets/js/views/WorkQueueViews.js
web/assets/js/views/workqueue.js

| Jira Ticket(s)      | HPRO-1185

[HPRO-1185] Customized WorkQueue Updates

---

src/Controller/MeasurementsController.php
src/Service/HelpService.php
templates/measurementform/0.3-blood-donor.html.twig
templates/measurementform/0.3-ehr.html.twig
templates/measurementform/0.3.html.twig
tests/Service/HelpServiceTest.php

| Jira Ticket(s)      | HPRO-1046 
Adds links to SOP's for measurement processes. Clicking links open SOP's in new tab.

[HPRO-1046] Edited templates and added method for sop titles

---

src/Controller/WorkQueueController.php
src/Entity/WorkqueueView.php
src/Form/WorkQueueViewType.php
templates/workqueue/_page_heading.html.twig
templates/workqueue/partials/delete-view-modal.html.twig
templates/workqueue/partials/manage-views-modal.html.twig
templates/workqueue/partials/save-manage-view-buttons.twig
templates/workqueue/partials/save-view-modal.html.twig
web/assets/css/app.css
web/assets/js/views/WorkQueueConsents.js
web/assets/js/views/WorkQueueViews.js
web/assets/js/views/workqueue.js

| Target Release?     | 2.9.4 
| Jira Ticket(s)      | HPRO-1185

[HPRO-1185] Customized WQ Fixes

---

src/Service/WorkQueueService.php

| Target Release?     | 2.9.4.1
| Jira Ticket(s)      | HPRO-1228

[HPRO-1228] Fix WQ site & org filter unpaired option issue

---

src/Controller/DefaultController.php
src/EventListener/RequestListener.php
src/Service/SiteService.php
templates/base.html.twig
web/assets/css/app.css

| Jira Ticket(s)      | HPRO-1199 
**Screenshots:**

[HPRO-1199] Implement nav bar switch program dropdown

---

config/packages/security.yaml
dev_config/config.yml.dist
migrations/Version20221018202212.php
src/Audit/Log.php
src/Controller/DefaultController.php
src/Controller/NphAdminController.php
src/Entity/NphSite.php
src/EventListener/RequestListener.php
src/Form/NphSiteType.php
src/Repository/NphSiteRepository.php
src/Security/User.php
src/Service/SiteService.php
templates/base.html.twig
templates/nphadmin/sites/edit.html.twig
web/assets/css/app.css

| NPM updates?        |/❌ 
| Jira Ticket(s)      | HPRO-1211

[HPRO-1211]  Implement NPH admin site create/edit/delete

---

src/Controller/ParticipantDetailsController.php
src/Helper/WorkQueue.php
templates/participant/details.html.twig
templates/workqueue/partials/consent-modal.html.twig

| Target Release?     | 2.9.5
| Jira Ticket(s)      | HPRO-1230

[HPRO-1230] Replace typo field with correct field

---

src/Helper/Participant.php
templates/biobank/participant.html.twig

| Jira Ticket(s)      | HPRO-1172 
Display a patients AI/AN status in the biobank view.

[HPRO-1172] Biobank AI/AN Status display

---

src/Helper/WorkQueue.php
src/Repository/IncentiveRepository.php
tests/Helper/WorkQueueTest.php
tests/Service/data/participant_summary_search.json

| Target Release?     | 2.9.5 
| Jira Ticket(s)      | HPRO-1168

[HPRO-1168] Remove deleted incentive in on-site reporting & WQ pages

---

src/Helper/Participant.php
templates/biobank/participant.html.twig

Reverting this as RDR has some work to complete for participants that have identified ‘more than one race.'

Revert "[HPRO-1172] Biobank AI/AN Status display"

---

migrations/Version20221102213643.php
src/Entity/NphAliquot.php
src/Entity/NphOrder.php
src/Entity/NphSample.php
src/Repository/NphAliquotRepository.php
src/Repository/NphOrderRepository.php
src/Repository/NphSampleRepository.php

| Jira Ticket(s)      | HPRO-1239

[HPRO-1239] Create entities for NPH order workflow

---

src/Controller/NphOrderController.php
src/Form/Nph/NphOrderType.php
src/Nph/Order/Samples.php
src/Nph/Order/Samples/Module1.json
src/Nph/Order/Visits/VisitLMT.php
src/Service/Nph/NphOrderService.php
templates/program/nph/order/generate-orders.html.twig
templates/program/nph/order/samples.html.twig
web/assets/css/app.css

| Jira Ticket(s)      | HPRO-1241

[HPRO-1241] Save module 1 create orders and samples in db

---

src/Controller/NphOrderController.php
src/Form/Nph/NphOrderType.php
src/Nph/Order/Modules/Module1.php
src/Nph/Order/Modules/Module2.php
src/Nph/Order/Modules/Module3.php
src/Nph/Order/Samples.php
src/Nph/Order/TimePoints.php
src/Service/Nph/NphOrderService.php
templates/program/nph/order/generate-orders.html.twig
templates/program/nph/order/samples.html.twig
web/assets/js/views/NphOrderCreate.js
webpack.config.js

| Jira Ticket(s)      | HPRO-1254

[HPRO-1254] Implement orders review and submit

---

src/Controller/NphOrderController.php
src/Form/Nph/NphSampleFinalizeType.php
templates/program/nph/order/sample-finalize.html.twig
web/assets/js/views/NphSampleFinalize.js

| Jira Ticket(s)      | HPRO-1284

[HPRO-1284] Implement add delete aliquot samples

---

src/Controller/NphParticipantSummaryController.php
src/Nph/Order/Modules/Module1.php
src/Nph/Order/Modules/Module2.php
src/Nph/Order/Modules/Module3.php
src/Nph/Order/Samples/Module2.json
src/Service/Nph/NphProgramSummaryService.php
templates/program/nph/order/label-print.html.twig
templates/program/nph/participant/index.html.twig
tests/Service/NphProgramSummaryServiceTest.php
web/assets/js/views/NphParticipantSummary.js
webpack.config.js

| Jira Ticket(s)      | HPRO-1152

[HPRO-1152] Participant Summary Page

---

src/Controller/NphParticipantSummaryController.php
templates/program/nph/order/label-print.html.twig

| Jira Ticket(s)      | HPRO-1226

[HPRO-1226] Missed updating casing in participant summary route.

---

src/Security/User.php
templates/program/nph/admin/index.html.twig
templates/program/nph/navbar.html.twig

| Jira Ticket(s)      | HPRO-1296

[HPRO-1296] Fix nph admin links

---

templates/login.html.twig
web/assets/css/login.css

| Jira Ticket(s)      | HPRO-1200

[HPRO-1200] NPH Carousel Adjustments

---

templates/program-select.html.twig

| Jira Ticket(s)      | HPRO-1206 
Swapped NPH and AOU program select.

[HPRO-1206] Swapped AOU and NPH programs.

---

templates/program/nph/navbar.html.twig
web/assets/css/app.css
web/assets/css/hpo.css
web/assets/css/nph.css

| Jira Ticket(s)      | HPRO-1203 
Removed help and translation dropdown. Changed text to white for NPH navbar.

[HPRO-1203] Change NPH Navbar Text to white. Remove Help and Translation from NPH.

---

src/Controller/NphOrderController.php
src/Form/Nph/NphOrderCollect.php
src/Service/Nph/NphOrderService.php
templates/program/nph/order/collect.html.twig
tests/Service/NphOrderServiceTest.php
web/assets/js/views/NphOrder.js

| Jira Ticket(s)      | HPRO-1291

[HPRO-1291] Order collect implement barcode scan

---

templates/program/nph/navbar.html.twig

| Jira Ticket(s)      | HPRO-1203 
Before:
After:

[HPRO-1203] Remove notification dropdown from NPH navbar.

---

src/Controller/NphOrderController.php
src/Form/Nph/NphSampleFinalizeType.php
src/Nph/Order/Samples.php
src/Service/Nph/NphOrderService.php
templates/program/nph/order/partials/participant-details-with-name.html.twig
templates/program/nph/order/partials/participant-details.html.twig
templates/program/nph/order/sample-finalize.html.twig

| Jira Ticket(s)      | HPRO-1295

[HPRO-1295] Implement aliquot stool samples

---

migrations/Version20221219195323.php
migrations/Version20221220192629.php
src/Controller/NphOrderController.php
src/Entity/NphOrder.php
src/Form/Nph/NphOrderModifyType.php
src/Service/Nph/NphOrderService.php
templates/program/nph/order/collect.html.twig
templates/program/nph/order/order-modify.html.twig
templates/program/nph/order/partials/order-header.html.twig
templates/program/nph/order/partials/order-participant-details-barcode.html.twig
templates/program/nph/order/sample-finalize.html.twig
tests/Service/NphOrderServiceTest.php
web/assets/js/views/NphOrderModify.js
webpack.config.js

| Jira Ticket(s)      | HPRO-1292

[HPRO-1292] Implement order cancel

---

src/Helper/Participant.php
templates/biobank/participant.html.twig

| Jira Ticket(s)      | HPRO-1172 
[HPRO-1172]: https://precisionmedicineinitiative.atlassian.net/browse/HPRO-1172?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

[HPRO-1172] Added is AI/AN status to biobank view.

---

migrations/Version20221227172800.php
src/Controller/NphOrderController.php
src/Entity/NphOrder.php
src/Entity/NphSample.php
src/Form/Nph/NphOrderCollect.php
src/Form/Nph/NphOrderForm.php
src/Form/Nph/NphOrderModifyType.php
src/Form/Nph/NphSampleModifyType.php
src/Service/Nph/NphOrderService.php
templates/program/nph/order/collect.html.twig
templates/program/nph/order/macros/display-text.html.twig
templates/program/nph/order/partials/order-header.html.twig
templates/program/nph/order/sample-finalize.html.twig
tests/Service/NphOrderServiceTest.php
web/assets/js/views/NphOrderModify.js

| Jira Ticket(s)      | HPRO-1302

[HPRO-1302] Implement NPH Sample Cancel

---

templates/biobank/participant.html.twig

| Jira Ticket(s)      | HPRO-1172

[HPRO-1172] Change Checkmark to Yes/No

---

migrations/Version20230110200343.php
src/Controller/NphOrderController.php
src/Entity/NphAliquot.php
src/Entity/NphSample.php
src/Form/Nph/NphSampleFinalizeType.php
src/Service/Nph/NphOrderService.php
templates/program/nph/order/macros/display-text.html.twig
templates/program/nph/order/sample-finalize.html.twig
templates/program/nph/order/sample-modify.html.twig
tests/Entity/NphSampleTest.php
tests/Entity/NphTestCase.php
tests/Service/NphOrderServiceTest.php
web/assets/js/views/NphSampleFinalize.js

| Jira Ticket(s)      | HPRO-1311

[HPRO-1311] Implement aliquot samples cancel and restore

---

migrations/Version20230113194633.php
src/Entity/NphSite.php
src/Form/NphSiteType.php
templates/program/nph/admin/sites/index.html.twig

| Jira Ticket(s)      | HPRO-1314

[HPRO-1314] Add mayo client id to NPH site form

---

templates/program/nph/participant/index.html.twig
web/assets/css/nph.css

| Jira Ticket(s)      | HPRO-1178

[HPRO-1178] Participant Summary Page Feedback

---

config/packages/security.yaml
src/Controller/DefaultController.php
templates/program/nph/index.html.twig
templates/program/nph/navbar.html.twig
templates/program/nph/order/samples.html.twig

| Jira Ticket(s)      | HPRO-1323

[HPRO-1323] Fix permission issues for users having only NPH site access

---

cron.yaml.dist
src/Controller/CronController.php
src/Service/HFHRepairService.php
tests/HenryFordRepairTest.php

| Jira Ticket(s)      | HPRO-1216
Adds a cron to repair site participants.

[HPRO-1216] Henry Ford Repair

---

src/Controller/HelpController.php
src/Service/HelpService.php
templates/help/sop-pdf.html.twig
templates/help/sop.html.twig

| Jira Ticket(s)      | HPRO-1321 HPRO-1209

[HPRO-1321] Added spanish SOP's, HPRO SOP-006

---

templates/program/nph/navbar.html.twig

| Jira Ticket(s)      | HPRO-1199

[HPRO-1199] Fix NPH navbar

---

src/Service/HFHRepairService.php

| Jira Ticket(s)      | HPRO-1216

[HPRO-1216] move flush and removal of CSV data to outside of if condition

---

templates/measurementform/0.3-blood-donor.html.twig
templates/measurementform/0.3-ehr.html.twig
templates/measurementform/0.3.html.twig

| Jira Ticket(s)      | HPRO-1321

[HPRO-1321] Added english language to measurement forms SOP links.

---

migrations/Version20230123172719.php
src/Controller/NphAdminController.php
src/Entity/NphSite.php
src/Form/NphSiteType.php
templates/program/nph/admin/sites/index.html.twig

| Jira Ticket(s)      | HPRO-1325

[HPRO-1325] NPH - Remove centrifuge and site type fields from Site form

---

src/Service/HFHRepairService.php

| Jira Ticket(s)      | HPRO-1216

[HPRO-1216] Change cron to log an issue instead of throwing an exception.

---

migrations/Version20230118144015.php
src/Controller/NphOrderController.php
src/Controller/NphPDFController.php
src/Entity/NphOrder.php
src/Entity/NphSample.php
src/Repository/NphOrderRepository.php
src/Service/Nph/NphOrderService.php
templates/program/nph/order/label-print.html.twig
templates/program/nph/order/samples.html.twig
templates/program/nph/participant/index.html.twig
tests/Repository/NphOrderRepositoryTest.php
tests/Service/NphOrderServiceTest.php
tests/testSetup.php
web/assets/js/views/NphOrderCreate.js

| Jira Ticket(s)      | HPRO-1318

[HPRO-1318] Group samples/orders based upon when they're made.

---

templates/program/nph/participant/index.html.twig

| Jira Ticket(s)      | HPRO-1335

[HPRO-1335] Hide modules 2 and 3, remove consent status

---

src/Form/Nph/NphSampleFinalizeType.php
src/Helper/NphParticipant.php
src/Service/Nph/NphOrderService.php
src/Service/SiteService.php
templates/program/nph/order/partials/participant-details-with-name.html.twig
templates/program/nph/order/partials/participant-details.html.twig
templates/program/nph/order/sample-finalize.html.twig
templates/program/nph/order/samples.html.twig
tests/Service/SiteServiceTest.php

| Bug fix?            | ✅  
| New feature?        | ❌
| Jira Ticket(s)      | HPRO-.1336

[HPRO-1336] Fix site id display name and other issues

---

src/Service/PDFService.php

| Jira Ticket(s)      | HPRO-1231

[HPRO-1231] Set PDF generation to /tmp directory.

---

templates/program/nph/order/generate-orders.html.twig
templates/program/nph/order/label-print.html.twig
web/assets/css/nph.css

| Jira Ticket(s)      | HPRO-1307

[HPRO-1307] Updated NPH Colors According to feedback.

---

src/Controller/NphOrderLookupController.php
src/Repository/NphOrderRepository.php
templates/program/nph/index.html.twig
templates/program/nph/navbar.html.twig
templates/program/nph/order/orderlookup.html.twig
tests/Repository/NphOrderRepositoryTest.php

| Jira Ticket(s)      | HPRO-1218

[HPRO-1218] Nph Order Lookup

---

src/Entity/NphSample.php
src/Nph/Order/Samples.php
src/Nph/Order/TimePoints.php
src/Nph/Order/Visits/VisitLMT.php
src/Service/Nph/NphOrderService.php
tests/Entity/NphSampleTest.php
tests/Service/NphOrderServiceTest.php
tests/Service/data/order_module_1.json

| Jira Ticket(s)      | HPRO-1340

[HPRO-1340] NPH - Change order payload

---

src/Service/Nph/NphOrderService.php
templates/program/nph/order/samples.html.twig
web/assets/js/views/NphOrderCreate.js

| Jira Ticket(s)      | HPRO-1326

[HRPO-1326] Allow generate new samples for cancelled samples

---

web/assets/js/views/NphOrder.js
web/assets/js/views/NphSampleFinalize.js

| Composer updates?   |❌ 
| Jira Ticket(s)      | HPRO-1291

[HPRO-1291] Implement auto select timestamp on barcode scan

---

src/Entity/NphSample.php
templates/program/nph/order/sample-finalize.html.twig
tests/Entity/NphSampleTest.php

| Jira Ticket(s)      | HPRO-1343

[HPRO-1343] Remove add line for non blood samples

---

src/Form/Nph/NphSampleFinalizeType.php
src/Service/Nph/NphOrderService.php
web/assets/js/views/NphSampleFinalize.js

| Jira Ticket(s)      | HPRO-1345

[HPRO-1345] Fix non blood samples finalization issue

---

templates/program/hpo/index.html.twig

| Jira Ticket(s)      | HPRO-1346

[HPRO-1346] Fix display work queue box in the AOU home page

---

src/Controller/NphOrderController.php
src/Service/Nph/NphOrderService.php

| Jira Ticket(s)      | HPRO-1345

[HPRO-1345] Fix notes field sample finalize issue 

---

src/Controller/NphOrderController.php
src/Nph/Order/Modules/Module2.php
src/Nph/Order/Modules/Module3.php
src/Nph/Order/Samples/Module3.json
src/Nph/Order/Visits/Visit3Diet.php
src/Nph/Order/Visits/VisitDLW.php
src/Nph/Order/Visits/VisitDSMT.php
src/Nph/Order/Visits/VisitLMT.php
src/Service/Nph/NphOrderService.php
src/Service/Nph/NphProgramSummaryService.php
src/Service/PDFService.php
templates/program/nph/order/generate-orders.html.twig
templates/program/nph/order/label-print.html.twig
templates/program/nph/order/partials/generate-orders-header.html.twig
templates/program/nph/participant/index.html.twig
tests/Service/NphOrderServiceTest.php
tests/Service/NphProgramSummaryServiceTest.php
tests/Service/data/order_module_1.json

| Jira Ticket(s)      | HPRO-1327

[HPRO-1327] Changed Timepoints to match Biobank requirements.

---

src/Service/Nph/NphParticipantSummaryService.php

| Jira Ticket(s)      | HPRO-1334

[HPRO-1334] Participant look up implement DOB validations

---

src/Nph/Order/Samples/Module1.json

| Jira Ticket(s)      | HPRO-1353

[HPRO-1353] Change aliquot identifier EDPAP1 to EDTAP1

---

src/Controller/NphOrderController.php
src/Entity/NphSample.php
src/Form/Nph/NphSampleRevertType.php
templates/program/nph/order/sample-finalize.html.twig

| Jira Ticket(s)      | HPRO-1338

[HPRO-1338] Implement sample revert

---

src/Controller/NphOrderController.php
src/Form/Nph/NphOrderType.php
src/Service/Nph/NphOrderService.php
templates/program/nph/order/generate-orders.html.twig
templates/program/nph/order/samples.html.twig
tests/Service/NphOrderServiceTest.php
web/assets/js/views/NphOrderCreate.js

| Jira Ticket(s)      | HPRO-1341

[HPRO-1341] Validate generate orders page

---

src/Form/Nph/NphOrderType.php
web/assets/js/views/NphOrderCreate.js

| Jira Ticket(s)      | HPRO-1341

[HPRO-1341] Fix disabled stool samples validation issues

---

src/Nph/Order/Visits/VisitDSMT.php
src/Nph/Order/Visits/VisitLMT.php
tests/Service/NphOrderServiceTest.php
tests/Service/data/order_module_1.json

| Jira Ticket(s)      | HPRO-1327

[HPRO-1327] Update timepoint UI display names.

---

src/Form/Nph/NphSampleFinalizeType.php
web/assets/js/views/NphSampleFinalize.js

| Jira Ticket(s)      | HPRO-1291

[HPRO-1291] Implement auto select aliquot time on barcode scan on sample finalize page

---

src/Controller/NphOrderController.php
src/Form/Nph/NphSampleFinalizeType.php
src/Service/Nph/NphOrderService.php
tests/Service/NphOrderServiceTest.php
web/assets/js/views/NphSampleFinalize.js

| Jira Ticket(s)      | HPRO-1358

[HPRO-1358] Fix duplicate aliquot barcodes and stool tube ids within the form

---

src/Controller/DefaultController.php
src/EventListener/RequestListener.php

| Jira Ticket(s)      | HPRO-1175
https://user-images.githubusercontent.com/6041980/217939559-ab6b2212-d06a-4dea-9853-d668c465e27e.mp4

[HPRO-1175] Fix site switch issues between programs

---

src/Service/TimezoneService.php

| Jira Ticket(s)      | HPRO-1330

[HPRO-1330] Add Atlantic Standard Time to the timezone options

---

src/Controller/NphOrderController.php
src/Nph/Order/Samples.php
templates/program/nph/order/sample-finalize.html.twig

| Jira Ticket(s)      | HPRO-1351

[HPRO-1351] Display aliquots pdf viewer on sample finalize page

---

src/Entity/NphSample.php
src/Form/Nph/NphOrderType.php
src/Service/Nph/NphOrderService.php
tests/Service/NphOrderServiceTest.php
web/assets/js/views/NphOrderCreate.js

| Jira Ticket(s)      | HPRO-1348

[HPRO-1348] Make Stool KIT ID and Tube IDs required when stool sample is checked

---

src/Entity/NphOrder.php
src/Form/Nph/NphSampleFinalizeType.php

| Jira Ticket(s)      | HPRO-1351

[HPRO-1351] Fix volume error messages in sample finalize page

---

migrations/Version20230210142836.php
src/Controller/NphReviewController.php
src/Entity/NphFieldSort.php
src/Repository/NphOrderRepository.php
templates/program/nph/index.html.twig
templates/program/nph/navbar.html.twig
templates/program/nph/review/page_heading.html.twig
templates/program/nph/review/recently_modified.html.twig
templates/program/nph/review/today.html.twig
templates/program/nph/review/unfinalized.html.twig
tests/Repository/NphOrderRepositoryTest.php
web/assets/js/views/NphReview.js
webpack.config.js

[HPRO-1182] Added NPH Participant Review Pages and Tests.

---

src/Service/Nph/NphOrderService.php
templates/program/nph/participant/index.html.twig

| Jira Ticket(s)      | HPRO-1256

[HPRO-1256] Change date format, display no orders generated if none exist.

---

src/Entity/NphSample.php
src/Nph/Order/Samples/Module1.json
src/Nph/Order/Samples/Module2.json
src/Nph/Order/Samples/Module3.json
src/Repository/NphOrderRepository.php
src/Service/Nph/NphOrderService.php
templates/program/nph/order/generate-orders.html.twig
templates/program/nph/order/label-print.html.twig
templates/program/nph/order/sample-finalize.html.twig
templates/program/nph/participant/index.html.twig
tests/Repository/NphOrderRepositoryTest.php
tests/Service/NphOrderServiceTest.php
tests/Service/data/order_module_1.json
web/assets/css/nph.css
web/assets/js/views/NphParticipantSummary.js
web/assets/js/views/NphSampleFinalize.js

| Jira Ticket(s)      | HPRO-1331

[HPRO-1331] Implemented feedback on layout/issues described in ticket.

---

src/Form/Nph/NphSampleModifyType.php
templates/program/nph/order/sample-modify.html.twig
web/assets/js/views/NphOrderModify.js

| Jira Ticket(s)      | HPRO-1342

[HPRO-1342] Implement check all in bulk samples cancel/restore page

---

src/Security/User.php
src/Security/UserProvider.php

| Jira Ticket(s)      | HPRO-1361

[HPRO-1361] Fix NPH management role

---

src/Nph/Order/Samples/Module1.json
src/Nph/Order/Samples/Module2.json

| Jira Ticket(s)      | HPRO-1364

[HPRO-1364] Change aliquot identifiers

---

templates/login.html.twig
web/assets/css/app.css

| Jira Ticket(s)      | HPRO-1352

[HPRO-1352] Added new help links to Login Page.

---

src/Controller/DefaultController.php
src/Service/SiteService.php
tests/Service/SiteServiceTest.php

| Jira Ticket(s)      | HPRO-1175

[HPRO-1175] Fix program switch logout issue

---

src/Entity/NphSample.php
src/Form/Nph/NphSampleFinalizeType.php
src/Service/Nph/NphOrderService.php

| Jira Ticket(s)      | HPRO-1365

[HPRO-1365] Enable urine question sample edit

---

migrations/Version20230210142836.php

[HPRO-1182] Add field encoding and collation on migration.

---

bin/deploy

| Jira Ticket(s)      | HPRO-1337

[HPRO-1337] Added environment check, different command for WSL environment.

---

src/Controller/NphReviewController.php

[HPRO-1182] Change to concrete class references.

---

templates/program/nph/order/sample-modify.html.twig

| Jira Ticket(s)      | HPRO-1342

[HPRO-1342] Change text cancel to restore in samples restore page

---

src/Form/Nph/NphSampleFinalizeType.php

| Jira Ticket(s)      | HPRO-1365

[HPRO-1365] Enable questions while unlocking stool samples

---

src/Entity/NphSample.php
src/Service/Nph/NphOrderService.php
tests/Entity/NphSampleTest.php
tests/Service/NphOrderServiceTest.php

| Jira Ticket(s)      | HPRO-1364

[HPRO-1364] Fix sample identifiers

---

src/Entity/NphSample.php
templates/program/hpo/navbar.html.twig
templates/program/nph/navbar.html.twig
templates/program/nph/order/sample-modify.html.twig

| Jira Ticket(s)      | HPRO-1305

[HPRO-1305] Fix restore options and display text

---

templates/program/nph/review/page_heading.html.twig
templates/program/nph/review/recently_modified.html.twig
templates/program/nph/review/unfinalized.html.twig

| Jira Ticket(s)      | HPRO-1152

[HPRO-1152] Fix links and display of sample status's with modifications.

---

src/Controller/NphReviewController.php
src/Repository/NphOrderRepository.php
templates/program/nph/review/recently_modified.html.twig
templates/program/nph/review/today.html.twig
templates/program/nph/review/unfinalized.html.twig

[HPRO-1182] Updated Missing Links, added modified timestamp, removed seconds.

---

src/Service/SiteService.php

| Jira Ticket(s)      | HPRO-1336

[HPRO-1336] Fix site entity session variable issue

---

src/Form/Nph/NphSampleLookupType.php
templates/program/nph/order/collect.html.twig
templates/program/nph/order/generate-orders.html.twig
templates/program/nph/order/label-print.html.twig
templates/program/nph/order/sample-finalize.html.twig
templates/program/nph/participant/index.html.twig

| Jira Ticket(s)      | HPRO-1355

[HPRO-1355] Changed wording of specimen collection in NPH.

---

src/Controller/NphOrderController.php
src/Entity/NphSample.php
src/Form/Nph/NphSampleFinalizeType.php
src/Service/Nph/NphOrderService.php
templates/program/nph/order/sample-finalize.html.twig
tests/Entity/NphSampleTest.php
web/assets/js/views/NphSampleFinalize.js

| Jira Ticket(s)      | HPRO-1367

[HPRO-1367] Implement aliquot sample edits

---

src/Entity/User.php
src/Security/User.php
src/Security/UserProvider.php
src/Service/SiteService.php
src/Service/UserService.php
tests/Entity/UserTest.php

| Jira Ticket(s)      | HPRO-1362

[HPRO-1362] Prevent cross program access

---

src/Form/Nph/NphSampleFinalizeType.php
templates/program/nph/order/sample-finalize.html.twig
web/assets/js/views/NphSampleFinalize.js

| Jira Ticket(s)      | HPRO-1367

[HPRO-1367] Fix volume field disable/enable issue

---

src/Controller/NphDebugToolsController.php
src/Form/DebugParticipantLookupType.php
src/Service/Nph/NphParticipantSummaryService.php
templates/program/nph/admin/debug/participant.html.twig
templates/program/nph/admin/debug/participants.html.twig
templates/program/nph/admin/index.html.twig

| Jira Ticket(s)      | HPRO-1384

[HPRO-1384] Create NPH admin debug tool for Participants API

---

src/Controller/NphParticipantSummaryController.php

| Jira Ticket(s)      | HPRO-1359

[HPRO-1359] Redirect when trying to access non existent participant page.

---

src/Controller/DeceasedReportsController.php
src/Controller/PatientStatusController.php
src/Service/SiteService.php
tests/Service/SiteServiceTest.php

| Jira Ticket(s)      | HPRO-1393

[HPRO-1393] Fix retrieving organization id from site session entity

---

templates/program/nph/order/generate-orders.html.twig
templates/program/nph/participant/index.html.twig
web/assets/css/nph.css

| Target Release?     | 3.1.0
| Jira Ticket(s)      | HPRO-1355 
Adjust text to what was requested, make collections nav pill same size and module nav.

[HPRO-1355] Fix capitalization, sample collections text, Extra padding collections.

---

src/Entity/NphSample.php
src/Nph/Order/Samples/Module1.json
templates/program/nph/order/sample-finalize.html.twig
tests/Entity/NphSampleTest.php

| Jira Ticket(s)      | HPRO-1376

[HPRO-1376] Remove add new aliquot 500 uL blood samples

---

src/Service/SiteService.php
tests/Service/SiteServiceTest.php

| Jira Ticket(s)      | HPRO-1339

[HPRO-1339] NPH handle misconfigured sites

---

src/Controller/OrderController.php
src/Entity/Order.php
src/Form/OrderType.php
src/Service/OrderService.php
templates/order/finalize.html.twig
tests/Entity/OrderTest.php

| Target Release?     | 3.1.1 
| Jira Ticket(s)      | HPRO-.1399

[HPRO-1399] Revert "[HPRO-1356] Add Fedex Tracking field to HPO order workflow"

---

templates/program/nph/order/collect.html.twig
web/assets/css/nph.css

| Jira Ticket(s)      | HPRO-1375

[HPRO-1375] Closer cancelled banner, Cancelled text under sample.

---

src/Controller/NphOrderController.php
src/Form/Nph/NphOrderCollect.php
src/Form/Nph/NphOrderForm.php
src/Form/Nph/NphSampleFinalizeType.php
src/Service/Nph/NphOrderService.php
web/assets/js/views/NphOrder.js
web/assets/js/views/NphSampleFinalize.js

| Jira Ticket(s)      | HPRO-1357

[HPRO-1357] NPH Order/Sample validate dates

---

templates/program/nph/order/samples.html.twig
web/assets/css/app.css

| Jira Ticket(s)      | HPRO-1373

[HPRO-1373] Emphasize stool tube boxes

---

templates/program/nph/navbar.html.twig

| Jira Ticket(s)      | HPRO-1362

[HPRO-1362] Check for ROLE_NPH_USER role NPH menu items

---

src/Form/Nph/NphSampleFinalizeType.php

| Jira Ticket(s)      | HPRO-1371 
Requested text change.

[HPRO-1371] Remove others are optional text.

---

src/Entity/NphOrder.php
tests/Entity/NphOrderTest.php

| Jira Ticket(s)      | HPRO-1370

[HPRO-1370] Disable collected time only when at least one sample is finalized

---

src/Service/Nph/NphOrderService.php

| Jira Ticket(s)      | HPRO-1370

[HPRO-1370] Fix date comparison issue

---

src/Service/Nph/NphOrderService.php

| Jira Ticket(s)      | HPRO-1370

[HPRO-1370] Fix stool sample finalize issues

---

templates/program/hpo/navbar.html.twig
templates/program/nph/navbar.html.twig
templates/program/nph/order/collect.html.twig
templates/program/nph/order/generate-orders.html.twig
templates/program/nph/order/label-print.html.twig
templates/program/nph/order/partials/generate-orders-header.html.twig
templates/program/nph/order/partials/order-participant-details-barcode.html.twig
templates/program/nph/order/sample-finalize.html.twig
templates/program/nph/order/sample-modify.html.twig
templates/program/nph/order/samples.html.twig
templates/program/nph/participant/index.html.twig
web/assets/css/nph.css
web/assets/js/views/NphOrderCreate.js
web/assets/js/views/NphParticipantSummary.js
web/assets/js/views/NphSampleFinalize.js

| Jira Ticket(s)      | HPRO-1349 
Adjusts styling of several elements across the NPH side according to feedback in this ticket.
https://precisionmedicineinitiative.atlassian.net/browse/HPRO-1349

[HPRO-1349] Adjust styling according to feedback.

---

src/Controller/NphOrderController.php
src/Entity/NphOrder.php
src/Entity/NphSample.php
src/Nph/Order/Modules/Module2.php
src/Nph/Order/Samples/Module2.json
src/Nph/Order/TimePoints.php
src/Nph/Order/Visits/VisitDSMT.php
src/Service/Nph/NphOrderService.php
templates/program/nph/order/generate-orders.html.twig
templates/program/nph/order/sample-finalize.html.twig
tests/Entity/NphSampleTest.php
web/assets/js/views/NphOrderCreate.js

| Jira Ticket(s)      | HPRO-1279

[HPRO-1279] Handle module 2 workflow

---

src/Form/Nph/NphSampleModifyType.php
src/Service/Nph/NphOrderService.php

| Jira Ticket(s)      | HPRO-1412

[HPRO-1412] Order collection page fix form fields disable issue

---

src/Form/Nph/NphSampleLookupType.php

| Jira Ticket(s)      | HPRO-1413

[HPRO-1413] Update sample scan field label

---

src/Controller/NphParticipantSummaryController.php
src/Service/Nph/NphParticipantSummaryService.php
templates/program/nph/participant/index.html.twig
tests/Service/NphParticipantSummaryServiceTest.php
web/assets/css/nph.css

| Jira Ticket(s)      | HPRO-1394

[HPRO-1394] Implement refresh participant data

---

src/Entity/NphOrder.php
src/Form/Nph/NphOrderForm.php
tests/Entity/NphOrderTest.php

| Jira Ticket(s)      | HPRO-1424

[HPRO-1424] NPH add new option for stool questions

---

src/Command/DeployCommand.php

| Target Release?     | 3.3.0
| Jira Ticket(s)      | HPRO-1430 
I ran into an issue where the `git status` command in the deploy script was crashing, thus preventing my Docker container from loading.  In looking through the deploy script, I realized that we were calling `git status` and doing nothing with the result on a non-interactive deploy.  So, I refactored the code to skip the `git status` check on non-interactive deploys.  
While I was in there, I also added types to the constants.  I forgot that we are in PHP 7.4 and can be doing that already.

[HPRO-1430] Skip git status check on no-interaction deploy

---

phpstan.neon
src/Controller/BiobankController.php
src/Entity/Order.php
src/Service/OrderService.php
src/Service/WorkQueueService.php

| Jira Ticket(s)      | HPRO-1427

[HPRO-1427] Increase phpstan level to 5

---

src/Controller/OrderController.php
src/Entity/Order.php
src/Form/OrderType.php
src/Service/OrderService.php
templates/order/finalize.html.twig
tests/Entity/OrderTest.php

| Target Release?     | 3.4.0 
| Jira Ticket(s)      | HPRO-1428

[HPRO-1428] Display Fedex Tracking field for HPO orders

---

templates/program/nph/order/label-print.html.twig
templates/program/nph/participant/index.html.twig

Merging release 3.3.1 into develop

---

templates/program/hpo/navbar.html.twig
templates/program/nph/navbar.html.twig

| Target Release?     | 3.3.2 
| Jira Ticket(s)      | HPRO-1443

[HPRO-1443] Fix navbar program switch issue

---

templates/program/hpo/navbar.html.twig
templates/program/nph/navbar.html.twig

| Target Release?     | 3.3.3 
| Jira Ticket(s)      | HPRO-1450

[HPRO-1450] Fix navbar redirect home page issue

---

config/packages/security.yaml
src/Security/User.php
src/Security/UserProvider.php
templates/program/nph/navbar.html.twig

| Target Release?     | 3.3.3 
| Jira Ticket(s)      | HPRO-1451

[HPRO-1451] Fix for seeing management tools when not allowed.

---

src/Controller/AccessManagementController.php
src/Form/RemoveGroupMemberType.php

| Target Release?     | 3.4.0 
| Jira Ticket(s)      | HPRO-1457

[HPRO-1457] Fix group removal email text

---

.circleci/config.yml
Dockerfile
app.yaml.dist
composer.json
composer.lock
src/Controller/ProblemController.php
src/Datastore/DatastoreSessionHandler.php
tools/php-cs-fixer/composer.json
tools/php-cs-fixer/composer.lock

| Jira Ticket(s)      | HPRO-1433

[HPRO-1433] Migrate php 7 to 8.1

---

src/Helper/NphParticipant.php
templates/program/nph/participant/index.html.twig

| Jira Ticket(s)      | HPRO-1449

[HPRO-1449] Get module from participant object

---

src/Service/HelpService.php
templates/help/sop.html.twig

| Jira Ticket(s)      | HPRO-1446

[HPRO-1446] Added spanish SOP's for Biobank Standard Operating Procedures

---

src/Form/Nph/NphOrderCollect.php
src/Form/Nph/NphOrderForm.php
templates/program/nph/order/sample-finalize.html.twig

| Target Release?     | 3.4.1 
| Jira Ticket(s)      | HPRO-1469

[HPRO-1469] Fix urine & stool samples validation

---

src/Entity/NphSample.php

| Target Release?     | 3.4.1 
| Jira Ticket(s)      | HPRO-1463

[HPRO-1463] Display other reason text for cancelled orders

---

src/Helper/NphParticipant.php
src/Service/Nph/NphParticipantSummaryService.php
tests/Helper/NphParticipantTest.php

| Target Release?     | 3.4.1 
| Jira Ticket(s)      | HPRO-1459

[HPRO-1459] Use NPH date of birth field

---

config/packages/twig.php
migrations/Version20230421204151.php
src/Controller/BaseController.php
src/Controller/BiobankController.php
src/Controller/OrderController.php
src/Entity/Order.php
src/Entity/OrderHistory.php
src/Entity/User.php
src/Repository/OrderRepository.php
src/Service/OrderService.php
templates/biobank/orders-recent-modify.html.twig
templates/biobank/orders-today.html.twig
templates/biobank/orders-unfinalized.html.twig
templates/biobank/orders-unlocked.html.twig
templates/biobank/partials/biobank-order-details.html.twig
templates/macros/display-text.html.twig
templates/partials/participant-orders-list.html.twig
tests/Entity/OrderTest.php
tests/Entity/UserTest.php

| Target Release?     | 3.6.0 
| Jira Ticket(s)      | HPRO-1432

[HPRO-1432] Save and display time zone info for biobank view orders

---

src/Controller/IdVerificationImportController.php
src/Controller/IncentiveImportController.php
src/Controller/PatientStatusController.php

| Target Release?     | 3.5.1 
| Jira Ticket(s)      | HPRO-1478

[HPRO-1478] Fix doctrine slice method type hint

---

templates/program/hpo/navbar.html.twig
templates/program/nph/navbar.html.twig

| Target Release?     | 3.5.1 
| Jira Ticket(s)      | HPRO-1482

[HPRO-1482] Fix navbar return to home issue

---

migrations/Version20230502194526.php
src/Entity/Order.php
src/Service/OrderService.php
templates/biobank/partials/biobank-order-details.html.twig
templates/order/header.html.twig
web/assets/css/app.css

| Target Release?     | 3.6.0 
| Jira Ticket(s)      | HPRO-1402

[HPRO-1402] Save and display order finalization submission time
